// tests/test_reference_arith.m
//
// Purely arithmetic, no curve models built (~28 s). Runs
// count_special_points_X0Nstar(N) and GenusStarQuotient(N) over 198 levels and
// compares against the literal expected values embedded below.
//
// Run with: tests/run.sh test_reference_arith
//
// This script is meant to be re-run after every sub-step of the module-split
// refactor (release_plan.md, Step 4). It must stay self-contained: a
// self-review grep for the export-excluded results directory against this
// file must return nothing, and this script never opens a file at runtime;
// every expected value below is a literal embedded in this file.
//
// Provenance of the literal table below (derived once, not at runtime; the
// exact derivation snippet is recorded in the task-5 report, not here so this
// file has no runtime or review-time dependency on it):
//   - 166 of the 198 rows are (N, genus, special) triples read from the
//     five per-genus (g=3..7) "special vs found" tables generated by the
//     squarefree PointSearch(B=1e6) sweep (columns: N, found, special;
//     31 + 36 + 39 + 27 + 33 rows respectively; header lines start with #).
//   - The remaining 32 rows are the genus-8 levels: N and special_points read
//     from the models[] entries of data/genus8_models.m (genus is always 8
//     there).
//
// release_plan.md §2.0 verified (2026-07-25) that all 198 values match the
// stored columns with zero drift, so a fully green run is the expected
// result. If a mismatch appears here, that is a real finding about the
// current code, report it, do not edit the expected value to match.
//
// Caveat on what this suite can and cannot catch: every `special` value in
// the table below was itself produced by count_special_points_X0Nstar (via
// RationalCMDiscs) -- the PointSearch sweep tables and data/genus8_models.m
// both call the same code path this suite asserts against. So this is a
// regression-drift check, not an independent verification: a bug already
// present in RationalCMDiscs when the table was generated would be silently
// enshrined here as "expected" and this suite would stay green. Only the 14
// levels also covered by tests/test_exceptional_tables.m (178, 183, 246,
// 290, 310, 318, 329, 430, 455, 510, 137, 311, 370, 399) have any
// independent corroboration, via that suite's paper-sourced exceptional-
// point tables. The other 184 levels have none.

load "src/AtkinLehner.m";
load "tests/assertions.m";

results := NewResults();

// =========================================================================
// Literal reference table: <N, genus, special>.
// genus 3..7 rows come from the per-genus special-vs-found tables; genus 8
// rows come from data/genus8_models.m. See provenance note above.
// =========================================================================
levels := [
    <97, 3, 10>,
    <109, 3, 9>,
    <113, 3, 8>,
    <127, 3, 8>,
    <139, 3, 7>,
    <149, 3, 7>,
    <151, 3, 8>,
    <178, 3, 10>,
    <179, 3, 6>,
    <183, 3, 10>,
    <185, 3, 7>,
    <187, 3, 6>,
    <194, 3, 10>,
    <203, 3, 6>,
    <217, 3, 6>,
    <239, 3, 5>,
    <246, 3, 11>,
    <249, 3, 6>,
    <258, 3, 11>,
    <282, 3, 9>,
    <290, 3, 10>,
    <295, 3, 5>,
    <303, 3, 4>,
    <310, 3, 7>,
    <318, 3, 10>,
    <329, 3, 4>,
    <429, 3, 5>,
    <430, 3, 7>,
    <455, 3, 7>,
    <462, 3, 6>,
    <510, 3, 7>,
    <137, 4, 8>,
    <173, 4, 6>,
    <199, 4, 8>,
    <201, 4, 11>,
    <202, 4, 11>,
    <214, 4, 9>,
    <219, 4, 11>,
    <247, 4, 5>,
    <251, 4, 6>,
    <254, 4, 8>,
    <259, 4, 7>,
    <262, 4, 7>,
    <267, 4, 5>,
    <273, 4, 11>,
    <305, 4, 7>,
    <311, 4, 4>,
    <319, 4, 5>,
    <321, 4, 6>,
    <322, 4, 8>,
    <334, 4, 5>,
    <335, 4, 4>,
    <341, 4, 6>,
    <345, 4, 9>,
    <354, 4, 10>,
    <355, 4, 5>,
    <366, 4, 10>,
    <370, 4, 9>,
    <374, 4, 7>,
    <385, 4, 6>,
    <395, 4, 5>,
    <399, 4, 9>,
    <426, 4, 8>,
    <434, 4, 6>,
    <483, 4, 3>,
    <546, 4, 7>,
    <570, 4, 8>,
    <157, 5, 9>,
    <181, 5, 9>,
    <218, 5, 10>,
    <226, 5, 11>,
    <227, 5, 4>,
    <235, 5, 8>,
    <237, 5, 11>,
    <253, 5, 8>,
    <263, 5, 6>,
    <278, 5, 7>,
    <302, 5, 6>,
    <323, 5, 5>,
    <339, 5, 7>,
    <371, 5, 5>,
    <377, 5, 4>,
    <382, 5, 6>,
    <391, 5, 6>,
    <393, 5, 4>,
    <402, 5, 11>,
    <406, 5, 8>,
    <407, 5, 5>,
    <410, 5, 8>,
    <413, 5, 3>,
    <418, 5, 8>,
    <435, 5, 7>,
    <438, 5, 8>,
    <442, 5, 6>,
    <465, 5, 8>,
    <494, 5, 7>,
    <551, 5, 2>,
    <555, 5, 7>,
    <574, 5, 6>,
    <595, 5, 7>,
    <645, 5, 6>,
    <663, 5, 4>,
    <714, 5, 6>,
    <770, 5, 6>,
    <798, 5, 7>,
    <910, 5, 4>,
    <163, 6, 11>,
    <197, 6, 8>,
    <211, 6, 8>,
    <223, 6, 7>,
    <265, 6, 9>,
    <269, 6, 6>,
    <271, 6, 6>,
    <274, 6, 11>,
    <291, 6, 11>,
    <301, 6, 9>,
    <314, 6, 10>,
    <327, 6, 10>,
    <359, 6, 7>,
    <398, 6, 5>,
    <447, 6, 4>,
    <451, 6, 5>,
    <470, 6, 9>,
    <506, 6, 7>,
    <561, 6, 5>,
    <590, 6, 6>,
    <598, 6, 4>,
    <609, 6, 4>,
    <615, 6, 5>,
    <627, 6, 4>,
    <670, 6, 7>,
    <690, 6, 9>,
    <858, 6, 3>,
    <193, 7, 11>,
    <229, 7, 9>,
    <233, 7, 7>,
    <241, 7, 8>,
    <257, 7, 6>,
    <281, 7, 8>,
    <298, 7, 11>,
    <309, 7, 11>,
    <326, 7, 9>,
    <358, 7, 9>,
    <365, 7, 6>,
    <411, 7, 7>,
    <437, 7, 3>,
    <445, 7, 6>,
    <446, 7, 7>,
    <474, 7, 11>,
    <478, 7, 5>,
    <498, 7, 10>,
    <501, 7, 5>,
    <518, 7, 8>,
    <519, 7, 5>,
    <527, 7, 2>,
    <530, 7, 11>,
    <582, 7, 9>,
    <623, 7, 3>,
    <638, 7, 7>,
    <646, 7, 4>,
    <658, 7, 6>,
    <671, 7, 4>,
    <710, 7, 4>,
    <861, 7, 3>,
    <870, 7, 8>,
    <897, 7, 3>,
    <293, 8, 5>,
    <383, 8, 3>,
    <431, 8, 5>,
    <479, 8, 4>,
    <346, 8, 10>,
    <362, 8, 9>,
    <381, 8, 10>,
    <403, 8, 7>,
    <415, 8, 6>,
    <427, 8, 6>,
    <505, 8, 6>,
    <511, 8, 7>,
    <545, 8, 6>,
    <559, 8, 6>,
    <573, 8, 4>,
    <581, 8, 4>,
    <534, 8, 11>,
    <606, 8, 10>,
    <651, 8, 9>,
    <654, 8, 11>,
    <665, 8, 7>,
    <682, 8, 4>,
    <715, 8, 5>,
    <759, 8, 5>,
    <782, 8, 3>,
    <805, 8, 6>,
    <814, 8, 5>,
    <1001, 8, 3>,
    <930, 8, 9>,
    <966, 8, 6>,
    <1155, 8, 6>,
    <1190, 8, 3>
];

AssertEqual(~results, #levels, 198, "literal table has 198 levels");

// =========================================================================
// 5a. count_special_points_X0Nstar over all 198 levels.
// =========================================================================
printf "\n=== test_reference_arith: count_special_points_X0Nstar over %o levels ===\n", #levels;
for tup in levels do
    N := tup[1];
    g := tup[2];
    expected_special := tup[3];
    AssertEqual(~results, count_special_points_X0Nstar(N), expected_special,
        Sprintf("N=%o (genus %o): count_special_points_X0Nstar", N, g));
end for;

// =========================================================================
// 5c. GenusStarQuotient over the same 198 levels, checked against the genus
// recorded alongside each level above. This is a free exact oracle and the
// only real coverage of the star_quotients module reached by the current
// tests (release_plan.md §2.0: 1 of 11 functions reached).
// =========================================================================
printf "\n=== test_reference_arith: GenusStarQuotient over %o levels ===\n", #levels;
for tup in levels do
    N := tup[1];
    expected_genus := tup[2];
    AssertEqual(~results, GenusStarQuotient(N), expected_genus,
        Sprintf("N=%o: GenusStarQuotient", N));
end for;

// =========================================================================
// Summary
// =========================================================================
printf "\n";
Report(~results, "test_reference_arith");
