// test_cm_field_of_definition.m
// Regression test for FieldsOfDefinitionOfCMPoint (src/fields_of_definition.m).
//
// Q(P) is the subfield of the ring class field H_R fixed by sigma = c . sigma_a
// (c = complex conjugation, [a] in Pic(R)/Pic(R)^2 satisfying the quaternion
// condition).  See arXiv:math/0612732v2, Gonzalez-Rotger, Appendix.
//
// It is single-valued except for one genuine source of multiplicity:
//   GR Remark (uniqueness): [a] is determined by the quaternion condition only
//   when f = 1.  For f > 1 several classes can satisfy it, each giving a field.
//   Pinned below by N = 377, d = -36 (f = 3) -> {Q(sqrt(-3)), Q(sqrt(3))}.
//
// There is a second, spurious source that an earlier implementation reported as
// real: enumerating every order-2 automorphism of H_R restricting to complex
// conjugation on K.  When Pic(R) has exponent > 2, every c . tau for tau in
// Gal(H_R/K) = Pic(R) has order 2 and restricts to conjugation on K, so that
// enumeration returns the whole coset, exactly h candidates, every time; and
// then dedups.  The answer it produced was the union over levels, which always
// contains the right field and so looked correct.
//
// The current implementation instead works inside the Atkin-Lehner-fixed field
// A_abs, so it is level-aware: d = -39 gives Q(sqrt(13)) at N = 286 but
// Q(sqrt(-3)) at N = 26.  The old approach could not express that distinction.
//
// Expected values below are generated by scripts/gen_cm_field_expectations.m from
// ShimuraCurveALQuotients/SchoferFormula.m (intrinsic FieldsOfDefinitionOfCMPointFast),
// specialised to D = 1, W = all of Divisors(N).  This test itself has no dependency
// on that repo.
//
// Run with: tests/run.sh test_cm_field_of_definition

load "src/AtkinLehner.m";
load "tests/assertions.m";

results := NewResults();

// Tag a field of degree <= 2 by the squarefree part of its discriminant
// (1 for Q); tag higher-degree fields by 10000*degree.  Must match Tag() in
// scripts/gen_cm_field_expectations.m.
function FieldTag(F)
    if Degree(F) eq 1 then return 1; end if;
    if Degree(F) gt 2 then return 10000*Degree(F); end if;
    return Squarefree(Discriminant(MaximalOrder(F)));
end function;

function DistinctTags(flds)
    return Sort(SetToSequence({FieldTag(F) : F in flds}));
end function;

printf "\n=== FieldsOfDefinitionOfCMPoint: fields agree with the reference ===\n";

// <N, d, #fields, sorted distinct field tags>
cases := [
    <11, -39, 1, [ 40000 ]>,
    <11, -95, 1, [ 80000 ]>,
    <11, -36, 0, []>,
    <11, -32, 2, [ -1, 2 ]>,
    <11, -20, 0, []>,
    <11, -23, 0, []>,
    <11, -84, 1, [ 40000 ]>,
    <26, -39, 1, [ -3 ]>,
    <26, -95, 1, [ 80000 ]>,
    <26, -36, 1, [ 1 ]>,
    <26, -32, 0, []>,
    <26, -20, 0, []>,
    <26, -23, 1, [ 30000 ]>,
    <26, -84, 0, []>,
    <39, -39, 1, [ 13 ]>,
    <39, -95, 1, [ 80000 ]>,
    <39, -36, 2, [ -3, 3 ]>,
    <39, -32, 0, []>,
    <39, -20, 0, []>,
    <39, -23, 1, [ 30000 ]>,
    <39, -84, 0, []>,
    <77, -39, 0, []>,
    <77, -95, 0, []>,
    <77, -36, 0, []>,
    <77, -32, 0, []>,
    <77, -20, 0, []>,
    <77, -23, 0, []>,
    <77, -84, 1, [ -3 ]>,
    <143, -39, 1, [ -3 ]>,
    <143, -95, 1, [ 80000 ]>,
    <143, -36, 0, []>,
    <143, -32, 0, []>,
    <143, -20, 0, []>,
    <143, -23, 0, []>,
    <143, -84, 0, []>,
    <286, -39, 1, [ 13 ]>,
    <286, -95, 1, [ 80000 ]>,
    <286, -36, 0, []>,
    <286, -32, 0, []>,
    <286, -20, 0, []>,
    <286, -23, 0, []>,
    <286, -84, 0, []>,
    <377, -39, 0, []>,
    <377, -95, 0, []>,
    <377, -36, 2, [ -3, 3 ]>,
    <377, -32, 0, []>,
    <377, -20, 0, []>,
    <377, -23, 1, [ 30000 ]>,
    <377, -84, 0, []>,
    <510, -39, 0, []>,
    <510, -95, 0, []>,
    <510, -36, 1, [ 1 ]>,
    <510, -32, 0, []>,
    <510, -20, 0, []>,
    <510, -23, 0, []>,
    <510, -84, 1, [ 1 ]>,
];

// FieldTag collapses every field of degree > 2 to 10000*Degree(F), so tags
// alone cannot distinguish one degree-8 field from several, and "several
// where there should be one" is exactly the bug this port fixes (see header).
// Assert #flds alongside the tags so the high-degree rows stay discriminating
// instead of silently passing on a wrong count with matching tags.
rc := AssociativeArray();
for c in cases do
    N := c[1]; d := c[2]; expected_n := c[3]; expected := c[4];
    flds, rc := FieldsOfDefinitionOfCMPoint(N, d : rc_cache := rc);
    got := DistinctTags(flds);
    AssertEqual(~results, (#flds eq expected_n) and (got eq expected), true,
        Sprintf("N=%o, d=%o: %o field(s) with tags %o (got %o with %o)",
            N, d, expected_n, expected, #flds, got));
end for;

// Proposition 5.6 early exit still returns the empty list.
flds_empty, _ := FieldsOfDefinitionOfCMPoint(26, -32);
AssertEqual(~results, #flds_empty, 0,
    "N=26, d=-32: Prop 5.6 rules out a CM point, empty list");

// All candidates for a given (N, d) must share one degree; the degree is
// well defined even when the field is not, which is what
// DegreeOfFieldOfDefinitionOfCMPoint relies on.  Only c[1], c[2] are used
// here; "#flds eq 0" below corresponds to "c[3] = 0" (no CM point) above.
printf "\n=== degree is single-valued and agrees with the fast degree function ===\n";
for c in cases do
    N := c[1]; d := c[2];
    flds, rc := FieldsOfDefinitionOfCMPoint(N, d : rc_cache := rc);
    if #flds eq 0 then continue; end if;
    degs := {Degree(F) : F in flds};
    fast := DegreeOfFieldOfDefinitionOfCMPoint(N, d);
    AssertEqual(~results, #degs eq 1 and fast in degs, true,
        Sprintf("N=%o, d=%o: all candidates have degree %o (fast function says %o)",
            N, d, degs, fast));
end for;

Report(~results, "test_cm_field_of_definition");
