// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = 5.
// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical
// saturated-HNF star basis. Cusp forms not stored.
// All curves of this genus live in the single shared projective space P below.
//   models[N]`curve          : the curve X_0(N)^* in P
//   models[N]`special_points : number of special (CM + cusp) rational points

Q := Rationals();
P<x, y, z, w, t> := ProjectiveSpace(Q, 4);
ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, 
curve >;
models := AssociativeArray();


// ---- N = 157,  [ <157, 1> ],  special points = 9 ----
models[157] := rec< ModelRec | N := 157, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + y*w + 4*y*t - z^2 - 3*z*t - 4*w*t - 2*t^2,
    x*w - y*z + 3*y*t - z*w + z*t - 3*w*t - 5*t^2,
    x*t - y*w + z*w - z*t + w^2 - 2*w*t - t^2
]) >;


// ---- N = 181,  [ <181, 1> ],  special points = 9 ----
models[181] := rec< ModelRec | N := 181, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 3*z*w - 7*z*t + w^2 - 6*w*t + 9*t^2,
    x*t - y*w + z*w - z*t + w^2 - 2*w*t - t^2,
    y*t - z*w + z*t + w*t - 3*t^2,
    x^2*z - x*y^2 + x*w^2 + 3*y^2*w - 7*y*z*w - 6*y*w^2 + 7*z^2*w - 7*z^2*t + 
13*z*w^2 - 17*z*w*t + 2*z*t^2 + 3*w^3 - 12*w^2*t + 12*w*t^2 + 9*t^3,
    x^2*w - x*w^2 - y^3 + 2*y*z^2 + 2*y*z*w - 2*y*w^2 + z^3 - 13*z^2*w + 3*z^2*t
+ 6*z*w^2 + 27*z*w*t - 27*z*t^2 + 3*w^3 - 13*w^2*t - 22*w*t^2 + 27*t^3,
    x^2*t - y^2*z + y*z^2 + y*z*w - y*w^2 + z^3 - 3*z^2*w - 5*z^2*t - 2*z*w^2 + 
17*z*w*t - 3*z*t^2 + w^3 + 4*w^2*t - 29*w*t^2 + 5*t^3,
    x*y*z - y^3 + 3*y*z*w + y*w^2 - 7*z^2*w + 7*z^2*t - 6*z*w^2 + 22*z*w*t - 
30*z*t^2 + 6*w^2*t - 27*w*t^2 + 27*t^3,
    x*y*w - x*w^2 - y^2*z - y^2*w + y*z^2 + 2*y*z*w + y*w^2 + z^3 - 4*z^2*w - 
4*z^2*t - z*w^2 + 12*z*w*t - z*t^2 - 13*w*t^2 + 6*t^3,
    x*y*t - y^2*w + y*z*w + y*w^2 - z^2*w + z^2*t - 2*z*w^2 + 2*z*w*t - 2*z*t^2 
+ 2*w^2*t - 5*w*t^2 - 3*t^3,
    x*z^2 - y^2*z + 3*z^2*w - 7*z^2*t + z*w^2 - 6*z*w*t + 9*z*t^2,
    x*z*w - y^2*w + 3*z*w^2 - 7*z*w*t + w^3 - 6*w^2*t + 9*w*t^2,
    x*z*t - y*z*w + z^2*w - z^2*t + z*w^2 - 2*z*w*t - z*t^2,
    x*w*t - y*w^2 + z*w^2 - z*w*t + w^3 - 2*w^2*t - w*t^2,
    x*t^2 - z*w^2 + 2*z*w*t - z*t^2 + 2*w^2*t - 5*w*t^2 - t^3,
    y^2*t - y*z*w + z^2*w - z^2*t + z*w^2 - 5*z*w*t + 6*z*t^2 - w^2*t + 6*w*t^2 
- 9*t^3,
    y*z*t - z^2*w + z^2*t + z*w*t - 3*z*t^2,
    y*w*t - z*w^2 + z*w*t + w^2*t - 3*w*t^2,
    y*t^2 - z*w*t + z*t^2 + w*t^2 - 3*t^3
]) >;


// ---- N = 218,  [ <2, 1>, <109, 1> ],  special points = 10 ----
models[218] := rec< ModelRec | N := 218, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + y*w + 2*y*t - z^2 - z*w - 2*z*t + w*t + t^2,
    x*w - y*z + 2*y*t - z*w - w*t,
    x*t - y*w + w^2 - 2*t^2
]) >;


// ---- N = 226,  [ <2, 1>, <113, 1> ],  special points = 11 ----
models[226] := rec< ModelRec | N := 226, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + y*w + 2*y*t - z^2 - 2*w*t - 2*t^2,
    x*w - y*z - y*w + 2*y*t + z^2 - z*t - w*t - 2*t^2,
    x*t - 2*y*w + y*t + z^2 - 2*z*t + w^2 + w*t - 3*t^2
]) >;


// ---- N = 227,  [ <227, 1> ],  special points = 4 ----
models[227] := rec< ModelRec | N := 227, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - x*t - y^2 + 3*y*t + z^2 - z*w - 5*z*t + w^2 - 2*w*t + 4*t^2,
    x*w - x*t - y*z + 2*y*t + 2*z*t - w^2 - w*t - 2*t^2,
    y*w - y*t - z^2 + 3*z*t - w^2 + w*t - 2*t^2,
    x^2*z - x*y^2 - x*t^2 + y^2*z - 6*y^2*t - y*z^2 + y*z*t + 24*y*t^2 - z^3 + 
5*z^2*w + 9*z^2*t - 5*z*w^2 - 11*z*w*t - 32*z*t^2 + 4*w^3 - w^2*t + 12*t^3,
    x^2*w - 5*x*t^2 - y^3 + 4*y^2*t + y*z^2 - 9*y*z*t + 10*y*t^2 - 3*z^3 + 
3*z^2*w + 9*z^2*t - 4*z*w^2 + z*w*t - 2*z*t^2 + w^3 - 5*w^2*t - 4*t^3,
    x^2*t - 5*x*t^2 - y^2*t - y*z*t + 6*y*t^2 - z^3 + z^2*w + 5*z^2*t - z*w^2 - 
z*w*t - 8*z*t^2 + 2*w^2*t - 5*w*t^2 + 10*t^3,
    x*y*z - 2*x*t^2 - y^3 + 3*y^2*t + y*z^2 - 7*y*z*t + 2*y*t^2 - z^3 + 3*z^2*t 
- z*w*t + 2*z*t^2 - w*t^2 + 2*t^3,
    x*y*w - 2*x*t^2 - y^2*z + 2*y^2*t + y*z*t - 5*y*t^2 - 2*z^2*w - z^2*t + 
z*w^2 + 4*z*w*t + 7*z*t^2 - 2*w^3 + w^2*t - 4*w*t^2,
    x*y*t - 2*x*t^2 - y*z*t - y*t^2 - z^2*w + z^2*t + z*w^2 + z*w*t + z*t^2 - 
w^3 + 2*w^2*t - 4*w*t^2 + 4*t^3,
    x*z^2 - x*t^2 - y^2*z - y^2*t + 3*y*z*t + 3*y*t^2 + z^3 - z^2*w - 4*z^2*t + 
z*w^2 - 3*z*w*t - z*t^2 + w^2*t - 2*w*t^2 + 4*t^3,
    x*z*w - x*t^2 - y^2*t - y*z^2 + 2*y*z*t + 3*y*t^2 + 3*z^2*t - z*w^2 - 
2*z*w*t - 7*z*t^2 + w^2*t - 2*w*t^2 + 4*t^3,
    x*z*t - x*t^2 - y^2*t + 3*y*t^2 + z^2*t - z*w*t - 5*z*t^2 + w^2*t - 2*w*t^2 
+ 4*t^3,
    x*w^2 - x*t^2 - 2*y*z*t + 4*y*t^2 - z^3 + 5*z^2*t - z*w^2 + 3*z*w*t - 
6*z*t^2 - w^3 - 5*w*t^2 + 2*t^3,
    x*w*t - x*t^2 - y*z*t + 2*y*t^2 + 2*z*t^2 - w^2*t - w*t^2 - 2*t^3,
    y^2*w - y^2*t - y*z^2 + 3*y*z*t - 2*y*t^2 - z^2*w + 3*z*w*t - w^3 + w^2*t - 
2*w*t^2,
    y*z*w - y*z*t - z^3 + 3*z^2*t - z*w^2 + z*w*t - 2*z*t^2,
    y*w^2 - y*t^2 - z^2*w - z^2*t + 3*z*w*t + 3*z*t^2 - w^3 - w*t^2 - 2*t^3,
    y*w*t - y*t^2 - z^2*t + 3*z*t^2 - w^2*t + w*t^2 - 2*t^3
]) >;


// ---- N = 235,  [ <5, 1>, <47, 1> ],  special points = 8 ----
models[235] := rec< ModelRec | N := 235, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + 3*y*w - 5*y*t - 3*z^2 + 2*z*w + 9*z*t - 2*w^2 - w*t - 6*t^2,
    x*w - y*z + y*w - 2*y*t - z^2 + z*w + 7*z*t - w^2 - 3*w*t - 6*t^2,
    2*x*t + y*w - 2*y*t - z^2 + 4*z*t - w^2 - 8*t^2
]) >;


// ---- N = 237,  [ <3, 1>, <79, 1> ],  special points = 11 ----
models[237] := rec< ModelRec | N := 237, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 - 2*y*w + 5*y*t + 2*z^2 - 4*z*w - 3*z*t + 4*w^2 + 4*w*t - 8*t^2,
    x*w - y*z - 2*y*w + 2*y*t + 2*z^2 - 2*z*w - z*t + 2*w^2 + 3*w*t - 6*t^2,
    2*x*t - 5*y*w + 4*y*t + 3*z^2 - 4*z*w - 2*z*t + 6*w^2 + 6*w*t - 14*t^2
]) >;


// ---- N = 253,  [ <11, 1>, <23, 1> ],  special points = 8 ----
models[253] := rec< ModelRec | N := 253, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*w - y*z + y*w - z^2 + z*w + z*t - 2*w*t,
    x*t - z^2 + z*t + w^2 - w*t - t^2,
    y*t - z*w + z*t - w^2 + w*t - t^2,
    x^2*z - x*y^2 - x*y*z + y^3 + y^2*w - 4*y*w^2 - 3*z^3 + 5*z^2*w - z^2*t + 
7*z*w^2 - 8*z*w*t + 3*w^3 - w^2*t + w*t^2,
    x^2*w - x*y*z + y^2*w - y*w^2 - 2*z^2*t - z*w^2 + 5*z*w*t - z*t^2 + w^3 + 
w^2*t - 3*w*t^2,
    x^2*t - y^2*z + 2*y^2*w - 2*y*z^2 + 3*y*z*w - 2*y*w^2 - z^3 + 4*z^2*w - 
3*z^2*t - 3*z*w^2 + 2*z*w*t + z*t^2 - 2*w^3 + 7*w^2*t - 5*w*t^2 - t^3,
    x*y*w - y^2*z + y^2*w - y*z^2 + y*z*w + z^2*w - z^2*t - z*w^2 + z*w*t + 
z*t^2 - 2*w^3 + 2*w^2*t - 2*w*t^2,
    x*y*t - y*z^2 + y*w^2 + z^2*w - z^2*t - z*w*t + 2*z*t^2 - w^3 - t^3,
    x*z^2 - y^2*z + 2*y^2*w - 2*y*z^2 + 2*y*z*w - y*w^2 - 2*z^3 + 4*z^2*w - 
z^2*t - z*w^2 + z*w*t - z*t^2 - 3*w^3 + 5*w^2*t - 3*w*t^2,
    x*z*w - y*z^2 + y*z*w - z^3 + z^2*w + z^2*t - 2*z*w*t,
    x*z*t - z^3 + z^2*t + z*w^2 - z*w*t - z*t^2,
    x*w^2 - y*z*w + y*w^2 - z^2*w + z*w^2 + z*w*t - 2*w^2*t,
    x*w*t - z^2*w + z*w*t + w^3 - w^2*t - w*t^2,
    x*t^2 - z^2*t + z*t^2 + w^2*t - w*t^2 - t^3,
    y^2*t - y*z*w - y*w^2 + z^2*w - z^2*t + 2*z*w^2 - 3*z*w*t + 2*z*t^2 + w^3 - 
2*w^2*t + 2*w*t^2 - t^3,
    y*z*t - z^2*w + z^2*t - z*w^2 + z*w*t - z*t^2,
    y*w*t - z*w^2 + z*w*t - w^3 + w^2*t - w*t^2,
    y*t^2 - z*w*t + z*t^2 - w^2*t + w*t^2 - t^3
]) >;


// ---- N = 263,  [ <263, 1> ],  special points = 6 ----
models[263] := rec< ModelRec | N := 263, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 2*y*w + 5*y*t - z^2 - 2*z*t - 3*w^2 + w*t - 7*t^2,
    x*w - y*z + y*w + 2*y*t + z*t - 2*w^2 - w*t - 4*t^2,
    x*t - y*t - z*w + z*t + w^2 - w*t
]) >;


// ---- N = 278,  [ <2, 1>, <139, 1> ],  special points = 7 ----
models[278] := rec< ModelRec | N := 278, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + y*w + 2*y*t - 2*z*w + 2*w^2 - 5*w*t + 3*t^2,
    x*w - y*z - z*w + 2*z*t + w^2 - 3*w*t + 2*t^2,
    x*t - z*w + w^2 - 2*w*t + t^2
]) >;


// ---- N = 302,  [ <2, 1>, <151, 1> ],  special points = 6 ----
models[302] := rec< ModelRec | N := 302, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - x*w - y^2 + y*z + y*w - z^2 - z*t + w*t,
    x*t - y*w - z*t + w^2 - t^2,
    y*t - z*w - z*t + w^2,
    x^2*z - x*y^2 + y*z^2 - 3*y*z*w - y*w^2 + z^3 - 3*z^2*t + 4*z*w^2 + 3*z*w*t 
- 2*z*t^2 - 2*w^3 - w*t^2 + t^3,
    x^2*w - x*w^2 - y^3 + 2*y^2*w - y*z^2 + 2*y*z*w - 5*y*w^2 + 2*z^2*w + 
2*z^2*t - 3*z*w^2 - 3*z*w*t + z*t^2 + 4*w^3 + w^2*t - 2*w*t^2 - t^3,
    x^2*t - y^2*z + 2*y*z*w - y*w^2 - z^3 + z^2*w + z^2*t - 4*z*w^2 - 4*z*w*t - 
z*t^2 + 4*w^3 + 2*w^2*t - 2*t^3,
    x*y*z - x*w^2 - y^3 + y^2*w - y*z^2 + 3*y*z*w - y*w^2 - z^3 + z^2*t - 
2*z*w^2 - 2*z*w*t + z*t^2 + 2*w^3 + w^2*t - t^3,
    x*y*w - x*w^2 - y^2*z + 3*y*z*w - y*w^2 - z^3 + z^2*w + 2*z^2*t - 4*z*w^2 - 
3*z*w*t + z*t^2 + 3*w^3 + w^2*t - t^3,
    x*y*t - y^2*w + y*w^2 - z^2*w - z^2*t + z*w^2 - z*w*t - z*t^2 + w^2*t,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z^2 + 2*y*z*w + y*w^2 - z^3 - z^2*w - 
z^2*t + w^2*t,
    x*z*w - x*w^2 - y^2*w + y*z*w + y*w^2 - z^2*w - z*w*t + w^2*t,
    x*z*t - y*z*w - z^2*t + z*w^2 - z*t^2,
    x*w*t - y*w^2 - z*w*t + w^3 - w*t^2,
    x*t^2 - z*w^2 - z*w*t - z*t^2 + w^3 + w^2*t - t^3,
    y^2*t - y*z*w + y*w^2 - z^2*w - z^2*t + z*w^2,
    y*z*t - z^2*w - z^2*t + z*w^2,
    y*w*t - z*w^2 - z*w*t + w^3,
    y*t^2 - z*w*t - z*t^2 + w^2*t
]) >;


// ---- N = 323,  [ <17, 1>, <19, 1> ],  special points = 5 ----
models[323] := rec< ModelRec | N := 323, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*w - y*z + z*w - w^2 - w*t,
    x*t - z^2 + z*w - w*t - t^2,
    y*t - z*w + w^2 - w*t,
    x^2*z - x*y^2 + y*z^2 - 2*y*z*w + y*w^2 - 3*z^3 + 4*z^2*w - 3*z^2*t + 
2*z*w^2 + 2*z*w*t - 3*z*t^2 - 3*w^3 + 2*w^2*t + t^3,
    x^2*w - x*y*z + y*z^2 - y*z*w - 2*z^2*w + 3*z*w^2 + z*w*t - w^3 - 2*w^2*t - 
w*t^2,
    x^2*t - y^2*z + y*z^2 + y*z*w - y*w^2 - z^3 - 2*z^2*t - z*w^2 + 2*z*w*t - 
3*z*t^2 + 2*w^3 + w^2*t - w*t^2,
    x*y*w - y^2*z + y*z*w - y*w^2 - z*w^2 + w^3 - w^2*t,
    x*y*t - y*z^2 + y*z*w - z*w^2 - z*w*t + w^3 - w*t^2,
    x*z^2 - y^2*z + y*z*w - y*w^2 - z^3 + 2*z^2*w - z^2*t - 3*z*w^2 - 3*z*t^2 + 
2*w^3 + 2*w^2*t + w*t^2 + t^3,
    x*z*w - y*z^2 + z^2*w - z*w^2 - z*w*t,
    x*z*t - z^3 + z^2*w - z*w*t - z*t^2,
    x*w^2 - y*z*w + z*w^2 - w^3 - w^2*t,
    x*w*t - z^2*w + z*w^2 - w^2*t - w*t^2,
    x*t^2 - z^2*t + z*w*t - w*t^2 - t^3,
    y^2*t - y*z*w + y*w^2 - z*w^2 + w^3 - w^2*t,
    y*z*t - z^2*w + z*w^2 - z*w*t,
    y*w*t - z*w^2 + w^3 - w^2*t,
    y*t^2 - z*w*t + w^2*t - w*t^2
]) >;


// ---- N = 339,  [ <3, 1>, <113, 1> ],  special points = 7 ----
models[339] := rec< ModelRec | N := 339, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 2*y*t - z*w - 2*z*t + w^2 + w*t,
    x*w - y*z + 2*y*t - z*w - z*t - t^2,
    x*t - y*w - z*t + w^2 + w*t
]) >;


// ---- N = 371,  [ <7, 1>, <53, 1> ],  special points = 5 ----
models[371] := rec< ModelRec | N := 371, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 - y*w + 3*y*t + z^2 - 2*z*t - w^2 + 3*w*t,
    x*w + 2*x*t - y*z + 2*y*t + z^2 + z*w - 2*z*t - w*t - t^2,
    3*x*t + y*w + 2*y*t - z^2 + z*w - 2*z*t + 2*w^2 - 5*w*t - 3*t^2
]) >;


// ---- N = 377,  [ <13, 1>, <29, 1> ],  special points = 4 ----
models[377] := rec< ModelRec | N := 377, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 - 2*y*t + z^2 - 2*z*w + z*t + 2*w^2 + 3*w*t,
    x*w - y*z - 2*y*w - 8*y*t + 4*z^2 - 5*z*w + 3*z*t + 4*w^2 + 9*w*t + 2*t^2,
    x*t + y*w + 2*y*t - z^2 + z*w - z*t - w^2 - 3*w*t - t^2
]) >;


// ---- N = 382,  [ <2, 1>, <191, 1> ],  special points = 6 ----
models[382] := rec< ModelRec | N := 382, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + y*w + y*t - z^2 - z*t - w*t,
    x*w - y*z - 2*y*w - y*t + 2*z^2 + z*w - z*t + w^2 + w*t - t^2,
    x*t + 2*y*w + 2*y*t - 3*z^2 - 2*z*w + 2*z*t - w^2 - 2*w*t - t^2
]) >;


// ---- N = 391,  [ <17, 1>, <23, 1> ],  special points = 6 ----
models[391] := rec< ModelRec | N := 391, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + y*w - z^2 + z*w - 2*z*t - 2*w*t + t^2,
    x*w - y*z - y*w + 3*y*t + z^2 - 2*z*w + 2*z*t + w*t - 3*t^2,
    x*t - y*w + y*t + z*t - 2*t^2
]) >;


// ---- N = 393,  [ <3, 1>, <131, 1> ],  special points = 4 ----
models[393] := rec< ModelRec | N := 393, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + y*w - y*t - z^2 + z*w - w^2 - w*t + t^2,
    x*w - y*z + y*w - y*t - z^2 + z*w + 2*z*t - w^2 - w*t,
    x*t - y*t - z^2 + z*w + z*t - t^2
]) >;


// ---- N = 402,  [ <2, 1>, <3, 1>, <67, 1> ],  special points = 11 ----
models[402] := rec< ModelRec | N := 402, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 2*y*t + z^2 - 2*z*w - z*t + w^2 - t^2,
    x*w + 5*x*t - y*z - 5*y*w + 4*y*t + 5*z^2 - 6*z*w - 7*z*t + w^2 - t^2,
    8*x*t - 7*y*w + 5*y*t + 7*z^2 - 8*z*w - 11*z*t + w^2 - t^2
]) >;


// ---- N = 406,  [ <2, 1>, <7, 1>, <29, 1> ],  special points = 8 ----
models[406] := rec< ModelRec | N := 406, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + y*w - z^2 - 2*z*t - 2*w*t + t^2,
    x*w - y*z + y*t + z*t - t^2,
    3*x*t - 2*y*w - z^2 + 3*z*w + z*t + w*t - 3*t^2
]) >;


// ---- N = 407,  [ <11, 1>, <37, 1> ],  special points = 5 ----
models[407] := rec< ModelRec | N := 407, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 - 5*y*w + 4*y*t + 5*z^2 - 3*z*w - 5*z*t + 8*w^2 - 5*w*t - t^2,
    x*w + x*t - y*z - 7*y*w + 4*y*t + 6*z^2 - 3*z*w - 6*z*t + 9*w^2 - 5*w*t - 
t^2,
    2*x*t - 9*y*w + 5*y*t + 7*z^2 - 3*z*w - 8*z*t + 11*w^2 - 6*w*t - t^2
]) >;


// ---- N = 410,  [ <2, 1>, <5, 1>, <41, 1> ],  special points = 8 ----
models[410] := rec< ModelRec | N := 410, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + y*w + y*t - z^2 - z*t,
    x*w + x*t - y*z + 2*y*w + y*t - 3*z^2 - z*w + 2*z*t - w*t - t^2,
    3*x*t + 10*y*w + 4*y*t - 13*z^2 - 4*z*w + 4*z*t - w^2 - 2*w*t - t^2
]) >;


// ---- N = 413,  [ <7, 1>, <59, 1> ],  special points = 3 ----
models[413] := rec< ModelRec | N := 413, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + y*t + z*t - 4*w^2 + 3*w*t - 3*t^2,
    x*w - y*z + y*t - w*t,
    x*t - y*w + z*w - z*t
]) >;


// ---- N = 418,  [ <2, 1>, <11, 1>, <19, 1> ],  special points = 8 ----
models[418] := rec< ModelRec | N := 418, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + z*w - z*t - w^2 + 2*t^2,
    x*w - y*z + y*w - z^2 + z*w + 2*z*t - w^2 - 3*w*t,
    x*t - y*w - y*t + z*w - w*t
]) >;


// ---- N = 435,  [ <3, 1>, <5, 1>, <29, 1> ],  special points = 7 ----
models[435] := rec< ModelRec | N := 435, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z + x*t - y^2 + 3*y*w - 3*y*t - 3*z^2 + z*w + 5*z*t - 2*w^2 + 3*w*t - 
4*t^2,
    x*w - y*z + 2*y*w - y*t - 2*z^2 + 7*z*t - w^2 - w*t - 3*t^2,
    2*x*t + 3*y*w - 4*y*t - 3*z^2 + 8*z*t - 2*w^2 + 2*w*t - 5*t^2
]) >;


// ---- N = 438,  [ <2, 1>, <3, 1>, <73, 1> ],  special points = 8 ----
models[438] := rec< ModelRec | N := 438, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z + 3*x*t - y^2 + 4*y*w - 4*y*t - 7*z^2 + z*w + 7*z*t + 5*w^2 - 7*w*t - 
3*t^2,
    x*w + x*t - y*z + 2*y*w - 2*y*t - 3*z^2 + z*w + 4*z*t + w^2 - 4*w*t - t^2,
    4*x*t + 3*y*w - 5*y*t - 7*z^2 + z*w + 8*z*t + 5*w^2 - 7*w*t - 4*t^2
]) >;


// ---- N = 442,  [ <2, 1>, <13, 1>, <17, 1> ],  special points = 6 ----
models[442] := rec< ModelRec | N := 442, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z + 14*x*t - y^2 - 3*y*w + 16*y*t - 11*z^2 - 15*z*w + 23*z*t - 5*w^2 + 
5*w*t - 12*t^2,
    x*w + 11*x*t - y*z - 4*y*w + 10*y*t - 7*z^2 - 11*z*w + 18*z*t - 3*w^2 + 
4*w*t - 7*t^2,
    15*x*t - 4*y*w + 16*y*t - 11*z^2 - 16*z*w + 24*z*t - 5*w^2 + 6*w*t - 13*t^2
]) >;


// ---- N = 465,  [ <3, 1>, <5, 1>, <31, 1> ],  special points = 8 ----
models[465] := rec< ModelRec | N := 465, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 - y*w + y*t + z^2 - z*w - z*t - w^2 - 2*w*t,
    x*w - y*z + y*w - z^2 + z*t + w*t,
    x*t - y*t - z^2 + z*w + w*t
]) >;


// ---- N = 494,  [ <2, 1>, <13, 1>, <19, 1> ],  special points = 7 ----
models[494] := rec< ModelRec | N := 494, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + y*w + 2*y*t - 2*z*w - 2*t^2,
    x*w - y*z - y*t - z*w + w^2 - w*t + t^2,
    x*t - z*w - w*t
]) >;


// ---- N = 551,  [ <19, 1>, <29, 1> ],  special points = 2 ----
models[551] := rec< ModelRec | N := 551, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 2, curve := Curve(P, [
    2*x*z - 2*y^2 - 2*y*w + 2*y*t + 2*z^2 + 3*z*t - w^2 + 4*w*t - 2*t^2,
    x*w - y*z + y*w - z^2 - z*t - 2*w*t,
    x*t - y*w - y*t + z*w + w*t
]) >;


// ---- N = 555,  [ <3, 1>, <5, 1>, <37, 1> ],  special points = 7 ----
models[555] := rec< ModelRec | N := 555, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - x*t - y^2 + 2*y*t + z^2 - z*t,
    x*w + x*t - y*z - z^2 + z*t - w*t - t^2,
    y*w + y*t - z^2 - z*w - w*t - t^2,
    x^2*z - x*y^2 - x*t^2 - 3*y^2*t + 3*y*t^2 + 6*z^3 + 5*z^2*w + 2*z^2*t - 
2*z*w^2 + z*w*t + z*t^2 + 2*w^2*t + 4*w*t^2 + 2*t^3,
    x^2*w + x*t^2 - y^3 + 4*y^2*t + 2*y*z^2 - 2*y*z*t - 2*y*t^2 - 3*z^3 - 
3*z^2*w - 3*z^2*t + z*w^2 + z*t^2 - w^2*t - 3*w*t^2 - 2*t^3,
    x^2*t - x*t^2 - y^2*z - y^2*t - 2*y*z^2 + 2*y*z*t + y*t^2 + z^3 + z^2*w + 
z^2*t - z*w*t - z*t^2,
    x*y*z - y^3 + 3*y^2*t - y*z*t - y*t^2 - 3*z^3 - 2*z^2*w + z*w^2 - z*w*t - 
z*t^2 - w^2*t - 2*w*t^2 - t^3,
    x*y*w - y^2*z - y^2*t + y*z*t + y*t^2 + 3*z^3 + 2*z^2*w - z^2*t - z*w^2 + 
z*t^2 + w^2*t + w*t^2,
    x*y*t + y^2*t - y*z^2 - y*t^2 - 3*z^3 - 2*z^2*w + z*w^2 - z*w*t - z*t^2 - 
w^2*t - 2*w*t^2 - t^3,
    x*z^2 - x*t^2 - y^2*z - y^2*t + 2*y*z*t + 2*y*t^2 + z^3 - z*t^2,
    x*z*w + x*t^2 + y^2*t - y*z^2 - 2*y*t^2 - z^3 - z*w*t,
    x*z*t - x*t^2 - y^2*t + 2*y*t^2 + z^2*t - z*t^2,
    x*w^2 - x*t^2 + 2*y*z*t - z^3 - 2*z^2*w + z^2*t - 2*z*t^2 - w^2*t + t^3,
    x*w*t + x*t^2 - y*z*t - z^2*t + z*t^2 - w*t^2 - t^3,
    y^2*w + y^2*t - y*z^2 + y*z*t - z^3 - z^2*w - z^2*t - 2*z*w*t - z*t^2 - 
w*t^2 - t^3,
    y*z*w + y*z*t - z^3 - z^2*w - z*w*t - z*t^2,
    y*w^2 - y*t^2 - z^2*w + z^2*t - z*w^2 + z*w*t - w^2*t + t^3,
    y*w*t + y*t^2 - z^2*t - z*w*t - w*t^2 - t^3
]) >;


// ---- N = 574,  [ <2, 1>, <7, 1>, <41, 1> ],  special points = 6 ----
models[574] := rec< ModelRec | N := 574, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 3*y*w - 3*z^2 + z*w + 5*z*t - 5*w^2 - 4*w*t - t^2,
    x*w - y*z + z*w - z*t,
    x*t - z^2 + 2*z*t - w^2 - 2*w*t - t^2
]) >;


// ---- N = 595,  [ <5, 1>, <7, 1>, <17, 1> ],  special points = 7 ----
models[595] := rec< ModelRec | N := 595, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + y*w + 2*y*t - z^2 + 2*z*t - w^2 + w*t - t^2,
    x*w - y*z - y*w + y*t + z^2 - w*t - t^2,
    x*t + 2*y*w + y*t - 2*z^2 + 4*z*t - w^2 + w*t - 2*t^2
]) >;


// ---- N = 645,  [ <3, 1>, <5, 1>, <43, 1> ],  special points = 6 ----
models[645] := rec< ModelRec | N := 645, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 5*y*w - y*t - 6*z^2 + 3*z*w + 7*z*t - 3*w*t - t^2,
    x*w - y*z + y*w - z^2 + 2*z*w + z*t - w^2 - w*t,
    x*t + 3*y*w - y*t - 5*z^2 + 3*z*w + 6*z*t - 3*w*t - t^2
]) >;


// ---- N = 663,  [ <3, 1>, <13, 1>, <17, 1> ],  special points = 4 ----
models[663] := rec< ModelRec | N := 663, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z + x*t - y^2 + y*w + 2*y*t - 2*z^2 - z*w + z*t - 2*w^2 - w*t - t^2,
    2*x*w + x*t - 2*y*z - y*w - y*t + 2*z*w - w*t + t^2,
    2*x*t + y*t - 2*z^2 + z*w + z*t - 2*w^2 - 2*w*t - t^2
]) >;


// ---- N = 714,  [ <2, 1>, <3, 1>, <7, 1>, <17, 1> ],  special points = 6 ----
models[714] := rec< ModelRec | N := 714, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + y*w + 4*y*t - z^2 - 3*z*w - w^2 + w*t - t^2,
    x*w - y*z - w^2 - w*t,
    x*t + y*w - 2*z^2 + z*t - 4*w*t - t^2
]) >;


// ---- N = 770,  [ <2, 1>, <5, 1>, <7, 1>, <11, 1> ],  special points = 6 ----
models[770] := rec< ModelRec | N := 770, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z + x*t - y^2 - 3*y*w + 2*y*t + 2*z^2 - z*w + 2*z*t - 2*w^2 + 3*w*t,
    x*w + x*t - y*z - 4*y*w + y*t + 3*z^2 + 5*z*t - 4*w^2 + 6*w*t,
    2*x*t - 5*y*w + 3*y*t + 3*z^2 - z*w + 5*z*t - 2*w^2 + 7*w*t
]) >;


// ---- N = 798,  [ <2, 1>, <3, 1>, <7, 1>, <19, 1> ],  special points = 7 ----
models[798] := rec< ModelRec | N := 798, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z + 6*x*t - y^2 - y*w - 7*y*t - 5*z^2 + 11*z*w - 3*z*t - 4*w^2 - 4*t^2,
    x*w + 2*x*t - y*z + y*w - 5*y*t - 3*z^2 + 6*z*w - 2*z*t - w^2 + 4*w*t + t^2,
    10*x*t - y*w - 12*y*t - 9*z^2 + 22*z*w - 3*z*t - 8*w^2 - 6*t^2
]) >;


// ---- N = 910,  [ <2, 1>, <5, 1>, <7, 1>, <13, 1> ],  special points = 4 ----
models[910] := rec< ModelRec | N := 910, genus := 5, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z + 31*x*t - y^2 + 61*y*w + 6*y*t - 92*z^2 - 36*z*w - 50*z*t + 14*w^2 - 
62*w*t - 2*t^2,
    x*w + 26*x*t - y*z + 51*y*w + 4*y*t - 77*z^2 - 31*z*w - 41*z*t + 12*w^2 - 
52*w*t - 2*t^2,
    32*x*t + 63*y*w + 6*y*t - 95*z^2 - 38*z*w - 51*z*t + 14*w^2 - 64*w*t - 2*t^2
]) >;


// ==== special-points table (genus 5) ====
//   N : special points
//   157 : 9
//   181 : 9
//   218 : 10
//   226 : 11
//   227 : 4
//   235 : 8
//   237 : 11
//   253 : 8
//   263 : 6
//   278 : 7
//   302 : 6
//   323 : 5
//   339 : 7
//   371 : 5
//   377 : 4
//   382 : 6
//   391 : 6
//   393 : 4
//   402 : 11
//   406 : 8
//   407 : 5
//   410 : 8
//   413 : 3
//   418 : 8
//   435 : 7
//   438 : 8
//   442 : 6
//   465 : 8
//   494 : 7
//   551 : 2
//   555 : 7
//   574 : 6
//   595 : 7
//   645 : 6
//   663 : 4
//   714 : 6
//   770 : 6
//   798 : 7
//   910 : 4

