// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = 6.
// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical
// saturated-HNF star basis. Cusp forms not stored.
// All curves of this genus live in the single shared projective space P below.
//   models[N]`curve          : the curve X_0(N)^* in P
//   models[N]`special_points : number of special (CM + cusp) rational points

Q := Rationals();
P<x, y, z, w, t, u> := ProjectiveSpace(Q, 5);
ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, curve >;
models := AssociativeArray();


// ---- N = 163,  [ <163, 1> ],  special points = 11 ----
models[163] := rec< ModelRec | N := 163, genus := 6, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + y*w - z^2 + 4*z*t - 2*z*u + 3*w^2 - 10*w*t - 2*w*u - t^2 + 3*t*u + 7*u^2,
    x*w - y*z + 3*z*t + 3*z*u + w^2 - 5*w*t - 6*w*u - t^2 + 2*u^2,
    x*t - y*w + z*t + 2*w^2 - 3*w*t + w*u - 3*t^2 - t*u,
    x*u - z*w + z*u + w^2 + w*t - 3*w*u - 3*t*u - u^2,
    y*t - z*w + 2*z*u + w*t + w*u - 2*t^2 - 4*t*u - 3*u^2,
    y*u - z*t + w*t - 2*w*u + t^2 - u^2
]) >;


// ---- N = 197,  [ <197, 1> ],  special points = 8 ----
models[197] := rec< ModelRec | N := 197, genus := 6, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + 5*y*t - 2*z*w - 7*z*t - z*u + 2*w^2 - 4*w*t + 6*w*u + 7*t^2 - 10*t*u + 3*u^2,
    x*w - y*z + 2*y*t - w^2 - 4*w*t + 3*w*u + 2*t^2 - 6*t*u + u^2,
    x*t - z^2 + z*w + z*t - w^2 - 2*w*t + 4*w*u - 7*t*u + u^2,
    x*u - z*t + 2*t^2 - 4*t*u - u^2,
    y*w - y*t - z^2 + z*w + 3*z*t - 2*w^2 - w*t + 2*w*u - t^2 - t*u - u^2,
    y*u - z*u - w*t + w*u + t^2 - t*u
]) >;


// ---- N = 211,  [ <211, 1> ],  special points = 8 ----
models[211] := rec< ModelRec | N := 211, genus := 6, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + 5*y*t - 5*z*w - z*t + 4*z*u + 6*w^2 - 6*w*t - w*u - 2*t^2 - 4*t*u - 2*u^2,
    x*w - y*z + y*t - z*w + 2*z*t + 4*z*u + w^2 - 5*w*t - 2*w*u - 2*t*u - 2*u^2,
    x*t - z^2 + 2*z*t + 3*z*u - 2*w*t - 2*t^2 - 3*t*u - 2*u^2,
    x*u - z*w + z*t + w*t + w*u - t^2 - 3*t*u - 2*u^2,
    y*w - y*t - z^2 + z*w + 2*z*t + 2*z*u - 2*w^2 - w*t - w*u + t^2 - t*u - u^2,
    y*u - z*u - w^2 + 2*w*t + w*u - t^2 - t*u - u^2
]) >;


// ---- N = 223,  [ <223, 1> ],  special points = 7 ----
models[223] := rec< ModelRec | N := 223, genus := 6, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 3*z*t - 2*z*u + w^2 - 5*w*t + 5*w*u - 6*t^2 + 12*t*u - 13*u^2,
    x*w - y*z + 2*z*t + 2*z*u - 2*w*t - w*u - 2*t^2 - 2*u^2,
    x*t - y*w + 2*w^2 - w*t - w*u - 3*t^2 + 2*t*u,
    x*u - z*w + w^2 + w*t - 2*w*u - 3*t*u + 2*u^2,
    y*t - z*w - 2*z*t + 2*w^2 + 2*w*t - 5*w*u - 3*t*u + 10*u^2,
    y*u - z*t + w*t - 2*w*u + t^2 - t*u + u^2
]) >;


// ---- N = 265,  [ <5, 1>, <53, 1> ],  special points = 9 ----
models[265] := rec< ModelRec | N := 265, genus := 6, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 5*y*u - 2*z*t - 2*z*u - 2*w*u + t^2 + t*u - 4*u^2,
    x*w - y*z + 3*y*u + 4*z*u - w^2 - w*t - 2*w*u - 2*t*u - 7*u^2,
    x*t + 6*y*u - z^2 - z*t + 9*z*u - 3*w^2 - 2*w*t + 5*w*u + t^2 - 8*t*u - 20*u^2,
    x*u + y*u - z*w + 2*z*u + w*u - 3*t*u - 5*u^2,
    y*w - y*u - z^2 + z*t + 2*z*u - w*t - t*u,
    y*t + 4*y*u - z*w - z*t + 7*z*u - 3*w^2 - w*t + 7*w*u + t^2 - 8*t*u - 16*u^2
]) >;


// ---- N = 269,  [ <269, 1> ],  special points = 6 ----
models[269] := rec< ModelRec | N := 269, genus := 6, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 3*y*u + z*w - 2*z*t - 2*z*u - 2*w^2 + 3*w*t - 3*w*u - t^2 + 2*t*u - u^2,
    x*w - y*z + y*u + z*w + z*t - 2*w^2 - 3*w*u - t^2 + u^2,
    x*t - z^2 + z*t + 3*z*u - w^2 + 2*w*u - 2*t^2 - 4*t*u - u^2,
    x*u - w^2 + w*t + w*u - t^2 - 3*u^2,
    y*w - y*u - z^2 + 2*z*t + 2*z*u - w^2 - w*t + 2*w*u - t^2 - 2*t*u,
    y*t - y*u - z*w + z*u + 3*w*u - t^2 - 2*u^2
]) >;


// ---- N = 271,  [ <271, 1> ],  special points = 6 ----
models[271] := rec< ModelRec | N := 271, genus := 6, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 2*y*t + 2*y*u - 3*z*t - z*u + w^2 - 5*w*u - t^2 + t*u + u^2,
    x*w - y*z + y*u + z*w - z*t + 3*z*u - w^2 - 4*w*u - 2*u^2,
    x*t + y*t - y*u - z^2 + z*t + 2*z*u - w*t - 2*t^2 - 3*t*u,
    x*u + y*t - y*u - z*w + z*u + w*t - w*u - t^2 - 3*t*u,
    y*w - y*u - z^2 + 2*z*t + z*u - w^2 - w*t + 2*w*u - 2*t*u,
    3*y*t - y*u - 3*z*w + 2*z*t + z*u + w^2 - 3*t^2 - 5*t*u + u^2
]) >;


// ---- N = 274,  [ <2, 1>, <137, 1> ],  special points = 11 ----
models[274] := rec< ModelRec | N := 274, genus := 6, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 3*y*u - 2*z*t - 5*z*u - 2*w^2 + 2*w*t - 3*w*u + t^2 + 3*t*u + 3*u^2,
    x*w - y*z + 3*y*u + z*w + z*t - z*u - w^2 - 2*w*t - 5*w*u - t*u + u^2,
    x*t - 2*y*u - z^2 + 3*z*t - 2*z*u - 3*w^2 + 4*w*t - 2*w*u - 4*t^2 - 2*t*u + 10*u^2,
    x*u - z*u - w^2 + w*t - w*u - t*u,
    y*w - 2*y*u - z^2 + 3*z*t - 2*w^2 + 2*w*t - w*u - 2*t^2 - 3*t*u + 7*u^2,
    y*t - 3*y*u - z*w + 2*w*t + w*u - t^2 + 2*t*u + u^2
]) >;


// ---- N = 291,  [ <3, 1>, <97, 1> ],  special points = 11 ----
models[291] := rec< ModelRec | N := 291, genus := 6, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + y*t + y*u - z*w + z*t - z*u + w^2 - w*t + w*u - t^2 - 4*t*u,
    x*w - y*z + 3*y*t - 3*z*w + 3*z*t + 2*z*u - 2*w^2 + w*t + 7*w*u - 6*t^2 - 9*t*u - 2*u^2,
    x*t - z^2 + z*t + 3*z*u - 2*w*t - t^2 - t*u - 2*u^2,
    x*u + 2*y*t - y*u - 3*z*w + 3*z*t + z*u - w^2 + w*t + 7*w*u - 4*t^2 - 9*t*u - 2*u^2,
    y*w + 3*y*t - y*u - z^2 - 3*z*w + 3*z*t + 4*z*u - 2*w^2 - w*t + 7*w*u - 4*t^2 - 7*t*u - 3*u^2,
    4*y*t - y*u - 4*z*w + 2*z*t + z*u - w^2 + 2*w*t + 9*w*u - 7*t^2 - 9*t*u - u^2
]) >;


// ---- N = 301,  [ <7, 1>, <43, 1> ],  special points = 9 ----
models[301] := rec< ModelRec | N := 301, genus := 6, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 11*y*u - 9*z*u - 9*w^2 + 6*w*t + 15*w*u - 2*t^2 - 10*u^2,
    x*w - y*z + 3*y*u + 2*z*t - z*u - 4*w^2 + 6*w*u - 2*t^2 - 3*u^2,
    x*t - z^2 + 3*z*t + z*u - 2*w^2 + 4*w*u - 4*t^2 - t*u,
    x*u - z*w + z*t - w^2 + w*t + 3*w*u - t^2 - 2*t*u - u^2,
    y*w - 2*y*u - z^2 + 3*z*t + 3*z*u - w^2 - 2*w*t - 2*t^2 + 2*u^2,
    y*t - 2*y*u - z*w + 2*z*u + 2*w^2 - w*t - 2*w*u - t*u + 2*u^2
]) >;


// ---- N = 314,  [ <2, 1>, <157, 1> ],  special points = 10 ----
models[314] := rec< ModelRec | N := 314, genus := 6, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + 2*y*t + 3*y*u - 2*z*w - 2*z*t + 3*w*t + w*u - t^2 - 4*t*u - 3*u^2,
    x*w - y*z + 4*y*t - y*u - 4*z*w + 4*z*u + w^2 + 3*w*t - 2*t^2 - 8*t*u,
    x*t + 2*y*t - z^2 - 2*z*w + 2*z*u + w^2 + w*t - t^2 - 5*t*u - u^2,
    x*u + 3*y*t - y*u - 4*z*w - z*t + 2*z*u + w^2 + 4*w*t + w*u - 2*t^2 - 6*t*u - u^2,
    y*w + 3*y*t - y*u - z^2 - 3*z*w + 3*z*u + w^2 + w*t - w*u - 6*t*u,
    5*y*t - 2*y*u - 5*z*w - z*t + 3*z*u + 3*w^2 + 4*w*t - 3*t^2 - 8*t*u + u^2
]) >;


// ---- N = 327,  [ <3, 1>, <109, 1> ],  special points = 10 ----
models[327] := rec< ModelRec | N := 327, genus := 6, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + y*t - 2*y*u - z*w + 2*z*t + z*u + w^2 - w*t + 2*w*u - 2*t^2 - 3*t*u - u^2,
    x*w - y*z + y*t - z*w + z*t + 4*z*u - w*u - 2*t^2 - 3*t*u - 4*u^2,
    x*t + y*t + 7*y*u - z^2 - z*w - 5*z*t + 2*z*u - 7*w*u + t^2 + t*u - u^2,
    x*u + 2*y*t - y*u - 3*z*w + z*t + 4*z*u + w*t + w*u - 2*t^2 - 6*t*u - 4*u^2,
    y*w + 2*y*t + 5*y*u - z^2 - 2*z*w - 4*z*t + 4*z*u - w^2 + w*t - 5*w*u + t^2 - t*u - 3*u^2,
    3*y*t - y*u - 3*z*w + z*t + 5*z*u + w*t + w*u - 3*t^2 - 6*t*u - 5*u^2
]) >;


// ---- N = 359,  [ <359, 1> ],  special points = 7 ----
models[359] := rec< ModelRec | N := 359, genus := 6, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + y*u + z*w - 4*z*t + w^2 - w*t - 5*w*u + 4*t^2 + 3*t*u + 5*u^2,
    x*w - y*z - y*u + z*w + 3*z*u - w^2 - 2*w*t + 2*t^2 + u^2,
    x*t - y*u - z^2 + z*w + z*u - w*t - w*u + 2*u^2,
    x*u - y*u + z*u - w*t + t^2,
    y*w - y*u - z^2 + 2*z*t + z*u - w^2 + w*u - t^2 - t*u,
    y*t + y*u - z*w + z*t + w*u - 2*t^2 - 2*t*u - 3*u^2
]) >;


// ---- N = 398,  [ <2, 1>, <199, 1> ],  special points = 5 ----
models[398] := rec< ModelRec | N := 398, genus := 6, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + z*u + 2*w^2 - 4*w*t - w*u + 2*t*u,
    x*w - y*z + z*t + z*u - w*t - w*u,
    x*t + y*u - z^2 + z*t + z*u - w^2 + w*t - t^2 - t*u - u^2,
    x*u + y*u - z*w + 2*w*t - 2*t*u - u^2,
    y*w + y*u - z^2 + z*t - 2*w^2 + 2*w*t - t*u - u^2,
    y*t + 2*y*u - z*w - z*t - w^2 + 3*w*t + w*u - 3*t*u - u^2
]) >;


// ---- N = 447,  [ <3, 1>, <149, 1> ],  special points = 4 ----
models[447] := rec< ModelRec | N := 447, genus := 6, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + y*t - z*t - 2*z*u + t*u + u^2,
    x*w - y*z + y*w + y*t + 2*y*u - z^2 - z*w + 2*z*t + 3*z*u - 2*w^2 - 2*w*t + 2*w*u - t^2 - t*u - 6*u^2,
    x*t + y*w + y*t + 2*y*u - 2*z^2 + 3*z*t + 2*z*u - 2*w^2 - 3*w*t + 3*w*u - 3*t^2 - 2*t*u - 6*u^2,
    x*u + y*w + y*t + 2*y*u - z^2 - z*w + 2*z*t + 2*z*u - 2*w^2 - 2*w*t + 3*w*u - 2*t^2 - t*u - 7*u^2,
    2*y*w + y*t + y*u - 2*z^2 - z*w + 3*z*t + 3*z*u - 2*w^2 - 2*w*t + 4*w*u - 2*t^2 - 2*t*u - 7*u^2,
    2*y*u + z*t - w^2 - w*t + w*u - t^2 - 2*u^2
]) >;


// ---- N = 451,  [ <11, 1>, <41, 1> ],  special points = 5 ----
models[451] := rec< ModelRec | N := 451, genus := 6, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 2*y*u + z*w - 2*z*t - 3*z*u + t^2 + 2*t*u + u^2,
    x*w - y*z + 3*y*u + z*w - z*t + w^2 - 2*w*u - t*u - 2*u^2,
    x*t + 7*y*u - z^2 + z*t - z*u - 2*w*t - 6*w*u - 5*t^2 - 4*t*u - 5*u^2,
    x*u - z*u - w*t - w*u,
    y*w + 5*y*u - z^2 + z*t - w*t - 5*w*u - 3*t^2 - 3*t*u - 4*u^2,
    y*t - 3*y*u - z*w + 2*z*u + 2*w*u + t^2 + u^2
]) >;


// ---- N = 470,  [ <2, 1>, <5, 1>, <47, 1> ],  special points = 9 ----
models[470] := rec< ModelRec | N := 470, genus := 6, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 3*y*t - 3*z*t + z*u - w^2 - 2*w*t + w*u + 2*t^2 + t*u - 5*u^2,
    x*w - y*z + 2*y*t + z*w + z*t + z*u - w*t - 2*w*u - 2*t^2 - 2*t*u - 2*u^2,
    x*t + y*t - z*t + z*u - w^2 - w*t + w*u - t*u - 2*u^2,
    x*u - z*t - w*t - w*u + 2*t^2 - u^2,
    y*w - z^2 + 4*z*t + 2*z*u + w^2 - 4*t^2 - 4*t*u - 2*u^2,
    y*u - z*u - w*t + t*u + u^2
]) >;


// ---- N = 506,  [ <2, 1>, <11, 1>, <23, 1> ],  special points = 7 ----
models[506] := rec< ModelRec | N := 506, genus := 6, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + y*w + y*u - z^2 + w^2 - 2*w*u,
    x*w + x*u - y*z + y*w - 2*y*u - z^2 - z*w + 2*z*t + 2*z*u + w^2 - w*t - 3*w*u - t*u + 2*u^2,
    x*t + x*u + y*w + 2*y*u - 2*z^2 - z*w + 2*z*t + 2*z*u - 2*w^2 + w*t - w*u - t^2 - 3*t*u - 2*u^2,
    3*x*u + y*w + 4*y*u - z^2 - 3*z*w - 3*z*u - 4*w^2 + 7*w*t + 3*w*u - 2*t^2 - 3*t*u - 4*u^2,
    2*y*w + 2*y*u - 2*z^2 + z*t + z*u - 3*w^2 + w*t - 2*w*u - 2*t*u - 2*u^2,
    y*t + 4*y*u - z*w - z*t - z*u - 3*w^2 + 3*w*t + 3*w*u - t^2 - 2*t*u - 4*u^2
]) >;


// ---- N = 561,  [ <3, 1>, <11, 1>, <17, 1> ],  special points = 5 ----
models[561] := rec< ModelRec | N := 561, genus := 6, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 8*y*t + 9*y*u - 7*z*w + 5*z*t + 3*w^2 - 3*w*t - 27*w*u - 13*t^2 + 18*t*u - 8*u^2,
    x*w - y*z + 13*y*t + 16*y*u - 13*z*w + 10*z*t + 5*z*u + 2*w^2 - 4*w*t - 43*w*u - 20*t^2 + 25*t*u - 20*u^2,
    x*t + 13*y*t + 12*y*u - z^2 - 12*z*w + 10*z*t + 3*z*u + 3*w^2 - 4*w*t - 39*w*u - 19*t^2 + 22*t*u - 14*u^2,
    x*u + 11*y*t + 11*y*u - 11*z*w + 8*z*t + 3*z*u + 2*w^2 - 3*w*t - 34*w*u - 16*t^2 + 19*t*u - 14*u^2,
    y*w + 2*y*t - z^2 - 2*z*w + 2*z*t + z*u - 3*w*u - t^2 - t*u,
    14*y*t + 15*y*u - 14*z*w + 11*z*t + 3*z*u + 3*w^2 - 4*w*t - 44*w*u - 21*t^2 + 26*t*u - 18*u^2
]) >;


// ---- N = 590,  [ <2, 1>, <5, 1>, <59, 1> ],  special points = 6 ----
models[590] := rec< ModelRec | N := 590, genus := 6, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + y*t + 2*y*u - z*w + 2*z*u - w^2 - w*t + 2*w*u - t^2 + t*u - 2*u^2,
    x*w - y*z + y*t - z*w + 2*z*u + w^2 - w*t - 2*w*u - 2*t*u,
    x*t - y*u - z^2 + w^2 - w*t - 2*w*u + 2*u^2,
    x*u + y*t - y*u - 2*z*w + z*u + 2*w^2 - w*t - 3*w*u - 2*t*u + 2*u^2,
    y*w - 2*y*u - z^2 - z*u + 2*w^2 - 4*w*u + t^2 - t*u + 4*u^2,
    2*y*t - y*u - 2*z*w + z*t + 2*z*u - 3*w*t - t^2 - t*u
]) >;


// ---- N = 598,  [ <2, 1>, <13, 1>, <23, 1> ],  special points = 4 ----
models[598] := rec< ModelRec | N := 598, genus := 6, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + z*w - z*u - 2*w^2 + w*t - t^2 + 2*t*u - 2*u^2,
    x*w - y*z + z*w + z*t - 2*z*u - 2*w^2 + w*u - t^2 + 2*t*u - 2*u^2,
    x*t - 4*y*u - z^2 + 3*z*t - 2*z*u - 3*w^2 + 2*w*t + 2*w*u - 3*t^2 + 5*t*u - 2*u^2,
    x*u - y*u + z*t - 2*z*u - 2*w^2 + w*t + w*u - t^2 + 2*t*u - 2*u^2,
    y*w - 2*y*u - z^2 + 2*z*t - w^2 - t^2 + 2*t*u,
    y*t - 2*y*u - z*w + z*t - 2*z*u - w^2 + w*t + 2*w*u - t^2 + 2*t*u
]) >;


// ---- N = 609,  [ <3, 1>, <7, 1>, <29, 1> ],  special points = 4 ----
models[609] := rec< ModelRec | N := 609, genus := 6, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 - 3*y*u + z^2 - 2*z*w - 2*z*t + 3*z*u + 2*w^2 - w*t - 2*w*u + 5*t*u + 3*u^2,
    x*w - y*z - z*w - w^2 + w*t + 2*w*u - t*u - u^2,
    x*t - y*u - z*w - z*t + z*u + t*u + u^2,
    x*u + z*u - w*t + w*u + t*u - u^2,
    y*w + y*u - z^2 + z*t - 2*z*u - 2*w^2 + 2*w*t + 2*w*u - 4*t*u - 2*u^2,
    y*t + y*u - z*u - w^2 + 2*w*u - t*u - u^2
]) >;


// ---- N = 615,  [ <3, 1>, <5, 1>, <41, 1> ],  special points = 5 ----
models[615] := rec< ModelRec | N := 615, genus := 6, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 19*y*t - 27*y*u - 19*z*w + 22*z*t + 4*z*u + 5*w^2 - 13*w*t + 23*w*u - 6*t^2 + 18*u^2,
    x*w - y*z + 30*y*t - 46*y*u - 30*z*w + 38*z*t + 7*z*u + 8*w^2 - 21*w*t + 38*w*u - 11*t^2 - t*u + 29*u^2,
    x*t + 49*y*t - 75*y*u - z^2 - 49*z*w + 61*z*t + 10*z*u + 15*w^2 - 35*w*t + 62*w*u - 17*t^2 - 2*t*u + 47*u^2,
    x*u + 46*y*t - 71*y*u - 47*z*w + 58*z*t + 9*z*u + 14*w^2 - 33*w*t + 58*w*u - 16*t^2 - 2*t*u + 45*u^2,
    y*w + 37*y*t - 57*y*u - z^2 - 37*z*w + 46*z*t + 7*z*u + 11*w^2 - 27*w*t + 47*w*u - 12*t^2 - 2*t*u + 36*u^2,
    60*y*t - 91*y*u - 60*z*w + 74*z*t + 12*z*u + 17*w^2 - 43*w*t + 75*w*u - 20*t^2 - 2*t*u + 58*u^2
]) >;


// ---- N = 627,  [ <3, 1>, <11, 1>, <19, 1> ],  special points = 4 ----
models[627] := rec< ModelRec | N := 627, genus := 6, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + 2*y*t + 2*z*t + 12*z*u + 6*w*t + 2*w*u - 11*t^2 + 4*t*u - 13*u^2,
    x*w - y*z + 2*y*t + z^2 + 4*z*u - w^2 + 2*w*t + 2*w*u - 4*t^2 + 2*t*u - 5*u^2,
    x*t + y*t - z*w - z*t - z*u - w^2 + t^2 - t*u + u^2,
    x*u - z*t - z*u - w*t - w*u + 2*t^2 - 2*t*u + 2*u^2,
    y*w - y*t - z^2 + z*w + 4*z*t + 6*z*u + 2*w^2 + w*t + w*u - 7*t^2 + 3*t*u - 6*u^2,
    y*u - 2*z*u - w*t + w*u + t^2 + u^2
]) >;


// ---- N = 670,  [ <2, 1>, <5, 1>, <67, 1> ],  special points = 7 ----
models[670] := rec< ModelRec | N := 670, genus := 6, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 4*y*u + z*t - 2*z*u - 3*w^2 + w*t + 2*w*u - t^2 + t*u - 3*u^2,
    x*w - y*z + y*w + y*t - 2*y*u - z^2 - z*w + z*t + 2*z*u + 2*w^2 - 3*w*t,
    x*t + y*w + y*t - 5*y*u - 2*z^2 - z*w + z*t + 3*z*u + 6*w^2 - 6*w*t + t^2 - 2*t*u + 2*u^2,
    x*u + y*u - z*w + z*t - z*u - w^2 + w*t + w*u - t^2 + t*u - 2*u^2,
    2*y*w - 4*y*u - 2*z^2 + z*t + 2*z*u + 3*w^2 - 4*w*t - w*u + t^2 + 2*u^2,
    2*y*t - 5*y*u - 2*z*w - 2*z*t + 3*z*u + 7*w^2 - 4*w*t - 2*w*u + 2*t^2 - 4*t*u + 4*u^2
]) >;


// ---- N = 690,  [ <2, 1>, <3, 1>, <5, 1>, <23, 1> ],  special points = 9 ----
models[690] := rec< ModelRec | N := 690, genus := 6, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 4*y*t - 4*z*w + 2*z*t + 5*z*u - 2*w^2 - 7*w*t + 2*w*u - t*u - 2*u^2,
    x*w - y*z + 3*y*w + 5*y*t - 8*y*u - 3*z^2 - 5*z*w - z*t - 8*z*u + 10*w^2 + 4*w*t - 15*w*u - 4*t^2 - 7*t*u + 2*u^2,
    x*t + 4*y*w + 6*y*t - 11*y*u - 5*z^2 - 6*z*w - 3*z*t - 14*z*u + 14*w^2 + 7*w*t - 22*w*u - 5*t^2 - 9*t*u + 4*u^2,
    x*u + 4*y*t - 3*y*u - 5*z*w + 2*z*t + 2*z*u + 2*w^2 - 4*w*t - 4*w*u - 2*t^2 - 3*t*u - u^2,
    5*y*w + 3*y*t - 10*y*u - 5*z^2 - 3*z*w - 6*z*t - 19*z*u + 16*w^2 + 14*w*t - 23*w*u - 4*t^2 - 8*t*u + 6*u^2,
    5*y*t - 3*y*u - 5*z*w + 3*z*t + 4*z*u - 7*w*t - 2*w*u - 2*t^2 - 3*t*u - 2*u^2
]) >;


// ---- N = 858,  [ <2, 1>, <3, 1>, <11, 1>, <13, 1> ],  special points = 3 ----
models[858] := rec< ModelRec | N := 858, genus := 6, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + 6*y*t + 5*y*u - 6*z*w + 4*z*t - z*u - 9*w^2 + 6*w*t + 9*w*u + 3*t^2 - t*u,
    x*w - y*z + 8*y*t + 4*y*u - 8*z*w + 4*z*t - z*u - 8*w^2 + 10*w*t + 4*w*u + 2*t^2 + t*u,
    x*t + 5*y*t + 3*y*u - z^2 - 5*z*w + 4*z*t - z*u - 6*w^2 + 6*w*t + 5*w*u + 2*t^2 - t*u - u^2,
    x*u + 42*y*t + 29*y*u - 43*z*w + 25*z*t - 5*z*u - 54*w^2 + 48*w*t + 40*w*u + 14*t^2 + u^2,
    y*w + 2*y*t + y*u - z^2 - 2*z*w + 2*z*t - z*u - 3*w^2 + 3*w*t + 2*w*u + 2*t^2 - t*u - u^2,
    44*y*t + 31*y*u - 44*z*w + 26*z*t - 5*z*u - 57*w^2 + 49*w*t + 43*w*u + 14*t^2 + u^2
]) >;


// ==== special-points table (genus 6) ====
//   N : special points
//   163 : 11
//   197 : 8
//   211 : 8
//   223 : 7
//   265 : 9
//   269 : 6
//   271 : 6
//   274 : 11
//   291 : 11
//   301 : 9
//   314 : 10
//   327 : 10
//   359 : 7
//   398 : 5
//   447 : 4
//   451 : 5
//   470 : 9
//   506 : 7
//   561 : 5
//   590 : 6
//   598 : 4
//   609 : 4
//   615 : 5
//   627 : 4
//   670 : 7
//   690 : 9
//   858 : 3

