// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = 4.
// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical
// saturated-HNF star basis. Cusp forms not stored.
// All curves of this genus live in the single shared projective space P below.
//   models[N]`curve          : the curve X_0(N)^* in P
//   models[N]`special_points : number of special (CM + cusp) rational points

Q := Rationals();
P<x, y, z, w> := ProjectiveSpace(Q, 3);
ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, 
curve >;
models := AssociativeArray();


// ---- N = 137,  [ <137, 1> ],  special points = 8 ----
models[137] := rec< ModelRec | N := 137, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*w - y*z + z^2 - z*w - w^2,
    x^2*z - x*y^2 - x*z^2 + 3*y^2*z + 2*y^2*w - 6*y*z^2 - y*z*w - 3*y*w^2 + 
3*z^3 + 2*z^2*w - z*w^2 + 2*w^3,
    x^2*w - x*y*z + x*z^2 - y*z^2 - y*z*w + z^3 - 2*z*w^2 - w^3,
    x*y*w - y^2*z + y*z^2 - y*z*w - y*w^2,
    x*z*w - y*z^2 + z^3 - z^2*w - z*w^2,
    x*w^2 - y*z*w + z^2*w - z*w^2 - w^3
]) >;


// ---- N = 173,  [ <173, 1> ],  special points = 6 ----
models[173] := rec< ModelRec | N := 173, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z + 2*x*w - y^2 + y*z + 3*y*w - 6*z*w - 3*w^2,
    x^2*z - x*y^2 + 3*x*y*w - 3*x*w^2 + y^3 - y^2*z - 5*y^2*w + 2*y*z^2 + 
4*y*z*w + 9*y*w^2 - 8*z^2*w - 2*z*w^2 - 6*w^3,
    x^2*w - x*y*w + 6*x*w^2 - 2*y^2*w - y*z^2 + 4*y*z*w + 6*y*w^2 + 4*z^2*w - 
17*z*w^2 - 6*w^3,
    x*y*z + 2*x*y*w - y^3 + y^2*z + 3*y^2*w - 6*y*z*w - 3*y*w^2,
    x*z^2 - 4*x*w^2 - y^2*z + 2*y^2*w + y*z^2 + y*z*w - 6*y*w^2 - 6*z^2*w + 
9*z*w^2 + 6*w^3,
    x*z*w + 2*x*w^2 - y^2*w + y*z*w + 3*y*w^2 - 6*z*w^2 - 3*w^3
]) >;


// ---- N = 199,  [ <199, 1> ],  special points = 8 ----
models[199] := rec< ModelRec | N := 199, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z + 2*x*w - y^2 - 2*y*z + 3*y*w - 4*w^2,
    x^2*z - x*y^2 + 3*x*y*w - 6*x*w^2 - 2*y^2*z + 2*y^2*w - 2*y*z^2 + 10*y*z*w -
8*y*w^2 - 6*z*w^2 + 10*w^3,
    x^2*w + 2*x*y*w + x*w^2 - y^3 - y^2*z + 2*y^2*w + y*z^2 - 5*y*z*w + 3*z*w^2 
- 5*w^3,
    x*y*z + 2*x*y*w - y^3 - 2*y^2*z + 3*y^2*w - 4*y*w^2,
    x*z^2 - 4*x*w^2 - y^2*z + 2*y^2*w - 2*y*z^2 + 7*y*z*w - 6*y*w^2 - 4*z*w^2 + 
8*w^3,
    x*z*w + 2*x*w^2 - y^2*w - 2*y*z*w + 3*y*w^2 - 4*w^3
]) >;


// ---- N = 201,  [ <3, 1>, <67, 1> ],  special points = 11 ----
models[201] := rec< ModelRec | N := 201, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + y*w,
    x^2*z - x*y^2 + x*y*w,
    x^2*w - 3*x*w^2 - y^3 + y*z^2 + 2*y*z*w + 6*y*w^2 - 2*z^2*w - 3*z*w^2 - 
3*w^3,
    x*y*z - y^3 + y^2*w,
    x*z^2 - y^2*z + y*z*w,
    x*z*w - y^2*w + y*w^2
]) >;


// ---- N = 202,  [ <2, 1>, <101, 1> ],  special points = 11 ----
models[202] := rec< ModelRec | N := 202, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - x*w - y^2 + y*w - z^2 - z*w + 2*w^2,
    x^2*z - x*y^2 + x*y*w - 4*x*w^2 - 2*y^2*z - 2*y^2*w + 4*y*w^2 - 8*z^2*w + 
7*z*w^2 + 4*w^3,
    x^2*w - 4*x*w^2 - y^2*z - y*z*w + 2*y*w^2 + z^3 - 5*z^2*w + 7*z*w^2,
    x*y*z - x*y*w - y^3 + y^2*w - y*z^2 - y*z*w + 2*y*w^2,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z*w + y*w^2 - z^3 - 2*z^2*w + z*w^2 + 
2*w^3,
    x*z*w - x*w^2 - y^2*w + y*w^2 - z^2*w - z*w^2 + 2*w^3
]) >;


// ---- N = 214,  [ <2, 1>, <107, 1> ],  special points = 9 ----
models[214] := rec< ModelRec | N := 214, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*w - y*z + z^2 - w^2,
    x^2*z - x*y^2 - x*z^2 + 2*y^2*z - y*z^2 - 2*y*z*w + z^3 + w^3,
    x^2*w - x*y*z + x*z^2 - y*z*w + z^2*w - w^3,
    x*y*w - y^2*z + y*z^2 - y*w^2,
    x*z*w - y*z^2 + z^3 - z*w^2,
    x*w^2 - y*z*w + z^2*w - w^3
]) >;


// ---- N = 219,  [ <3, 1>, <73, 1> ],  special points = 11 ----
models[219] := rec< ModelRec | N := 219, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*w - y*z + y*w + 2*z*w - 2*w^2,
    x^2*z - x*y^2 - x*y*z - x*z^2 + y^3 + y^2*z - 3*y^2*w + y*z^2 + 3*y*w^2 - 
3*z*w^2,
    x^2*w - x*y*z + y^2*z - y^2*w + 2*y*z^2 - 6*y*z*w + 4*y*w^2 - 4*z^2*w + 
8*z*w^2 - 4*w^3,
    x*y*w - y^2*z + y^2*w + 2*y*z*w - 2*y*w^2,
    x*z*w - y*z^2 + y*z*w + 2*z^2*w - 2*z*w^2,
    x*w^2 - y*z*w + y*w^2 + 2*z*w^2 - 2*w^3
]) >;


// ---- N = 247,  [ <13, 1>, <19, 1> ],  special points = 5 ----
models[247] := rec< ModelRec | N := 247, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    2*x*z + x*w - 2*y^2 - y*z + 2*y*w - 2*z*w + w^2,
    x^2*z - x*y^2 + x*y*w + x*z^2 + 2*x*z*w + 2*x*w^2 - y^2*z - 2*y^2*w - y*z^2 
- z*w^2 + 2*w^3,
    x^2*w + x*y*z + x*y*w + x*z*w - 2*y^3 - y^2*z + y*z^2 - 3*y*z*w + 7*y*w^2 - 
2*z^2*w - 3*z*w^2 - w^3,
    2*x*y*z + x*y*w - 2*y^3 - y^2*z + 2*y^2*w - 2*y*z*w + y*w^2,
    2*x*z^2 + x*z*w - 2*y^2*z - y*z^2 + 2*y*z*w - 2*z^2*w + z*w^2,
    2*x*z*w + x*w^2 - 2*y^2*w - y*z*w + 2*y*w^2 - 2*z*w^2 + w^3
]) >;


// ---- N = 251,  [ <251, 1> ],  special points = 6 ----
models[251] := rec< ModelRec | N := 251, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - 2*x*w - y^2 + y*w + w^2,
    x^2*z - x*y^2 + x*y*w - 9*x*w^2 - 2*y^2*z - 2*y^2*w + 2*y*z^2 + 2*y*w^2 + 
2*z^2*w - 2*z*w^2 + 8*w^3,
    x^2*w - 5*x*w^2 - y^2*z - y^2*w + y*z^2 + y*w^2 + z^2*w - z*w^2 + 4*w^3,
    x*y*z - 2*x*y*w - y^3 + y^2*w + y*w^2,
    x*z^2 - 4*x*w^2 - y^2*z - 2*y^2*w + y*z*w + 2*y*w^2 + z*w^2 + 2*w^3,
    x*z*w - 2*x*w^2 - y^2*w + y*w^2 + w^3
]) >;


// ---- N = 254,  [ <2, 1>, <127, 1> ],  special points = 8 ----
models[254] := rec< ModelRec | N := 254, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*w - y*z,
    x^2*z - x*y^2 - x*z^2 + 2*y^2*z - 2*y*z^2 - y*w^2 + z^2*w + 2*z*w^2 - w^3,
    x^2*w - x*y*z,
    x*y*w - y^2*z,
    x*z*w - y*z^2,
    x*w^2 - y*z*w
]) >;


// ---- N = 259,  [ <7, 1>, <37, 1> ],  special points = 7 ----
models[259] := rec< ModelRec | N := 259, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z + 3*x*w - y^2 + y*z - 2*z^2 - z*w - 2*w^2,
    x^2*z - x*y^2 - 8*x*w^2 + y^3 - y^2*w + y*z^2 - 7*y*z*w + 14*y*w^2 - 4*z^3 +
11*z^2*w + z*w^2 - 8*w^3,
    x^2*w - x*y*w - 3*x*w^2 - y^2*z + 2*y^2*w + y*z^2 + y*z*w - 4*y*w^2 - z^2*w 
+ 6*w^3,
    x*y*z + 3*x*y*w - y^3 + y^2*z - 2*y*z^2 - y*z*w - 2*y*w^2,
    x*z^2 - 9*x*w^2 - y^2*z + 3*y^2*w + y*z^2 - 3*y*z*w - 2*z^3 + 5*z^2*w + 
z*w^2 + 6*w^3,
    x*z*w + 3*x*w^2 - y^2*w + y*z*w - 2*z^2*w - z*w^2 - 2*w^3
]) >;


// ---- N = 262,  [ <2, 1>, <131, 1> ],  special points = 7 ----
models[262] := rec< ModelRec | N := 262, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - x*w - y^2 + y*w - z^2 + w^2,
    x^2*z - x*y^2 + x*y*w - 4*x*w^2 - 2*y^2*z - y^2*w + y*w^2 - z^3 + 6*w^3,
    x^2*w - 4*x*w^2 - y^2*z - y*z*w + z^2*w - z*w^2 + 5*w^3,
    x*y*z - x*y*w - y^3 + y^2*w - y*z^2 + y*w^2,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z*w + y*w^2 - z^3 - z^2*w + z*w^2 + w^3,
    x*z*w - x*w^2 - y^2*w + y*w^2 - z^2*w + w^3
]) >;


// ---- N = 267,  [ <3, 1>, <89, 1> ],  special points = 5 ----
models[267] := rec< ModelRec | N := 267, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - x*w - y^2 + y*z + y*w - z^2 - z*w,
    x^2*z - x*y^2 + x*y*w - 3*x*w^2 - 2*y^2*w + 2*y*z*w + 2*y*w^2 - 3*z^2*w,
    x^2*w - x*y*w - x*w^2 - y^3 + 2*y^2*z + y^2*w - 2*y*z^2 - 2*y*z*w + z^3 + 
2*z*w^2,
    x*y*z - x*y*w - y^3 + y^2*z + y^2*w - y*z^2 - y*z*w,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z^2 + 2*y*z*w + y*w^2 - z^3 - 2*z^2*w - 
z*w^2,
    x*z*w - x*w^2 - y^2*w + y*z*w + y*w^2 - z^2*w - z*w^2
]) >;


// ---- N = 273,  [ <3, 1>, <7, 1>, <13, 1> ],  special points = 11 ----
models[273] := rec< ModelRec | N := 273, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 11, curve := Curve(P, [
    4*x*z - 3*x*w - 4*y^2 + 3*y*z + 4*y*w - 3*z^2 - z*w + 5*w^2,
    x^2*z - x*y^2 + x*y*w + x*z*w - x*w^2 - 2*y^2*w + 2*y*w^2 + z*w^2 + w^3,
    x^2*w + 3*x*y*z - 3*x*y*w + x*z^2 + 3*x*z*w - 4*x*w^2 - 4*y^3 + 3*y^2*z - 
3*y*z^2 + 9*y*w^2 - z^2*w + z*w^2 + 3*w^3,
    4*x*y*z - 3*x*y*w - 4*y^3 + 3*y^2*z + 4*y^2*w - 3*y*z^2 - y*z*w + 5*y*w^2,
    4*x*z^2 + x*z*w - 3*x*w^2 - 4*y^2*z - 4*y^2*w + 3*y*z^2 + 7*y*z*w + 4*y*w^2 
- 3*z^3 - 4*z^2*w + 4*z*w^2 + 5*w^3,
    4*x*z*w - 3*x*w^2 - 4*y^2*w + 3*y*z*w + 4*y*w^2 - 3*z^2*w - z*w^2 + 5*w^3
]) >;


// ---- N = 305,  [ <5, 1>, <61, 1> ],  special points = 7 ----
models[305] := rec< ModelRec | N := 305, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*w - y*z,
    x^2*z - x*y^2 - x*z^2 + 2*y^2*z + 2*y^2*w - 3*y*z^2 - 2*y*z*w - y*w^2 + z^3 
+ 2*z^2*w - w^3,
    x^2*w - x*y*z,
    x*y*w - y^2*z,
    x*z*w - y*z^2,
    x*w^2 - y*z*w
]) >;


// ---- N = 311,  [ <311, 1> ],  special points = 4 ----
models[311] := rec< ModelRec | N := 311, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - x*w - y^2 + y*z + 2*y*w - z^2 - 2*z*w,
    x^2*z - x*y^2 + 2*x*y*w - 3*x*w^2 - y^2*z - 3*y^2*w + y*z^2 + 5*y*z*w + 
5*y*w^2 - z^3 - 4*z^2*w - 6*z*w^2,
    x^2*w - x*y*w - y^3 + y^2*z + 2*y^2*w - y*z^2 - 2*y*z*w - y*w^2 + z^2*w,
    x*y*z - x*y*w - y^3 + y^2*z + 2*y^2*w - y*z^2 - 2*y*z*w,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z^2 + 3*y*z*w + 2*y*w^2 - z^3 - 3*z^2*w - 
2*z*w^2,
    x*z*w - x*w^2 - y^2*w + y*z*w + 2*y*w^2 - z^2*w - 2*z*w^2
]) >;


// ---- N = 319,  [ <11, 1>, <29, 1> ],  special points = 5 ----
models[319] := rec< ModelRec | N := 319, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z + x*w - y^2 - y*z + 2*y*w - z^2 - w^2,
    x^2*z - x*y^2 + 2*x*y*w - y^2*z + y^2*w - y*z^2 - y*z*w - y*w^2 + z^3 - 
z^2*w + 2*z*w^2,
    x^2*w + x*y*w - 2*x*w^2 - y^3 - y^2*z + 2*y^2*w - y*z^2 + 4*y*z*w - 2*y*w^2 
- 2*z^3 + 2*z^2*w - 3*z*w^2 + w^3,
    x*y*z + x*y*w - y^3 - y^2*z + 2*y^2*w - y*z^2 - y*w^2,
    x*z^2 - x*w^2 - y^2*z + y^2*w - y*z^2 + 3*y*z*w - 2*y*w^2 - z^3 + z^2*w - 
z*w^2 + w^3,
    x*z*w + x*w^2 - y^2*w - y*z*w + 2*y*w^2 - z^2*w - w^3
]) >;


// ---- N = 321,  [ <3, 1>, <107, 1> ],  special points = 6 ----
models[321] := rec< ModelRec | N := 321, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - 2*x*w - y^2 + y*w - z*w + w^2,
    x^2*z - x*y^2 + x*y*w - 7*x*w^2 - 2*y^2*z - 3*y^2*w + 2*y*z^2 + 3*y*w^2 - 
2*z^2*w - 3*z*w^2 + 5*w^3,
    x^2*w - 3*x*w^2 - y^2*z - y^2*w + y*z^2 + y*w^2 - z^2*w - z*w^2 + 2*w^3,
    x*y*z - 2*x*y*w - y^3 + y^2*w - y*z*w + y*w^2,
    x*z^2 - 4*x*w^2 - y^2*z - 2*y^2*w + y*z*w + 2*y*w^2 - z^2*w - z*w^2 + 2*w^3,
    x*z*w - 2*x*w^2 - y^2*w + y*w^2 - z*w^2 + w^3
]) >;


// ---- N = 322,  [ <2, 1>, <7, 1>, <23, 1> ],  special points = 8 ----
models[322] := rec< ModelRec | N := 322, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    3*x*z - 4*x*w - 3*y^2 + 4*y*z + 2*y*w - 3*z^2 + 3*z*w + 5*w^2,
    x^2*z - x*y^2 + 2*x*y*z - 2*x*y*w - x*w^2 - 2*y^3 + 3*y^2*z + y^2*w - 
2*y*z^2 + 4*y*z*w + 4*y*w^2 - z^3 + 2*z^2*w + 2*z*w^2 + w^3,
    x^2*w + 2*x*y*z - 4*x*y*w + x*z*w - 3*x*w^2 - 3*y^3 + 5*y^2*z + y^2*w - 
4*y*z^2 + 5*y*z*w + 6*y*w^2 + z*w^2 + 2*w^3,
    3*x*y*z - 4*x*y*w - 3*y^3 + 4*y^2*z + 2*y^2*w - 3*y*z^2 + 3*y*z*w + 5*y*w^2,
    3*x*z^2 + 2*x*z*w - 8*x*w^2 - 3*y^2*z - 6*y^2*w + 4*y*z^2 + 10*y*z*w + 
4*y*w^2 - 3*z^3 - 3*z^2*w + 11*z*w^2 + 10*w^3,
    3*x*z*w - 4*x*w^2 - 3*y^2*w + 4*y*z*w + 2*y*w^2 - 3*z^2*w + 3*z*w^2 + 5*w^3
]) >;


// ---- N = 334,  [ <2, 1>, <167, 1> ],  special points = 5 ----
models[334] := rec< ModelRec | N := 334, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - 2*x*w - y^2 + 2*y*z - z*w + w^2,
    x^2*z - x*y^2 - 3*x*w^2 - y^2*w + 2*y*z^2 + 2*y*z*w - 2*y*w^2 - z*w^2 + 
3*w^3,
    x^2*w - 2*x*y*w - x*w^2 - y^3 + 2*y^2*z + y*z^2 - y*z*w + w^3,
    x*y*z - 2*x*y*w - y^3 + 2*y^2*z - y*z*w + y*w^2,
    x*z^2 - 4*x*w^2 - y^2*z - 2*y^2*w + 2*y*z^2 + 4*y*z*w - z^2*w - z*w^2 + 
2*w^3,
    x*z*w - 2*x*w^2 - y^2*w + 2*y*z*w - z*w^2 + w^3
]) >;


// ---- N = 335,  [ <5, 1>, <67, 1> ],  special points = 4 ----
models[335] := rec< ModelRec | N := 335, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 4, curve := Curve(P, [
    4*x*z - 7*x*w - 4*y^2 + 7*y*z + 7*y*w - 3*z^2 + 3*z*w + w^2,
    x^2*z - x*y^2 + x*y*z + x*z^2 + 4*x*z*w - 12*x*w^2 - y^3 - 5*y^2*w + y*z^2 +
13*y*z*w + 9*y*w^2 - 2*z^2*w + 9*z*w^2 + 3*w^3,
    x^2*w + 3*x*y*z - 7*x*y*w + x*z^2 + 3*x*z*w - 9*x*w^2 - 4*y^3 + 6*y^2*z + 
2*y^2*w - 2*y*z^2 + 12*y*z*w + 8*y*w^2 - 2*z^2*w + 6*z*w^2 + 2*w^3,
    4*x*y*z - 7*x*y*w - 4*y^3 + 7*y^2*z + 7*y^2*w - 3*y*z^2 + 3*y*z*w + y*w^2,
    4*x*z^2 + x*z*w - 14*x*w^2 - 4*y^2*z - 8*y^2*w + 7*y*z^2 + 21*y*z*w + 
14*y*w^2 - 3*z^3 - 3*z^2*w + 7*z*w^2 + 2*w^3,
    4*x*z*w - 7*x*w^2 - 4*y^2*w + 7*y*z*w + 7*y*w^2 - 3*z^2*w + 3*z*w^2 + w^3
]) >;


// ---- N = 341,  [ <11, 1>, <31, 1> ],  special points = 6 ----
models[341] := rec< ModelRec | N := 341, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - 4*x*w - y^2 - y*w + 2*z^2 - 3*z*w + 3*w^2,
    x^2*z - x*y^2 - x*y*w - 29*x*w^2 - 2*y^2*z - 7*y^2*w + 4*y*z^2 - 6*y*z*w - 
7*y*w^2 + 4*z^3 + 12*z^2*w - 23*z*w^2 + 25*w^3,
    x^2*w - 13*x*w^2 - y^2*z - 3*y^2*w + y*z^2 - 2*y*z*w - 3*y*w^2 + 2*z^3 + 
4*z^2*w - 8*z*w^2 + 10*w^3,
    x*y*z - 4*x*y*w - y^3 - y^2*w + 2*y*z^2 - 3*y*z*w + 3*y*w^2,
    x*z^2 - 16*x*w^2 - y^2*z - 4*y^2*w - y*z*w - 4*y*w^2 + 2*z^3 + 5*z^2*w - 
9*z*w^2 + 12*w^3,
    x*z*w - 4*x*w^2 - y^2*w - y*w^2 + 2*z^2*w - 3*z*w^2 + 3*w^3
]) >;


// ---- N = 345,  [ <3, 1>, <5, 1>, <23, 1> ],  special points = 9 ----
models[345] := rec< ModelRec | N := 345, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*w - y*z + y*w - z^2 + z*w,
    x^2*z - x*y^2 - x*y*z + y^3 + y^2*w - 2*y*z*w - 3*y*w^2 + z^3 + 2*z^2*w,
    x^2*w - x*y*z - x*z^2 + y^2*z - y^2*w + 2*y*z^2 - 2*y*z*w + z^3 - z^2*w,
    x*y*w - y^2*z + y^2*w - y*z^2 + y*z*w,
    x*z*w - y*z^2 + y*z*w - z^3 + z^2*w,
    x*w^2 - y*z*w + y*w^2 - z^2*w + z*w^2
]) >;


// ---- N = 354,  [ <2, 1>, <3, 1>, <59, 1> ],  special points = 10 ----
models[354] := rec< ModelRec | N := 354, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - x*w - y^2 + y*z + y*w - z^2 + z*w + w^2,
    x^2*z - x*y^2 + x*y*w + x*w^2 - 2*y*z*w + z^2*w - w^3,
    x^2*w - x*y*w - y^3 + 2*y^2*z + y^2*w - 2*y*z^2 - 2*y*z*w + y*w^2 + z^3 - 
z*w^2 - w^3,
    x*y*z - x*y*w - y^3 + y^2*z + y^2*w - y*z^2 + y*z*w + y*w^2,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z^2 + 2*y*z*w + y*w^2 - z^3 + 2*z*w^2 + 
w^3,
    x*z*w - x*w^2 - y^2*w + y*z*w + y*w^2 - z^2*w + z*w^2 + w^3
]) >;


// ---- N = 355,  [ <5, 1>, <71, 1> ],  special points = 5 ----
models[355] := rec< ModelRec | N := 355, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z + x*w - y^2 - y*z + 2*z*w,
    x^2*z - x*y^2 + 2*y^2*w - y*z^2 - y*w^2 + z^2*w - 2*z*w^2,
    x^2*w + x*y*w - 2*x*w^2 - y^3 - y^2*z + y*z^2 + 4*y*z*w + y*w^2 - z^2*w - 
2*z*w^2,
    x*y*z + x*y*w - y^3 - y^2*z + 2*y*z*w,
    x*z^2 - x*w^2 - y^2*z + y^2*w - y*z^2 + y*z*w + 2*z^2*w - 2*z*w^2,
    x*z*w + x*w^2 - y^2*w - y*z*w + 2*z*w^2
]) >;


// ---- N = 366,  [ <2, 1>, <3, 1>, <61, 1> ],  special points = 10 ----
models[366] := rec< ModelRec | N := 366, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - x*w - y^2 + y*z + y*w - 2*z*w,
    x^2*z - x*y^2 + x*y*w - 3*x*w^2 - y^2*z - 2*y^2*w + y*z^2 + 5*y*z*w + 
2*y*w^2 - z^2*w - 5*z*w^2,
    x^2*w - x*y*w - x*w^2 - y^3 + y^2*w + y*z^2 + y*z*w - z^2*w - z*w^2,
    x*y*z - x*y*w - y^3 + y^2*z + y^2*w - 2*y*z*w,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z^2 + 2*y*z*w + y*w^2 - 2*z^2*w - 2*z*w^2,
    x*z*w - x*w^2 - y^2*w + y*z*w + y*w^2 - 2*z*w^2
]) >;


// ---- N = 370,  [ <2, 1>, <5, 1>, <37, 1> ],  special points = 9 ----
models[370] := rec< ModelRec | N := 370, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 9, curve := Curve(P, [
    3*x*z - 4*x*w - 3*y^2 + 8*y*z + 4*y*w - 3*z^2 - 3*z*w,
    x^2*z - x*y^2 + x*y*z + x*z^2 + x*z*w - 4*x*w^2 - y^3 + 2*y^2*z - 2*y^2*w + 
3*y*z^2 + 7*y*z*w + 4*y*w^2 - 2*z^3 - 4*z^2*w - 2*z*w^2,
    2*x^2*w + 2*x*y*z - 8*x*y*w + x*z*w + 2*x*w^2 - 6*y^3 + 18*y^2*z + 9*y^2*w -
8*y*z^2 - 14*y*z*w - 2*y*w^2 + 3*z^2*w + 3*z*w^2,
    6*x*y*z - 8*x*y*w - 3*x*z*w + 4*x*w^2 - 6*y^3 + 16*y^2*z + 11*y^2*w - 
6*y*z^2 - 14*y*z*w - 4*y*w^2 + 3*z^2*w + 3*z*w^2,
    6*x*z^2 + x*z*w - 12*x*w^2 - 6*y^2*z - 9*y^2*w + 16*y*z^2 + 32*y*z*w + 
12*y*w^2 - 6*z^3 - 15*z^2*w - 9*z*w^2,
    3*x*z*w - 4*x*w^2 - 3*y^2*w + 8*y*z*w + 4*y*w^2 - 3*z^2*w - 3*z*w^2
]) >;


// ---- N = 374,  [ <2, 1>, <11, 1>, <17, 1> ],  special points = 7 ----
models[374] := rec< ModelRec | N := 374, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    2*x*z + 5*x*w - 2*y^2 - 5*y*z + 2*y*w - 2*z^2 + z*w - w^2,
    x^2*z - x*y^2 + x*y*w + x*z^2 + x*z*w - 8*x*w^2 - 2*y^2*z + 2*y^2*w - 
5*y*z^2 + 12*y*z*w - 2*y*w^2 - 2*z^3 + 3*z^2*w - 2*z*w^2 + w^3,
    x^2*w + x*y*z + 5*x*y*w + x*z*w + x*w^2 - 2*y^3 - 5*y^2*z + 2*y^2*w - 
2*y*z^2 - y*z*w - y*w^2,
    2*x*y*z + 5*x*y*w - 2*y^3 - 5*y^2*z + 2*y^2*w - 2*y*z^2 + y*z*w - y*w^2,
    2*x*z^2 + x*z*w - 10*x*w^2 - 2*y^2*z + 4*y^2*w - 5*y*z^2 + 12*y*z*w - 
4*y*w^2 - 2*z^3 + 5*z^2*w - 3*z*w^2 + 2*w^3,
    2*x*z*w + 5*x*w^2 - 2*y^2*w - 5*y*z*w + 2*y*w^2 - 2*z^2*w + z*w^2 - w^3
]) >;


// ---- N = 385,  [ <5, 1>, <7, 1>, <11, 1> ],  special points = 6 ----
models[385] := rec< ModelRec | N := 385, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    6*x*z - x*w - 6*y^2 + y*z + 7*y*w - 2*z^2 + 3*z*w,
    x^2*z - x*y^2 + x*y*z + x*y*w + 3*x*z^2 + 5*x*z*w - x*w^2 - y^3 - 3*y^2*z - 
4*y^2*w + 5*y*z*w + 6*y*w^2 - z^3 + 3*z*w^2,
    x^2*w + 5*x*y*z - x*y*w + 2*x*z^2 + 6*x*z*w - 2*x*w^2 - 6*y^3 - 3*y*z^2 + 
5*y*z*w + 8*y*w^2 - z^2*w + 6*z*w^2,
    6*x*y*z - x*y*w - 6*y^3 + y^2*z + 7*y^2*w - 2*y*z^2 + 3*y*z*w,
    6*x*z^2 + 5*x*z*w - x*w^2 - 6*y^2*z - 6*y^2*w + y*z^2 + 8*y*z*w + 7*y*w^2 - 
2*z^3 + z^2*w + 3*z*w^2,
    6*x*z*w - x*w^2 - 6*y^2*w + y*z*w + 7*y*w^2 - 2*z^2*w + 3*z*w^2
]) >;


// ---- N = 395,  [ <5, 1>, <79, 1> ],  special points = 5 ----
models[395] := rec< ModelRec | N := 395, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + y*w - z*w,
    x^2*z - x*y^2 + x*y*w - y^2*w + y*w^2 - z*w^2,
    x^2*w + x*w^2 - y^3 + y^2*z + y*z^2 - 4*y*z*w + y*w^2 + z^2*w - w^3,
    x*y*z - y^3 + y^2*w - y*z*w,
    x*z^2 - y^2*z + y*z*w - z^2*w,
    x*z*w - y^2*w + y*w^2 - z*w^2
]) >;


// ---- N = 399,  [ <3, 1>, <7, 1>, <19, 1> ],  special points = 9 ----
models[399] := rec< ModelRec | N := 399, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 9, curve := Curve(P, [
    2*x*z - 5*x*w - 2*y^2 + 5*y*z + 6*y*w + 2*z^2 - 8*z*w - 3*w^2,
    x^2*z - x*y^2 + 3*x*y*w + x*z^2 + 2*x*z*w - 19*x*w^2 - 5*y^2*z - 6*y^2*w + 
5*y*z^2 + 30*y*z*w + 18*y*w^2 + z^2*w - 34*z*w^2 - 9*w^3,
    x^2*w + x*y*z - 5*x*y*w - x*w^2 - 2*y^3 + 3*y^2*z + 6*y^2*w + 4*y*z^2 - 
2*y*z*w - 3*y*w^2 - 2*z^2*w - 4*z*w^2,
    2*x*y*z - 5*x*y*w - 2*y^3 + 5*y^2*z + 6*y^2*w + 2*y*z^2 - 8*y*z*w - 3*y*w^2,
    2*x*z^2 + x*z*w - 15*x*w^2 - 2*y^2*z - 6*y^2*w + 5*y*z^2 + 21*y*z*w + 
18*y*w^2 + 2*z^3 - 2*z^2*w - 27*z*w^2 - 9*w^3,
    2*x*z*w - 5*x*w^2 - 2*y^2*w + 5*y*z*w + 6*y*w^2 + 2*z^2*w - 8*z*w^2 - 3*w^3
]) >;


// ---- N = 426,  [ <2, 1>, <3, 1>, <71, 1> ],  special points = 8 ----
models[426] := rec< ModelRec | N := 426, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    3*x*z + 2*x*w - 3*y^2 - 2*y*z + y*w + z^2 + 4*z*w,
    x^2*z - x*y^2 + x*y*z + x*y*w + 2*x*z^2 + 2*x*z*w - y^3 - 3*y^2*z + y^2*w - 
y*z^2 + 3*y*z*w + z^3 + 2*z^2*w - 2*z*w^2,
    x^2*w + 2*x*y*z + 2*x*y*w + 2*x*z^2 + 2*x*z*w - 3*y^3 - 3*y^2*z + 3*y*z*w + 
3*z^2*w + 3*z*w^2,
    3*x*y*z + 2*x*y*w - 3*y^3 - 2*y^2*z + y^2*w + y*z^2 + 4*y*z*w,
    3*x*z^2 + 2*x*z*w - 3*y^2*z - 2*y*z^2 + y*z*w + z^3 + 4*z^2*w,
    3*x*z*w + 2*x*w^2 - 3*y^2*w - 2*y*z*w + y*w^2 + z^2*w + 4*z*w^2
]) >;


// ---- N = 434,  [ <2, 1>, <7, 1>, <31, 1> ],  special points = 6 ----
models[434] := rec< ModelRec | N := 434, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - x*w - y^2 + y*z + 2*y*w,
    x^2*z - x*y^2 + 2*x*y*w - x*w^2 - 2*y^2*w + y*w^2 + z^2*w + z*w^2,
    x^2*w - x*y*w - x*w^2 - y^3 + y^2*z + y*w^2 + z^2*w + z*w^2,
    x*y*z - x*y*w - y^3 + y^2*z + 2*y^2*w,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z^2 + 3*y*z*w + 2*y*w^2,
    x*z*w - x*w^2 - y^2*w + y*z*w + 2*y*w^2
]) >;


// ---- N = 483,  [ <3, 1>, <7, 1>, <23, 1> ],  special points = 3 ----
models[483] := rec< ModelRec | N := 483, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - x*w - y^2 + y*w - z^2 + 2*z*w - 2*w^2,
    x^2*z - x*y^2 + x*y*w - 2*x*w^2 - 2*y^2*z + y^2*w + y*z^2 + 3*y*z*w - y*w^2 
- 3*z^3 + 7*z^2*w - 8*z*w^2 + 2*w^3,
    x^2*w - x*w^2 - y^2*z + y*z^2 + 2*y*z*w - 2*z^3 + 4*z^2*w - 4*z*w^2,
    x*y*z - x*y*w - y^3 + y^2*w - y*z^2 + 2*y*z*w - 2*y*w^2,
    x*z^2 - x*w^2 - y^2*z - y^2*w + y*z*w + y*w^2 - z^3 + z^2*w - 2*w^3,
    x*z*w - x*w^2 - y^2*w + y*w^2 - z^2*w + 2*z*w^2 - 2*w^3
]) >;


// ---- N = 546,  [ <2, 1>, <3, 1>, <7, 1>, <13, 1> ],  special points = 7 ----
models[546] := rec< ModelRec | N := 546, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 7, curve := Curve(P, [
    2*x*z - x*w - 2*y^2 + y*z + 4*y*w - 3*z^2 + 5*z*w - w^2,
    x^2*z - x*y^2 + 2*x*y*w - y^2*z + 2*y^2*w + 2*y*z*w - y*w^2 - z^3 + 2*z^2*w 
- z*w^2,
    x^2*w + x*y*z - x*y*w + x*z^2 + 2*x*z*w - 2*x*w^2 - 2*y^3 + y^2*z + 2*y^2*w 
- 4*y*z^2 + 8*y*z*w + 9*y*w^2 + z^3 - 10*z^2*w + 14*z*w^2 - 3*w^3,
    2*x*y*z - x*y*w - 2*y^3 + y^2*z + 4*y^2*w - 3*y*z^2 + 5*y*z*w - y*w^2,
    2*x*z^2 + x*z*w - x*w^2 - 2*y^2*z - 2*y^2*w + y*z^2 + 5*y*z*w + 4*y*w^2 - 
3*z^3 + 2*z^2*w + 4*z*w^2 - w^3,
    2*x*z*w - x*w^2 - 2*y^2*w + y*z*w + 4*y*w^2 - 3*z^2*w + 5*z*w^2 - w^3
]) >;


// ---- N = 570,  [ <2, 1>, <3, 1>, <5, 1>, <19, 1> ],  special points = 8 ----
models[570] := rec< ModelRec | N := 570, genus := 4, squarefree := true, 
hyperelliptic := false, special_points := 8, curve := Curve(P, [
    14*x*z - 3*x*w - 14*y^2 + 3*y*z - y*w - 2*z^2 + 13*z*w + 8*w^2,
    x^2*z - x*y^2 + 9*x*y*z - 2*x*y*w + 6*x*z^2 + 12*x*z*w - 2*x*w^2 - 9*y^3 - 
4*y^2*z - 13*y^2*w + 10*y*z*w + 4*y*w^2 - z^3 + 4*z^2*w + 15*z*w^2 + 7*w^3,
    x^2*w + 13*x*y*z - 3*x*y*w + 10*x*z^2 + 9*x*z*w - 2*x*w^2 - 14*y^3 - 6*y^2*z
- 12*y^2*w + 12*y*z*w + 6*y*w^2 - 2*z^3 + 8*z^2*w + 16*z*w^2 + 6*w^3,
    14*x*y*z - 3*x*y*w - 14*y^3 + 3*y^2*z - y^2*w - 2*y*z^2 + 13*y*z*w + 
8*y*w^2,
    14*x*z^2 + 11*x*z*w - 3*x*w^2 - 14*y^2*z - 14*y^2*w + 3*y*z^2 + 2*y*z*w - 
y*w^2 - 2*z^3 + 11*z^2*w + 21*z*w^2 + 8*w^3,
    14*x*z*w - 3*x*w^2 - 14*y^2*w + 3*y*z*w - y*w^2 - 2*z^2*w + 13*z*w^2 + 8*w^3
]) >;


// ==== special-points table (genus 4) ====
//   N : special points
//   137 : 8
//   173 : 6
//   199 : 8
//   201 : 11
//   202 : 11
//   214 : 9
//   219 : 11
//   247 : 5
//   251 : 6
//   254 : 8
//   259 : 7
//   262 : 7
//   267 : 5
//   273 : 11
//   305 : 7
//   311 : 4
//   319 : 5
//   321 : 6
//   322 : 8
//   334 : 5
//   335 : 4
//   341 : 6
//   345 : 9
//   354 : 10
//   355 : 5
//   366 : 10
//   370 : 9
//   374 : 7
//   385 : 6
//   395 : 5
//   399 : 9
//   426 : 8
//   434 : 6
//   483 : 3
//   546 : 7
//   570 : 8

