// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = 7.
// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical
// saturated-HNF star basis. Cusp forms not stored.
// All curves of this genus live in the single shared projective space P below.
//   models[N]`curve          : the curve X_0(N)^* in P
//   models[N]`special_points : number of special (CM + cusp) rational points

Q := Rationals();
P<x, y, z, w, t, u, v> := ProjectiveSpace(Q, 6);
ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, curve >;
models := AssociativeArray();


// ---- N = 193,  [ <193, 1> ],  special points = 11 ----
models[193] := rec< ModelRec | N := 193, genus := 7, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 3*y*v + 3*z*w - 4*z*v - 10*w^2 + 14*w*t - 7*w*u - 30*w*v - 23*t^2 + 19*t*u + 62*t*v + 13*u^2 - 105*u*v + 26*v^2,
    x*w - y*z + 3*y*v + 2*z*w + 4*z*v - 3*w^2 + w*t - 3*w*u - 15*w*v - t^2 + t*u + 3*t*v - 4*u*v - 11*v^2,
    x*t - z^2 + z*w + 9*z*v - 3*w*t - w*u + w*v + t*u - 13*t*v - 6*u*v - 6*v^2,
    x*u + z*v - w^2 + w*t - 3*w*u + 2*w*v - 3*t^2 + 4*t*u + 4*t*v - 22*u*v + 8*v^2,
    x*v - w*u + w*v - t^2 + 3*t*u - 2*t*v - 8*u*v + 2*v^2,
    y*w - z^2 + 7*z*v + 2*w^2 - 6*w*t + 2*w*u + 5*w*v + 9*t^2 - 7*t*u - 26*t*v - 4*u^2 + 32*u*v - 16*v^2,
    y*t - y*v - z*w + w^2 - 2*w*t + 8*w*v + t*u - 5*t*v - u*v + 5*v^2,
    y*u - y*v - w*t - w*u + 4*w*v + u^2 - 6*u*v + 5*v^2,
    z*t - 2*z*v - w^2 + w*t - w*v - 3*t^2 + t*u + 7*t*v + 2*u^2 - 10*u*v + 6*v^2,
    z*u - z*v - w*u + w*v - t^2 + t*u + 3*t*v - 7*u*v + 4*v^2
]) >;


// ---- N = 229,  [ <229, 1> ],  special points = 9 ----
models[229] := rec< ModelRec | N := 229, genus := 7, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 3*z*t - 4*z*v + w^2 - 10*w*t + 14*w*u - 6*w*v + 4*t^2 - 5*t*u + 19*t*v - 13*u^2 - 12*u*v + 18*v^2,
    x*w - y*z + 3*z*t + 2*z*v - w^2 - 4*w*t + 4*w*u - w*v + t*u + 4*t*v - 3*u^2 - 10*u*v + v^2,
    x*t - z^2 + 2*z*t + 4*z*v + w*u - 4*w*v - 4*t^2 - t*u - 2*t*v - 4*u*v + 5*v^2,
    x*u - z*w + z*t + 2*z*v + w*u + 2*w*v - 3*t*u - t*v - 2*u^2 - 5*u*v - 4*v^2,
    x*v - z*v - w*t + w*v + t^2 + t*u - 2*u*v - 4*v^2,
    y*w - z^2 + z*t + 2*z*v - w^2 + 2*w*t - 4*w*u - 2*t^2 + 2*t*u - 5*t*v + 4*u^2 + 2*u*v - 3*v^2,
    y*t - z*w + 3*z*v + 2*w*t - 2*t^2 - 2*t*u - 6*t*v + u^2 - u*v - v^2,
    y*u - z*t + z*v + w*t - 2*w*u - t*v - v^2,
    y*v - z*v - w*u + w*v + t*u - t*v + u^2 - 4*v^2,
    z*u - z*v - w*t + 2*w*v + t^2 - t*u + t*v - u^2 - 3*v^2
]) >;


// ---- N = 233,  [ <233, 1> ],  special points = 7 ----
models[233] := rec< ModelRec | N := 233, genus := 7, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 2*z*u - 10*z*v + 4*w^2 - 14*w*t + 7*w*u + 2*w*v + 8*t^2 + 6*t*u + 3*t*v - 12*u^2 + 6*u*v + 16*v^2,
    x*w - y*z + z*u + 7*z*v + 3*w^2 - 5*w*t - 7*w*u - 3*w*v + 3*t^2 + t*u - 5*t*v + 6*u^2 - 8*u*v + 4*v^2,
    x*t - z^2 + z*u + 8*z*v + 2*w^2 - w*t - 6*w*u - 2*w*v - 4*t*u - 5*t*v + 8*u^2 - 10*u*v,
    x*u - z*w - z*u + 5*z*v + w^2 + w*t - 3*w*u - w*v - 3*t*u - 2*t*v + 5*u^2 - 7*u*v - v^2,
    x*v - z*u + z*v - w*v - t*v + 2*u^2 - 3*u*v - v^2,
    y*w - z^2 + z*u + 8*z*v + 2*w*t - 7*w*u - 3*w*v - 4*t*u - 4*t*v + 8*u^2 - 7*u*v - 3*v^2,
    y*t - z*w + 3*z*v + 2*w*t - w*u - 2*t^2 - 3*t*u - 2*t*v + 3*u^2 - 3*u*v - 3*v^2,
    y*u - z*u + z*v - w^2 + 2*w*t - t^2 - 2*t*u + t*v + u^2 - 2*u*v - 2*v^2,
    y*v - z*u + z*v + w*t - w*u - w*v - t^2 + t*u - t*v + 2*u^2 - 2*u*v - 2*v^2,
    z*t - 3*z*v - w^2 + 3*w*u + w*v - t^2 + 2*t*v - 3*u^2 + 3*u*v
]) >;


// ---- N = 241,  [ <241, 1> ],  special points = 8 ----
models[241] := rec< ModelRec | N := 241, genus := 7, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + z*w - 11*z*u + z*v - 4*w^2 + 8*w*t + 12*w*u - 26*w*v - 8*t^2 + 22*t*u + 4*t*v - 23*u^2 + 26*u*v + 10*v^2,
    x*w - y*z + z*w - 2*z*u + 6*z*v - w^2 + 2*w*t - 2*w*u - 12*w*v - 2*t^2 + 8*t*u - t*v - 8*u^2 + 7*u*v - 2*v^2,
    x*t - z^2 + 9*z*v + w*t - 5*w*u + 5*w*v - 5*t*u - 9*t*v + 11*u^2 - 11*u*v - 10*v^2,
    x*u - 2*z*u + 2*z*v - w^2 + w*t + w*v - t*u - 2*t*v + u^2 - 2*u*v - 2*v^2,
    x*v - z*u + z*v + t*u - 3*t*v + u^2 - 2*u*v - 2*v^2,
    y*w - z^2 + 4*z*u + 5*z*v + w^2 - 2*w*t - 8*w*u + 8*w*v + 3*t^2 - 8*t*u - 5*t*v + 11*u^2 - 13*u*v - 8*v^2,
    y*t - z*w + z*u - w*t - w*u + 8*w*v + t^2 - 6*t*u - 3*t*v + 8*u^2 - 7*u*v - 2*v^2,
    y*u - w*t - w*u + 4*w*v + t^2 - 3*t*u - t*v + 3*u^2 - 3*u*v - 2*v^2,
    y*v - w*u + w*v - t*v + 2*u^2 - 4*u*v,
    z*t - z*u - 2*z*v - w^2 + 3*w*u - t^2 + t*v - u^2 + 3*u*v + 2*v^2
]) >;


// ---- N = 257,  [ <257, 1> ],  special points = 6 ----
models[257] := rec< ModelRec | N := 257, genus := 7, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 2*z*w - 4*z*t + 2*z*u - 2*w^2 + w*t - 10*w*u + 14*w*v + 4*t^2 + 2*t*u - 9*t*v + 2*u^2 + 11*u*v - 15*v^2,
    x*w - y*z + z*w - z*t + 2*z*u - w^2 - 3*w*t - 3*w*u + w*v + 2*t^2 + 4*t*u + t*v - 4*u^2 + 2*u*v - 2*v^2,
    x*t - z^2 + z*w + z*u - 3*w*t + t*v - u^2 - 2*u*v + v^2,
    x*u - z*t - w*t + t^2 + t*u + t*v - 4*u^2 - u*v,
    x*v - w*t + 2*t*u - 4*u*v - v^2,
    y*w - z^2 + z*t - 3*w*t + 3*w*u - 4*w*v + t*u + 5*t*v - u^2 - 6*u*v + 5*v^2,
    y*t - z*w + w^2 - w*t + 2*w*u - 4*w*v - t^2 + 2*t*v - 2*u^2 - u*v + 4*v^2,
    y*u - z*u - w*t + w*u - w*v + t*u + 2*t*v - u^2 - 3*u*v + 2*v^2,
    y*v - z*u + w*u - w*v + u^2 - 2*u*v,
    z*v - w*u + w*v - t*v + 2*u^2 - u*v - v^2
]) >;


// ---- N = 281,  [ <281, 1> ],  special points = 8 ----
models[281] := rec< ModelRec | N := 281, genus := 7, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + 7*z*t - 8*z*v - 5*w^2 - 2*w*t + 15*w*u + 4*w*v - 9*t^2 - 9*t*u + 28*t*v + u^2 - 26*u*v + 15*v^2,
    x*w - y*z + 2*z*t + 2*z*v - w^2 + 3*w*u - 4*w*v - 3*t^2 - 3*t*u + 6*t*v - 5*u*v + 5*v^2,
    x*t - z^2 + z*t + 2*z*v + w*t + w*u - 2*w*v - 3*t^2 - 2*t*u - t*v - u*v + 2*v^2,
    x*u - z*w - z*t + 3*z*v + w^2 + w*t - 4*w*v - 2*t*u - u^2 + 2*v^2,
    x*v + w*u - 2*w*v - t^2 - t*u + 2*t*v - 2*u*v + v^2,
    y*w - z^2 - z*t + 3*z*v + w^2 + w*t - 5*w*u - 2*w*v + 2*t^2 + 2*t*u - 9*t*v + 8*u*v - 4*v^2,
    y*t - z*w - z*t + 3*z*v + w^2 + w*t - w*u - 2*w*v - t*u - 5*t*v + 3*u*v - v^2,
    y*u - 2*z*t + z*v + w^2 - 3*w*u - w*v + 2*t^2 + 2*t*u - 4*t*v - u^2 + 4*u*v - 2*v^2,
    y*v - z*t + z*v + w^2 - 2*w*u - 2*w*v + t^2 + t*u - 3*t*v + 3*u*v - 2*v^2,
    z*u - z*v - w*t + 2*t*v - u*v + v^2
]) >;


// ---- N = 298,  [ <2, 1>, <149, 1> ],  special points = 11 ----
models[298] := rec< ModelRec | N := 298, genus := 7, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 21*z*u + 11*z*v + 3*w^2 - 28*w*t + 11*w*u + 4*w*v + 10*t^2 - 9*t*u - 24*t*v - 18*u^2 - 44*u*v - 25*v^2,
    x*w - y*z - 20*z*u - 15*z*v + 2*w^2 + 19*w*t - 17*w*u + 2*w*v - 8*t^2 + 14*t*u + 16*t*v + 22*u^2 + 38*u*v + 32*v^2,
    x*t - z^2 - 4*z*u + z*v + 2*w^2 + 4*w*t - 7*w*u + 2*w*v - 3*t^2 + 4*t*u + 6*u^2 + 4*u*v + 2*v^2,
    x*u - z*w - 5*z*u - 4*z*v + w^2 + 6*w*t - 5*w*u + 3*w*v - 2*t^2 + 2*t*u + 4*t*v + 5*u^2 + 6*u*v + 8*v^2,
    x*v + 4*z*u + 2*z*v - 4*w*t + 2*w*u + t^2 - 2*t*u - 4*t*v - 3*u^2 - 8*u*v - 6*v^2,
    y*w - z^2 - 11*z*u - 4*z*v + 13*w*t - 10*w*u - 5*t^2 + 7*t*u + 10*t*v + 12*u^2 + 20*u*v + 12*v^2,
    y*t - z*w - z*u - 2*z*v + 3*w*t - w*u + 2*w*v - 2*t^2 - t*u + 3*t*v + 2*u^2 + 2*u*v + 4*v^2,
    y*u - 2*z*u - z*v - w^2 + 3*w*t - w*v - t^2 + 2*t*v + 5*u*v + 2*v^2,
    y*v + 7*z*u + 5*z*v - 7*w*t + 4*w*u - w*v + 3*t^2 - 4*t*u - 6*t*v - 7*u^2 - 15*u*v - 11*v^2,
    z*t + 3*z*u + 2*z*v - w^2 - 3*w*t + 4*w*u - w*v + t^2 - 3*t*u - 4*t*v - 4*u^2 - 4*u*v - 4*v^2
]) >;


// ---- N = 309,  [ <3, 1>, <103, 1> ],  special points = 11 ----
models[309] := rec< ModelRec | N := 309, genus := 7, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 11*z*u - 40*z*v - 8*w*t + 6*w*u + 26*t^2 - 20*t*u + t*v - 14*u^2 + 61*u*v,
    x*w - y*z + 7*z*u - 14*z*v - 4*w*t + w*u - 4*w*v + 10*t^2 - 8*t*u + 5*t*v - 7*u^2 + 23*u*v - 3*v^2,
    x*t - z^2 + 3*z*u + z*v - w*t - t^2 - t*u - 2*u^2 - 2*u*v,
    x*u - z*w + 3*z*v + w*t + w*u - 4*t^2 + t*u + 4*t*v - u^2 - 9*u*v,
    x*v + z*t - 3*z*v - 2*w^2 + w*t + 3*w*u + w*v - 2*t*u - 3*t*v - u^2 + 2*u*v + 2*v^2,
    y*w - z^2 + 10*z*v - 3*w*u - 4*t^2 + 4*t*u - 2*t*v + 2*u^2 - 14*u*v,
    y*t - z*w + 3*z*v + w*u - 2*t^2 - t*v - 4*u*v,
    y*u + z*t - 3*z*u + 6*z*v - 2*w^2 + 3*w*t + w*u + 3*w*v - 6*t^2 + 2*t*u - 3*t*v + 2*u^2 - 12*u*v + 3*v^2,
    y*v - z*u + 3*z*v - 2*t^2 + 2*t*u - t*v + u^2 - 6*u*v,
    2*z*t - 5*z*v - 2*w^2 + 3*w*u + 3*w*v + 2*t^2 - 4*t*u - 5*t*v - u^2 + 7*u*v + 3*v^2
]) >;


// ---- N = 326,  [ <2, 1>, <163, 1> ],  special points = 9 ----
models[326] := rec< ModelRec | N := 326, genus := 7, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 - 2*z*v + 2*w*t - w*u - 3*w*v - 2*t^2 + 2*t*v + 2*u^2 + 3*u*v - 2*v^2,
    x*w - y*z + 2*z*u + z*v + w*t - w*u - 2*w*v - 3*t*u + u*v - 2*v^2,
    x*t - z^2 + z*u + 3*z*v + w*u - t^2 - 2*t*u - 2*t*v - u^2 - u*v - 2*v^2,
    x*u - z*w + z*v + 2*w*t - 3*t*u - t*v - u^2 - 2*v^2,
    x*v - z*u - w^2 + w*t + w*u - w*v - 2*t*v + 2*u*v - v^2,
    y*w - z^2 + z*u + 2*z*v - w*t + w*v + t^2 - t*u - t*v - u^2 - 2*u*v,
    y*t - z*w + w*u + w*v - t*u - t*v - u^2,
    y*u - z*u + z*v - w^2 + w*t + w*u - t*u - 2*t*v - u^2 + u*v,
    y*v - w*t + t*u - 2*u*v,
    z*t - z*u - w^2 + w*t + w*u - w*v - t^2 - t*v + 2*u*v
]) >;


// ---- N = 358,  [ <2, 1>, <179, 1> ],  special points = 9 ----
models[358] := rec< ModelRec | N := 358, genus := 7, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + z*w - 2*z*u + 2*z*v - 4*w^2 + 2*w*t - 6*w*u + 13*w*v - t*u - 5*t*v + 3*u^2 - 5*u*v - 5*v^2,
    x*w - y*z + z*w + 2*z*u - z*v - w^2 - w*t - 3*w*u + 3*w*v - t*u + u*v - 3*v^2,
    x*t - z^2 + 2*z*u + 2*z*v - 2*w*t - 2*w*u + 4*w*v + 2*t^2 - 7*t*u - 6*t*v + 4*u^2 + 2*u*v - v^2,
    x*u - z*u + 2*z*v - w^2 - 2*w*u + 4*w*v + t^2 - 2*t*u - 4*t*v + u^2 - u*v - v^2,
    x*v - w*t + w*v + t^2 - 2*t*u - 2*t*v + 2*u^2 - u*v - v^2,
    y*w - z^2 + 2*z*u + w^2 - 2*w*t - 2*w*v + 2*t^2 - 4*t*u - 2*t*v + 2*u^2 + 4*u*v + v^2,
    y*t - z*w - 3*z*u + 5*z*v - w*t + w*v + 2*t^2 - 2*t*u - 8*t*v + 4*u^2 - u*v + 3*v^2,
    y*u - z*u + z*v - w*t + t^2 - t*u - t*v + u^2 - u*v + v^2,
    y*v - z*u + z*v - w*v + t*u - 2*t*v + v^2,
    z*t - 2*z*u + 2*z*v - w^2 - w*u + 3*w*v - 3*t*v + 2*u^2 - 2*u*v
]) >;


// ---- N = 365,  [ <5, 1>, <73, 1> ],  special points = 6 ----
models[365] := rec< ModelRec | N := 365, genus := 7, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + y*v - 3*z*u - 12*z*v + w^2 - w*t + w*u + 6*w*v - 7*t^2 + 2*t*u + 2*t*v + 6*u^2 - u*v + 20*v^2,
    x*w - y*z + z*t + 3*z*u - z*v - 2*w*t - 2*w*u + w*v + t^2 + t*u - 3*t*v + u^2 - 2*u*v + 2*v^2,
    x*t - z^2 + z*t + z*u + 5*z*v - t*u - 4*t*v - u^2 - 2*u*v - 6*v^2,
    x*u - z*w + z*t + w*t + 3*w*v - t*u - 2*t*v - u^2 - 2*u*v,
    x*v + y*v - z*v - w*v - t^2 - t*u - 2*u*v,
    y*w - z^2 + z*t + 6*z*v - w^2 + w*t - w*v + t^2 - t*u - 2*t*v - 2*u^2 - 8*v^2,
    y*t - z*w + z*u + 3*z*v + t^2 - 2*t*u - u^2 - 2*u*v - 6*v^2,
    y*u + 2*z*t - z*u - 3*w^2 + 2*w*t + 4*w*u + 3*w*v - 2*t^2 + t*u - 2*t*v - 5*u^2 - 2*u*v,
    2*y*v - z*u - 2*z*v + w*t + w*u - 2*t^2 - t*u + t*v - 2*u*v + 4*v^2,
    3*z*t - 2*z*u - 3*z*v - 3*w^2 + 2*w*t + 5*w*u + 6*w*v - 4*t^2 + 2*t*u - 3*t*v - 3*u^2 - 2*u*v + 6*v^2
]) >;


// ---- N = 411,  [ <3, 1>, <137, 1> ],  special points = 7 ----
models[411] := rec< ModelRec | N := 411, genus := 7, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 6*z*u - 3*z*v + w^2 - 8*w*t - 2*w*u + 10*w*v + 7*t^2 + 2*t*u - 7*t*v - 5*u^2 - 7*u*v + 8*v^2,
    x*w - y*z + 3*z*u + 2*z*v + w^2 - 4*w*t - 2*w*u + w*v + 2*t^2 + t*u - 2*t*v - u^2 - 3*u*v + 2*v^2,
    x*t - z^2 + z*u + 2*z*v - w*t + w*v - t^2 - t*u - u*v - v^2,
    x*u - z*w + z*u - w*t + w*v + t^2 - t*v - u^2 - 2*u*v + v^2,
    x*v - w*t + w*v - u*v - v^2,
    y*w - z^2 + 3*z*v + w*t - 4*w*v - 2*t^2 - t*u + 2*t*v + u^2 + u*v - 2*v^2,
    y*t - z*w - z*u + z*v + w*t + w*u - w*v - 2*t^2 - t*u + t*v + u^2 + u*v - 2*v^2,
    y*u - z*u + z*v - w^2 + w*t + w*u - t^2 - t*u + t*v - u*v - v^2,
    y*v - z*u + w*t - 2*w*v - t^2 + t*v + u^2 + u*v - 2*v^2,
    z*t - z*u - z*v - w^2 + w*t + w*u + w*v - t^2 - t*u + t*v + u*v - v^2
]) >;


// ---- N = 437,  [ <19, 1>, <23, 1> ],  special points = 3 ----
models[437] := rec< ModelRec | N := 437, genus := 7, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + 7*z*u - 5*z*v + w^2 - 8*w*t - 9*w*u - 3*w*v + 5*t^2 + 4*t*u - 18*t*v + 3*u^2 + 20*v^2,
    x*w - y*z + 7*z*u + w^2 - 6*w*t - 8*w*u - 4*w*v + 6*t^2 + 2*t*u - 18*t*v + 2*u^2 + 12*v^2,
    x*t - z^2 + 6*z*u + 4*z*v + w^2 - 6*w*t - 6*w*u - 3*w*v + 4*t^2 + t*u - 15*t*v - 3*u*v + 4*v^2,
    x*u - z*w + z*u - w*u + 2*w*v - t*u - u^2 - 3*u*v,
    x*v + z*u - z*v - w*t - w*u - t*v - u*v + v^2,
    y*w - z^2 + z*u + 5*z*v - w*u - 2*w*v + t^2 - 2*t*v - u^2 - 2*u*v - 6*v^2,
    y*t - z*w + 2*z*u - w*t - w*u + 2*w*v - 2*t*u - u^2 - 3*u*v,
    y*u - 4*z*u - w^2 + 4*w*t + 5*w*u + 3*w*v - 4*t^2 - 2*t*u + 12*t*v - 2*u^2 - 8*v^2,
    y*v - z*u + w*t + w*u - t^2 - t*u + 3*t*v - u*v - 2*v^2,
    z*t - 4*z*u - z*v - w^2 + 4*w*t + 5*w*u + 3*w*v - 4*t^2 - 2*t*u + 10*t*v - u^2 + u*v - 6*v^2
]) >;


// ---- N = 445,  [ <5, 1>, <89, 1> ],  special points = 6 ----
models[445] := rec< ModelRec | N := 445, genus := 7, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 2*w*t - w*u + 3*w*v - 3*t^2 - 2*t*u + 5*t*v + u^2 - 3*u*v - v^2,
    x*w - y*z + 2*z*u + z*v - 2*w*u - 2*w*v - u*v + v^2,
    x*t - z^2 + z*v + w*t - 2*w*v - 4*t*v + 2*u*v + 4*v^2,
    x*u - z*w + z*u - t*u + t*v - u^2 - 2*u*v - v^2,
    x*v - z*u - w^2 + 2*w*t + w*u - t^2 - t*u + u*v,
    y*w - z^2 + z*v - w*u - 4*w*v + 2*t^2 + 2*t*u - 6*t*v + 3*u*v + 5*v^2,
    y*t - z*w - 2*z*u - z*v + 2*w*t + 2*w*u - 4*w*v - 2*t*v + 6*u*v + 2*v^2,
    y*u - z*u - w^2 + w*t + w*u - t*u - t*v - u^2 + 2*u*v + v^2,
    y*v - z*u - z*v + w*u - 3*w*v + t^2 + t*u - 2*t*v + 2*u*v + v^2,
    z*t - 2*z*u - z*v - w^2 + 2*w*t + 2*w*u - w*v - t^2 - t*u + 4*u*v + v^2
]) >;


// ---- N = 446,  [ <2, 1>, <223, 1> ],  special points = 7 ----
models[446] := rec< ModelRec | N := 446, genus := 7, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 - z*u + z*v + 2*w*t - 3*w*u - 4*w*v - t^2 + t*u + t*v + u^2 + u*v - 5*v^2,
    x*w - y*z + 2*z*u + 3*z*v - 3*w*u - 3*w*v + 2*t*v - 2*u*v - 6*v^2,
    x*t - z^2 + 2*z*u + 3*z*v - w*t - w*u - t*u - 3*t*v - u*v - v^2,
    x*u - z*w + 2*z*v + w*t - w*u - t*u - t*v - 2*u*v - 2*v^2,
    x*v - w^2 + w*u - 2*t*v,
    y*w - z^2 + 2*z*u + z*v - 2*w*t + 2*w*v + t^2 - t*u - t*v - u*v + v^2,
    y*t - z*w + w*u + w*v - t*u - 2*t*v + 2*v^2,
    y*u - w^2 + w*u + w*v - t*v - u^2 - u*v + v^2,
    y*v - z*u - z*v + w*u - t*v + u*v + 2*v^2,
    z*t - z*u + z*v - w^2 + w*t - w*v - t^2 + t*u - t*v - u*v - v^2
]) >;


// ---- N = 474,  [ <2, 1>, <3, 1>, <79, 1> ],  special points = 11 ----
models[474] := rec< ModelRec | N := 474, genus := 7, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + z*t - 4*z*v - w^2 + w*t + w*u + w*v + t^2 + 2*t*u - 4*t*v - 3*u*v + 3*v^2,
    x*w - y*z + z*t + z*u - z*v - w^2 - u*v - v^2,
    x*t - z^2 + 5*z*t - z*u - 7*z*v - 5*w^2 + 2*w*t + 9*w*u + 2*w*v - 2*t^2 + t*u - 7*t*v - 2*u^2 - 7*u*v + 8*v^2,
    x*u - z*w + 2*z*t - 2*z*v - 2*w^2 + 3*w*u + 3*w*v - t^2 - 2*t*v - u^2 - 5*u*v + 2*v^2,
    x*v - z*v - w^2 + w*u + w*v - u*v - 2*v^2,
    y*w - z^2 + 6*z*t - 2*z*u - 8*z*v - 6*w^2 + 2*w*t + 11*w*u + 2*w*v - 2*t^2 + 2*t*u - 6*t*v - 3*u^2 - 8*u*v + 9*v^2,
    y*t - z*w + 5*z*t - z*u - 7*z*v - 5*w^2 + w*t + 10*w*u + 3*w*v - 2*t^2 + t*u - 7*t*v - 3*u^2 - 7*u*v + 9*v^2,
    y*u + 2*z*t - z*u - 4*z*v - 3*w^2 + w*t + 5*w*u + 2*w*v - t^2 - t*v - 2*u^2 - 3*u*v + 2*v^2,
    y*v + 2*z*t - z*u - 3*z*v - 2*w^2 + 4*w*u + w*v - t^2 + t*u - 2*t*v - u^2 - 3*u*v + 3*v^2,
    7*z*t - 2*z*u - 11*z*v - 7*w^2 + 2*w*t + 13*w*u + 4*w*v - 2*t^2 + 3*t*u - 8*t*v - 4*u^2 - 10*u*v + 11*v^2
]) >;


// ---- N = 478,  [ <2, 1>, <239, 1> ],  special points = 5 ----
models[478] := rec< ModelRec | N := 478, genus := 7, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 - 4*z*u - 22*z*v + 5*w*t + 19*w*u + 13*w*v + t^2 - 17*t*u + 3*t*v - 5*u^2 + 12*u*v + 12*v^2,
    x*w - y*z - 6*z*v + 2*w*t + 5*w*u + 2*w*v - 5*t*u + t*v - 2*u^2 + 4*u*v + 4*v^2,
    x*t - z^2 + 3*z*u + 16*z*v - 3*w*t - 13*w*u - 9*w*v - t^2 + 11*t*u - 4*t*v + 4*u^2 - 8*u*v - 8*v^2,
    x*u - z*w - 3*z*v + w*t + 3*w*u + 2*w*v - 3*t*u - u^2 + u*v + 2*v^2,
    x*v - w^2 + w*u - t*v - v^2,
    y*w - z^2 + 4*z*u + 20*z*v - 4*w*t - 18*w*u - 12*w*v + 14*t*u - 4*t*v + 5*u^2 - 10*u*v - 10*v^2,
    y*t - z*w + z*u + 2*z*v - w*t - w*u - t^2 + t*u + u^2 - 2*u*v - 2*v^2,
    y*u + z*v - w^2 - w*v + t*u - t*v - u^2,
    y*v - z*v - w*t + w*u + w*v - u*v,
    z*t - z*u - 7*z*v - w^2 + w*t + 7*w*u + 4*w*v - 5*t*u - 2*u^2 + 4*u*v + 4*v^2
]) >;


// ---- N = 498,  [ <2, 1>, <3, 1>, <83, 1> ],  special points = 10 ----
models[498] := rec< ModelRec | N := 498, genus := 7, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + 2*y*v - 2*z*t + 6*z*v + 3*w^2 - 4*w*t + 5*w*u - 2*w*v - 5*t^2 + 9*t*u + 28*t*v - 4*u^2 - 23*u*v - 33*v^2,
    x*w - y*z + 2*y*v + w^2 - 5*w*v - 2*t^2 + 2*t*u + 8*t*v - 4*u*v - 8*v^2,
    x*t - z^2 + w^2 - 2*w*u - 2*w*v + t*u - 2*t*v + u^2 - v^2,
    x*u + y*v - z*w + z*t + w*u - t^2 + 4*t*v - u^2 - 5*u*v - 4*v^2,
    x*v + y*v - z*t + 3*z*v + w^2 + w*u - 3*w*v - 2*t^2 + 3*t*u + 10*t*v - u^2 - 7*u*v - 14*v^2,
    y*w + 2*y*v - z^2 + 4*z*v + w*t + 2*w*u - 5*w*v - 3*t^2 + 5*t*u + 17*t*v - 2*u^2 - 12*u*v - 19*v^2,
    y*t - z*w + z*v + w*t + w*u - w*v - 2*t^2 + 6*t*v - u*v - 5*v^2,
    y*u - 2*z*v - w^2 + w*t - 2*w*u + w*v + 2*t^2 - 3*t*u - 10*t*v + u^2 + 8*u*v + 12*v^2,
    3*y*v - z*t + 6*z*v + w^2 + 4*w*u - 5*w*v - 5*t^2 + 6*t*u + 24*t*v - 3*u^2 - 16*u*v - 26*v^2,
    z*u + 3*z*v - w*t + 2*w*u + w*v - t^2 + t*u + 5*t*v - 2*u^2 - 6*u*v - 7*v^2
]) >;


// ---- N = 501,  [ <3, 1>, <167, 1> ],  special points = 5 ----
models[501] := rec< ModelRec | N := 501, genus := 7, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 - 3*z*u - z*v + w^2 + w*t + 3*w*u + w*v + t^2 + 3*t*u - 4*t*v - 4*u^2 + 4*u*v + 4*v^2,
    x*w - y*z - z*u + w^2 - w*u + w*v + 4*t*u - 3*t*v - 2*u^2 + u*v + 2*v^2,
    x*t - z^2 + 2*z*u + z*v + w^2 - 2*w*t - 2*w*u + w*v - t*v - u*v,
    x*u - z*w - z*u + w*t + w*v + t*u - 2*t*v - u*v + v^2,
    x*v - z*u + t*u - t*v + u^2 - u*v,
    y*w - z^2 + 2*z*u + z*v - w*t - 2*w*u - w*v - t*u + t*v - v^2,
    y*t - z*w + w*t - t^2 - t*v + u^2 - u*v,
    y*u + z*v - w^2 - 2*t*u + t*v + u^2 - 2*u*v - v^2,
    y*v + z*u - w*t - w*u - t*u + t*v + u^2 - u*v - 2*v^2,
    z*t - w^2 + w*u - 2*t*u + t*v + u^2 - v^2
]) >;


// ---- N = 518,  [ <2, 1>, <7, 1>, <37, 1> ],  special points = 8 ----
models[518] := rec< ModelRec | N := 518, genus := 7, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + 6*z*t - 6*z*v - 6*w^2 + w*t + 2*w*u + 2*w*v + 4*t^2 - 2*t*u - 6*t*v - u^2 + 2*u*v + 5*v^2,
    x*w - y*z + 2*z*t + 2*z*u - z*v - 2*w^2 - w*t - w*u + t^2 + t*u - t*v - u^2 + v^2,
    x*t - z^2 + z*u + z*v - w*t - t*v - u*v,
    x*u - z*w + z*t - w^2 + w*t + w*v - t*u - t*v - u*v,
    x*v - z*v - w^2 - w*u + w*v + 2*t^2 - 2*t*v + 2*u^2 - 2*u*v,
    y*w - z^2 - z*t + 2*z*u + 2*z*v + w^2 - 2*w*t - w*v - t^2 + t*u + 2*t*v - 2*u^2 - v^2,
    y*t - z*w + z*u - w*t + w*v - u*v,
    y*u - z*t + z*u + z*v - w*t + w*v + t*v - u^2 - u*v - v^2,
    y*v - 3*z*t + 2*z*v + 3*w^2 - w*t - w*u - w*v - t^2 + t*u + 2*t*v + u^2 - 2*u*v - 2*v^2,
    3*z*u - 3*w*t - w*u + w*v + t^2 + 2*t*u + t*v - 2*u^2 - u*v
]) >;


// ---- N = 519,  [ <3, 1>, <173, 1> ],  special points = 5 ----
models[519] := rec< ModelRec | N := 519, genus := 7, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 3*z*t + z*u - 6*z*v - 2*w^2 - 2*w*t + 4*w*v + t^2 - t*u + t*v + 2*u*v,
    x*w - y*z + 2*z*t + z*u - w^2 - w*t - t*u,
    x*t - z^2 + z*u - t*u - 2*t*v + u*v + v^2,
    x*u - z*w - z*u + 2*z*v + w^2 + 2*w*t - 2*w*v - t^2 - t*u - t*v - 2*u*v,
    x*v + 2*z*t + z*u - 2*z*v - 2*w^2 - w*t + w*u + 4*w*v - t*u - u*v - 3*v^2,
    y*w - z^2 + z*v + w*t - t^2 - 2*u*v - 2*v^2,
    y*t - z*w + 2*z*v + w*u + w*v - t^2 - 2*u*v - 2*v^2,
    y*u + 3*z*t - 4*z*v - 4*w^2 + w*t + 2*w*u + 8*w*v - t^2 - 2*t*u - 3*u*v - 5*v^2,
    y*v + z*t - w^2 + w*u + 3*w*v - t^2 + t*v - 3*u*v - 4*v^2,
    4*z*t + z*u - 4*z*v - 4*w^2 - w*t + 2*w*u + 9*w*v - t^2 - t*u + 2*t*v - 3*u*v - 6*v^2
]) >;


// ---- N = 527,  [ <17, 1>, <31, 1> ],  special points = 2 ----
models[527] := rec< ModelRec | N := 527, genus := 7, squarefree := true, hyperelliptic := false, special_points := 2, curve := Curve(P, [
    x*z - y^2 + z*w - 3*z*t - z*u + w^2 + 2*w*t - 2*w*u - w*v + 5*t^2 - 6*t*u - 2*t*v + 8*u^2 + u*v + 2*v^2,
    x*w - y*z + z*w - 2*z*t + z*u + w^2 - 2*w*u - 2*w*v + 4*t^2 - 4*t*u - t*v + 5*u^2 + 3*v^2,
    x*t - z^2 - z*t + 3*z*u + w^2 - 2*w*t - w*u + t^2 - t*v - 3*u*v + 5*v^2,
    x*u - z*t + t^2 - t*u + v^2,
    x*v - w*t + t*u - t*v - u^2,
    y*w - z^2 + 2*z*u + w^2 - 2*w*t - w*u - w*v + t^2 + t*u - t*v - 3*u*v + 5*v^2,
    y*t - z*w + z*t - w^2 - w*t + 3*w*u + 2*w*v - 3*t^2 + 2*t*u + 2*t*v - 5*u^2 - 3*v^2,
    y*u - w*t + t*u - u^2 - u*v + v^2,
    y*v - t^2 + t*u + t*v - u^2 - u*v - v^2,
    z*v - w*u - w*v + t*u - t*v
]) >;


// ---- N = 530,  [ <2, 1>, <5, 1>, <53, 1> ],  special points = 11 ----
models[530] := rec< ModelRec | N := 530, genus := 7, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 2*y*v - z*v - w^2 - w*t - w*u + w*v + t^2 - t*u - t*v + u^2 - v^2,
    x*w - y*z + y*v - z*u + z*v + w*t - 2*w*v + u*v - v^2,
    x*t + y*v - z^2 + 5*z*u - z*v - 6*w*t - 4*w*u + 4*w*v + 4*t^2 + t*u - t*v - 6*u^2 + 4*u*v - 3*v^2,
    x*u + 2*y*v - z*w + 8*z*u - 3*z*v - w^2 - 11*w*t - 8*w*u + 9*w*v + 8*t^2 + 3*t*u - t*v - 12*u^2 + 8*u*v - 6*v^2,
    x*v + y*v + 6*z*u - 2*z*v - 2*w^2 - 8*w*t - 6*w*u + 7*w*v + 6*t^2 + t*u - t*v - 7*u^2 + 5*u*v - 5*v^2,
    y*w - z^2 + 2*z*v - 2*w*u + t^2 - u^2 + 2*u*v - 2*v^2,
    y*t + y*v - z*w + 5*z*u - 2*z*v - 7*w*t - 4*w*u + 5*w*v + 4*t^2 + 2*t*u - t*v - 7*u^2 + 5*u*v - 3*v^2,
    y*u + 5*z*u - 2*z*v - w^2 - 6*w*t - 4*w*u + 5*w*v + 4*t^2 + t*u - 6*u^2 + 3*u*v - 2*v^2,
    2*y*v + 9*z*u - 4*z*v - 13*w*t - 9*w*u + 9*w*v + 8*t^2 + 4*t*u - t*v - 12*u^2 + 8*u*v - 5*v^2,
    z*t + 3*z*u - z*v - w^2 - 3*w*t - 2*w*u + 3*w*v + t^2 - t*v - u^2 - u*v
]) >;


// ---- N = 582,  [ <2, 1>, <3, 1>, <97, 1> ],  special points = 9 ----
models[582] := rec< ModelRec | N := 582, genus := 7, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + z*t + 3*z*u - 5*z*v - 5*w*t - 2*w*u + 3*w*v + 4*t^2 - 7*t*v + u^2 - 6*u*v + 7*v^2,
    x*w - y*z + 2*z*u - z*v + w^2 - 2*w*t - 2*w*u + 6*w*v + 3*t^2 + t*u + 2*t*v + 2*u^2 - 7*u*v - 3*v^2,
    x*t - z^2 + z*t + 5*z*u + z*v - 4*w*t - 3*w*u + 11*w*v + 7*t^2 - t*u - 4*t*v + 4*u^2 - 13*u*v - 5*v^2,
    x*u - z*w + z*t + 3*z*u - z*v - 2*w*t - w*u + 4*w*v + 4*t^2 - 2*t*u - 6*t*v + u^2 - 6*u*v + 2*v^2,
    x*v + z*u - z*v - w*t - w*u + t^2 - 2*t*v - 2*u*v + v^2,
    y*w - z^2 + 2*z*u + 3*z*v - w*t - 2*w*u + 5*w*v + 3*t^2 + t*v + 2*u^2 - 6*u*v - 6*v^2,
    y*t - z*w + z*t + 2*z*u - w^2 - w*t + 6*w*v + 3*t^2 - 2*t*u - 3*t*v + 2*u^2 - 4*u*v - 2*v^2,
    y*u + z*t + 2*z*u - z*v - 2*w^2 - w*t + 3*w*v + 4*t^2 - 2*t*u - 6*t*v + u^2 - 3*u*v + 2*v^2,
    y*v + z*t - w^2 + w*u - w*v - t*u - 3*t*v + u*v + v^2,
    2*z*t + 3*z*u - 2*z*v - 2*w^2 - 3*w*t + 5*w*v + 5*t^2 - 2*t*u - 8*t*v + 2*u^2 - 5*u*v + 3*v^2
]) >;


// ---- N = 623,  [ <7, 1>, <89, 1> ],  special points = 3 ----
models[623] := rec< ModelRec | N := 623, genus := 7, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + z*t + z*v - w^2 + w*t - 2*w*u - 3*w*v - 2*t^2 + 2*t*u - 2*u*v - v^2,
    x*w - y*z + z*t + z*u + z*v - w^2 - w*v - 2*t^2 + t*u + t*v - u^2 - u*v - 2*v^2,
    x*t - z^2 - z*t + z*u + 2*z*v + w^2 - 3*w*u - 2*w*v + 2*t^2 - 3*t*v + 2*u^2 - u*v + 3*v^2,
    x*u - z*w - z*t + z*v + w^2 + w*t - w*u - w*v + t^2 - t*v + u^2 - u*v + v^2,
    x*v - z*t + z*u - z*v - w*t + w*u + w*v + t^2 - t*u + u*v,
    y*w - z^2 - z*t + 2*z*v + w^2 - 4*w*u - 3*w*v + 3*t^2 - 3*t*v + 3*u^2 - u*v + 4*v^2,
    y*t - z*w - z*t + z*u - z*v + w^2 - w*t + w*u + 2*w*v + t^2 - 2*t*u + u*v + v^2,
    y*u - z*t + z*u - 2*z*v - w*t + 2*w*u + 3*w*v + t^2 - 2*t*u + t*v - u^2 + 2*u*v,
    y*v + z*u - 2*z*v - 2*w*t + 3*w*u + 3*w*v - t^2 - t*u + 2*t*v - 2*u^2 + u*v - 2*v^2,
    2*z*u - 3*z*v - 2*w*t + 4*w*u + 4*w*v - t^2 - 2*t*u + 3*t*v - 2*u^2 + 2*u*v - 2*v^2
]) >;


// ---- N = 638,  [ <2, 1>, <11, 1>, <29, 1> ],  special points = 7 ----
models[638] := rec< ModelRec | N := 638, genus := 7, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + z*u + 2*z*v - w*t + w*v - 2*t^2 - 4*t*u + 3*t*v + 2*u^2 - u*v - 2*v^2,
    x*w - y*z + 3*z*u + 2*z*v - 3*w*t - 5*t*u + 4*t*v + u^2 - 2*u*v - v^2,
    x*t - z^2 - z*t + 2*z*v + w^2 + w*u - w*v - 2*t^2 + t*v - u*v - v^2,
    x*u - z*w + z*t + 3*z*u + 3*z*v - w^2 - 3*w*t + w*u + 3*w*v - 3*t^2 - 5*t*u + 5*t*v - 2*u*v - 3*v^2,
    x*v - z*t + 4*z*u + 2*z*v - 5*w*t + 3*w*u + w*v - 3*t^2 - 3*t*u + 8*t*v - u^2 - 4*u*v - 3*v^2,
    y*w - z^2 - z*t + 4*z*u + 3*z*v + w^2 - 4*w*t + 3*w*u - w*v - 6*t^2 + 7*t*v - 4*u*v - 2*v^2,
    y*t - z*w + z*t + z*u + z*v - w^2 - w*t + 2*w*v - t^2 - 2*t*u + t*v - v^2,
    y*u - z*t + 2*z*u + 2*z*v - 2*w*t + w*u + w*v - 3*t^2 - 2*t*u + 4*t*v + u^2 - 2*u*v - 2*v^2,
    y*v + 4*z*u + 2*z*v - 5*w*t + 3*w*u + w*v - 6*t^2 - t*u + 8*t*v - u^2 - 3*u*v - 3*v^2,
    5*z*u + 3*z*v - 5*w*t + 3*w*u + w*v - 6*t^2 - 4*t*u + 9*t*v + u^2 - 4*u*v - 3*v^2
]) >;


// ---- N = 646,  [ <2, 1>, <17, 1>, <19, 1> ],  special points = 4 ----
models[646] := rec< ModelRec | N := 646, genus := 7, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 - 24*z*u + 25*z*v + 25*w*t - 9*w*u - 28*w*v - 18*t^2 + 28*t*u + 15*t*v - 23*u^2 - 8*u*v - 8*v^2,
    x*w - y*z + 4*z*u - 3*z*v - 3*w*t + 2*w*u + 2*w*v + t^2 - 4*t*u + t*v + 3*u^2 + 2*u*v - v^2,
    x*t - z^2 + z*t + 33*z*u - 37*z*v - w^2 - 32*w*t + 16*w*u + 34*w*v + 23*t^2 - 41*t*u - 18*t*v + 30*u^2 + 18*u*v + 8*v^2,
    x*u - z*w + z*t + 22*z*u - 25*z*v - w^2 - 21*w*t + 10*w*u + 23*w*v + 16*t^2 - 26*t*u - 13*t*v + 20*u^2 + 8*u*v + 7*v^2,
    x*v + z*t + 21*z*u - 23*z*v - 2*w^2 - 20*w*t + 8*w*u + 22*w*v + 16*t^2 - 25*t*u - 13*t*v + 21*u^2 + 6*u*v + 6*v^2,
    y*w - z^2 + z*t + 24*z*u - 27*z*v - w^2 - 24*w*t + 10*w*u + 26*w*v + 18*t^2 - 29*t*u - 15*t*v + 23*u^2 + 10*u*v + 8*v^2,
    y*t - z*w + z*t + 31*z*u - 33*z*v - w^2 - 31*w*t + 11*w*u + 35*w*v + 23*t^2 - 35*t*u - 20*t*v + 29*u^2 + 8*u*v + 11*v^2,
    y*u + z*t + 26*z*u - 27*z*v - 2*w^2 - 26*w*t + 7*w*u + 30*w*v + 21*t^2 - 29*t*u - 19*t*v + 27*u^2 + 2*u*v + 11*v^2,
    y*v + 7*z*u - 7*z*v - 8*w*t + 2*w*u + 9*w*v + 6*t^2 - 8*t*u - 6*t*v + 7*u^2 + u*v + 3*v^2,
    2*z*t + 19*z*u - 21*z*v - 2*w^2 - 19*w*t + 5*w*u + 22*w*v + 16*t^2 - 22*t*u - 15*t*v + 21*u^2 + u*v + 9*v^2
]) >;


// ---- N = 658,  [ <2, 1>, <7, 1>, <47, 1> ],  special points = 6 ----
models[658] := rec< ModelRec | N := 658, genus := 7, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 - 3*z*v + w*t - 2*w*u - 2*w*v + t^2 + t*u - 3*t*v + u^2 + u*v + 4*v^2,
    x*w - y*z + 3*z*v + w*t - 3*w*v - t^2 + t*u + 3*t*v - u^2 - 2*u*v - 4*v^2,
    x*t - z^2 + z*u + 3*z*v - w*t - w*u + t^2 - 3*t*v - u*v - 2*v^2,
    x*u - z*w + w*t + w*u + 2*w*v - t^2 - t*u + 3*t*v - 2*v^2,
    x*v + z*u + 3*z*v - w*t - t^2 + t*u + 3*t*v - u^2 - 4*u*v - 7*v^2,
    y*w - z^2 - w*u - w*v + 2*t^2 - 2*t*u - 4*t*v + u^2 + 4*u*v + 3*v^2,
    y*t - z*w + z*u + 2*z*v - w*t + w*u + 2*w*v - t^2 + 2*t*v - u^2 - 3*u*v - 4*v^2,
    y*u - 2*z*u - 7*z*v - w^2 + 2*w*t - 2*w*u + 3*t^2 - 2*t*u - 9*t*v + 3*u^2 + 9*u*v + 13*v^2,
    y*v + z*u + 2*z*v - w*t + w*u + w*v - t^2 + 3*t*v - u^2 - 3*u*v - 5*v^2,
    z*t - z*v - w^2 + w*u + 2*w*v - t^2 + v^2
]) >;


// ---- N = 671,  [ <11, 1>, <61, 1> ],  special points = 4 ----
models[671] := rec< ModelRec | N := 671, genus := 7, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + 3*z*t - 5*z*u - 2*w^2 + 5*w*t + w*u + t^2 - 3*t*u - 5*t*v - 2*u^2 + 5*u*v + 2*v^2,
    x*w - y*z + z*t - z*u + 2*z*v - w^2 + w*v + t^2 - 2*t*v,
    x*t - z^2 + 3*z*t - 4*z*u + z*v - 3*w^2 + 4*w*t + 3*w*v - t^2 - 5*t*v,
    x*u - z*w + 2*z*t - 3*z*u + 2*z*v - 2*w^2 + 3*w*t + w*u + w*v - 2*t*u - 3*t*v + u^2 - 2*u*v + v^2,
    x*v + 2*z*t - 3*z*u + z*v - 2*w^2 + 2*w*t + w*u + 2*w*v - 3*t*v - v^2,
    y*w - z^2 + z*t - w^2 - w*u + w*v - t^2 + t*u + u^2 - u*v - v^2,
    y*t - z*w + 3*z*t - 4*z*u + 2*z*v - 3*w^2 + 4*w*t + 2*w*u + 2*w*v - 2*t^2 - 2*t*u - 3*t*v + 2*u^2 - 3*u*v,
    y*u - z*u + z*v - w^2 + w*t + w*v - t*v - 2*u*v,
    y*v + 2*z*t - 3*z*u - 2*w^2 + 3*w*t + w*u + 2*w*v - 2*t^2 + t*u - 2*t*v - u*v - 2*v^2,
    4*z*t - 6*z*u + z*v - 4*w^2 + 6*w*t + 2*w*u + 3*w*v - 2*t^2 - t*u - 4*t*v - v^2
]) >;


// ---- N = 710,  [ <2, 1>, <5, 1>, <71, 1> ],  special points = 4 ----
models[710] := rec< ModelRec | N := 710, genus := 7, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + z*t - z*u - 2*z*v + w*t + 3*w*u + w*v - t^2 + 2*t*v + 2*u^2 - 5*u*v + v^2,
    x*w - y*z + 2*z*t - z*v - w^2 - w*t + w*v - t*u + 2*t*v + u^2 - u*v + v^2,
    x*t - z^2 + z*v - w*u - t*v + u*v,
    x*u - z*w + z*u - z*v - w*t - 3*w*u + 2*t^2 - t*v + 5*u*v + 2*v^2,
    x*v + 2*z*t - 4*z*v - 2*w^2 - w*t - w*u + 3*w*v + t^2 + t*v + u^2 + 2*u*v + v^2,
    y*w - z^2 + z*t + 3*z*u - 3*z*v - w^2 - 2*w*t - 5*w*u - w*v + 3*t^2 + t*u - 2*t*v - u^2 + 9*u*v + 4*v^2,
    y*t - z*w + z*u - w*t - 2*w*u + t^2 - 2*t*v + 4*u*v + v^2,
    y*u + z*t + z*u - 6*z*v - 2*w^2 - w*t - 4*w*u + w*v + 4*t^2 + 2*t*u - 2*t*v + 8*u*v + 5*v^2,
    y*v + 2*z*t + 2*z*u - 5*z*v - 2*w^2 - 2*w*t - 4*w*u + 2*w*v + 3*t^2 + t*u - t*v + 8*u*v + 3*v^2,
    3*z*t + 2*z*u - 8*z*v - 3*w^2 - 2*w*t - 4*w*u + 3*w*v + 4*t^2 + 2*t*u - t*v + u^2 + 9*u*v + 6*v^2
]) >;


// ---- N = 861,  [ <3, 1>, <7, 1>, <41, 1> ],  special points = 3 ----
models[861] := rec< ModelRec | N := 861, genus := 7, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + y*u - 2*z*u + 2*z*v - w^2 + 2*w*t + 3*w*u - w*v - 3*t*u + 4*t*v - 2*u^2 + 3*v^2,
    x*w - y*z + z*u + 4*z*v + w^2 - w*t + w*u + w*v - t^2 - 4*t*u + 2*t*v - 3*u^2 - u*v + 3*v^2,
    x*t - z^2 + 2*z*u + 2*z*v + w^2 - 2*w*t - 2*t*u - u^2 - u*v,
    x*u - z*w - z*v + t*u + u*v - v^2,
    x*v - z*u + z*v - 2*w*v + t*v + 2*u^2 - u*v - 2*v^2,
    y*w - z^2 + z*u - z*v - w*u - w*v + t^2 + t*u + u*v,
    y*t + y*u - z*w - 5*z*v - w^2 + w*t - 2*w*u + w*v + t^2 + 5*t*u - 4*t*v + 2*u^2 + u*v - 2*v^2,
    2*y*u - 2*z*u - z*v - 2*w^2 + 2*w*t - 3*w*v + t*u + 3*u^2 - u*v - 4*v^2,
    y*v - z*v - w*u + t*u - t*v + u^2 - 2*v^2,
    z*t - 2*z*u + 4*z*v - w^2 + 2*w*t + 2*w*u - 5*w*v - t^2 - 4*t*u + 4*t*v + 3*u^2 - u*v - 5*v^2
]) >;


// ---- N = 870,  [ <2, 1>, <3, 1>, <5, 1>, <29, 1> ],  special points = 8 ----
models[870] := rec< ModelRec | N := 870, genus := 7, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x*z - y^2 + y*v - z*v + w*u - w*v + t*u - t*v,
    x*w - y*z - 5*z*v + w*t + 2*w*u - 7*w*v + 2*t^2 - 2*t*v - 3*u^2 + 4*u*v + 7*v^2,
    x*t - z^2 + z*u + z*v - t*v,
    x*u - z*w - 3*z*v + 2*w*u - 4*w*v + t^2 - t*v - 3*u^2 + 2*u*v + 4*v^2,
    x*v + z*t - 2*z*u - 18*z*v - 2*w^2 + 3*w*t + 12*w*u - 20*w*v + 6*t^2 + 3*t*u - 9*t*v - 10*u^2 + 11*u*v + 22*v^2,
    y*w - z^2 - 2*z*u - 5*z*v + 2*w*t + 3*w*u - 8*w*v + 3*t^2 + t*u - 4*t*v - 3*u^2 + 6*u*v + 9*v^2,
    y*t - z*w + z*u + z*v - w*t + w*u + w*v - t^2 + t*v - u^2 - 2*u*v - v^2,
    y*u + y*v - 3*z*u - 10*z*v - w^2 + 2*w*t + 7*w*u - 12*w*v + 4*t^2 + 2*t*u - 6*t*v - 6*u^2 + 8*u*v + 14*v^2,
    2*y*v - z*u + 3*z*v - w*t + 2*w*v - t^2 + t*u + u^2 - 2*u*v - 3*v^2,
    2*z*t - 2*z*u - 17*z*v - 2*w^2 + 2*w*t + 12*w*u - 18*w*v + 5*t^2 + 3*t*u - 8*t*v - 10*u^2 + 10*u*v + 20*v^2
]) >;


// ---- N = 897,  [ <3, 1>, <13, 1>, <23, 1> ],  special points = 3 ----
models[897] := rec< ModelRec | N := 897, genus := 7, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + 2*z*v - 2*w*v - 3*t^2 + 4*t*u - 3*t*v + 2*v^2,
    x*w - y*z + 3*y*v + 3*z*u - z*v - 5*w*t + 3*w*u - w*v + t^2 - t*u + 3*t*v - u*v + 2*v^2,
    x*t + 3*y*v - z^2 + 2*z*u - 3*z*v - 5*w*t + 2*w*u + 2*w*v + 4*t^2 - 4*t*u + 7*t*v - u*v - v^2,
    x*u + 2*y*v - z*w - 2*w*t + w*u + w*v + 2*t^2 - t*u + 4*t*v - 2*u*v - v^2,
    x*v + 4*y*v + 2*z*u - z*v - w^2 - 5*w*t + 2*w*u + 2*w*v + 3*t^2 - 2*t*u + 5*t*v - u*v - v^2,
    y*w + 4*y*v - z^2 + 3*z*u - 2*z*v - 7*w*t + 3*w*u + w*v + 4*t^2 - 3*t*u + 8*t*v - u*v + v^2,
    y*t + 3*y*v - z*w + z*u - 3*z*v - 4*w*t + w*u + 2*w*v + 5*t^2 - 6*t*u + 7*t*v - v^2,
    y*u + 2*y*v + z*u - 3*z*v - w^2 - 3*w*t + 4*w*v + 5*t^2 - 6*t*u + 6*t*v - 3*v^2,
    5*y*v + 3*z*u - 4*z*v - 8*w*t + 3*w*u + 2*w*v + 6*t^2 - 6*t*u + 10*t*v - u*v,
    z*t - z*u + 2*z*v - w^2 + w*t - w*u + w*v - t^2 + t*u - 2*t*v - v^2
]) >;


// ==== special-points table (genus 7) ====
//   N : special points
//   193 : 11
//   229 : 9
//   233 : 7
//   241 : 8
//   257 : 6
//   281 : 8
//   298 : 11
//   309 : 11
//   326 : 9
//   358 : 9
//   365 : 6
//   411 : 7
//   437 : 3
//   445 : 6
//   446 : 7
//   474 : 11
//   478 : 5
//   498 : 10
//   501 : 5
//   518 : 8
//   519 : 5
//   527 : 2
//   530 : 11
//   582 : 9
//   623 : 3
//   638 : 7
//   646 : 4
//   658 : 6
//   671 : 4
//   710 : 4
//   861 : 3
//   870 : 8
//   897 : 3

