// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = 8.
// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical
// saturated-HNF star basis. Cusp forms not stored.
// All curves of this genus live in the single shared projective space P below.
//   models[N]`curve          : the curve X_0(N)^* in P
//   models[N]`special_points : number of special (CM + cusp) rational points

Q := Rationals();
P<x, y, z, w, t, u, v, s> := ProjectiveSpace(Q, 7);
ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, curve >;
models := AssociativeArray();


// ---- N = 293,  [ <293, 1> ],  special points = 5 ----
models[293] := rec< ModelRec | N := 293, genus := 8, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 3*w^2 - 6*w*t - 4*w*u - 13*w*v + 12*w*s + 2*t^2 + t*u - 9*t*v + 3*t*s - u^2 + 13*u*v - 36*u*s - 21*v^2 + 51*v*s - 54*s^2,
    x*w - y*z + 2*w^2 - w*t - 3*w*u - 2*w*v + 4*w*s - 3*t^2 + 5*t*u - 4*t*v + 2*t*s - 2*u^2 - u*v - 6*v^2 + 10*v*s - 4*s^2,
    x*t - z^2 + 2*w^2 + w*t - 3*w*u + 5*w*v - 4*w*s - 3*t^2 + 2*t*u - t*s + 4*u^2 - 4*u*v + 20*u*s + 7*v^2 - 15*v*s + 22*s^2,
    x*u - z*w + w^2 + w*t + 3*w*v - 2*t^2 + t*u - 2*t*v + 2*t*s - 2*u^2 - 3*u*v + 2*u*s - 2*v*s + 4*s^2,
    x*v - w*u - 3*w*v + 2*w*s - t*v - t*s - u^2 - 6*u*s - 5*v^2 + 8*v*s - 10*s^2,
    x*s - w*v + w*s - 2*t*s - u^2 - 4*u*s - 2*v^2 + 3*v*s - 6*s^2,
    y*w - z^2 + 2*w*t - 3*w*u + 5*w*v - 6*w*s - t^2 + t*u + 4*t*v - 2*t*s + 4*u^2 - 5*u*v + 21*u*s + 9*v^2 - 19*v*s + 24*s^2,
    y*t - z*w + 2*w*t + 2*w*u + 5*w*v - 2*w*s - 3*t^2 + t*u - 2*u^2 - 5*u*v + 8*u*s + 3*v^2 - 11*v*s + 12*s^2,
    y*u - w^2 + w*t + w*u + 3*w*v - 4*w*s - t*u + 2*t*v - u^2 - 3*u*v + 6*u*s + 5*v^2 - 13*v*s + 12*s^2,
    y*v - 3*w*v + 4*w*s - t*u - t*v - 2*t*s + u*v - 5*u*s - 3*v^2 + 7*v*s - 8*s^2,
    y*s - w*v + w*s - t*s + u*v - 3*u*s - v^2 + 3*v*s - 4*s^2,
    z*t - w^2 + w*u + 3*w*v - 6*w*s + t^2 - 2*t*u + t*v + t*s + 2*u^2 + 5*u*s + 6*v^2 - 12*v*s + 10*s^2,
    z*u - w*t - w*u + w*v - 4*w*s + 2*t^2 - 2*t*u + t*v + t*s + 2*u^2 + 2*u*s + 2*v^2 - 2*v*s + 2*s^2,
    z*v + w*u - 2*w*v + 4*w*s - t^2 + t*u - 2*t*v - 3*u^2 - 7*u*s - 5*v^2 + 7*v*s - 8*s^2,
    z*s + w*u - w*v + 3*w*s - t^2 + t*u - t*v - t*s - 2*u^2 - 4*u*s - 2*v^2 + 2*v*s - 4*s^2
]) >;


// ---- N = 346,  [ <2, 1>, <173, 1> ],  special points = 10 ----
models[346] := rec< ModelRec | N := 346, genus := 8, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + w*t - 7*w*u + 8*w*v - 8*w*s + t^2 - 5*t*u - 13*t*v + 11*u^2 - u*v + 15*u*s + 8*v^2 + 6*v*s - 10*s^2,
    x*w - y*z + 2*w*t - 3*w*u - 21*w*v + 23*w*s + 2*t^2 + 19*t*u - t*v - 26*t*s + 3*u^2 - 9*u*v - 34*u*s + 11*v^2 + 19*v*s + 13*s^2,
    x*t - z^2 - w*u - 18*w*v + 27*w*s + t^2 + 17*t*u + 4*t*v - 21*t*s + u^2 - 5*u*v - 43*u*s + 2*v^2 + 13*v*s + 12*s^2,
    x*u - z*w + w*t - 2*w*v + 6*w*s + t*u + t*v - 3*t*s - 2*u*v - 9*u*s + v*s + s^2,
    x*v - w^2 - w*u + 3*w*v - 2*w*s + t^2 - 3*t*u - 4*t*v + 4*t*s + 2*u^2 + 2*u*v + 2*u*s - 2*v^2 - v*s - 6*s^2,
    x*s - w*u + w*v - w*s - t*u + u^2 + u*v - v^2 - v*s - 3*s^2,
    y*w - z^2 + w*u - 19*w*v + 24*w*s + t^2 + 17*t*u + 8*t*v - 18*t*s - 3*u^2 - 5*u*v - 39*u*s + v^2 + 8*v*s + 16*s^2,
    y*t - z*w + w*u + 2*w*v - t^2 - 4*t*u + 2*t*v + 5*t*s - u^2 + 4*u*v + u*s - 4*v^2 - 5*v*s - 3*s^2,
    y*u - w^2 + 2*w*v - w*s + t^2 - 2*t*u - 2*t*v + 2*t*s - u^2 + u*v - v^2 + v*s - 4*s^2,
    y*v - w*t + w*u + 5*w*v - 6*w*s - t^2 - 5*t*u + 2*t*v + 8*t*s - u^2 + 2*u*v + 9*u*s - 5*v^2 - 7*v*s - 3*s^2,
    y*s + w*v - 2*w*s - 2*t*u + 2*t*s + 2*u*v + u*s - v^2 - 2*v*s - 2*s^2,
    z*t - w^2 + 7*w*v - 8*w*s - 7*t*u - 5*t*v + 6*t*s + u^2 + 3*u*v + 13*u*s - v*s - 7*s^2,
    z*u - w*t + w*u + 5*w*v - 5*w*s - t^2 - 4*t*u + 2*t*v + 6*t*s - u^2 + 6*u*s - 3*v^2 - 6*v*s - s^2,
    z*v - w*u + 3*w*v - 4*w*s - 3*t*u - 2*t*v + 3*t*s + u^2 + u*v + 7*u*s - v^2 - v*s - 3*s^2,
    z*s + 2*w*v - 3*w*s - 2*t*u - t*v + 2*t*s + u*v + 4*u*s - 2*v*s - 3*s^2
]) >;


// ---- N = 362,  [ <2, 1>, <181, 1> ],  special points = 9 ----
models[362] := rec< ModelRec | N := 362, genus := 8, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 - 26*z*v - w*u + 8*w*s + 34*t^2 - 10*t*u - 73*t*v - 41*t*s + 6*u^2 + 30*u*v - 8*u*s + 68*v^2 + 72*v*s + 2*s^2,
    x*w - y*z - 3*z*v - 3*w*u + w*s + 10*t^2 - 2*t*u - 24*t*v - 8*t*s + 5*u^2 + 4*u*v - 3*u*s + 17*v^2 + 15*v*s + 2*s^2,
    x*t - z^2 + 3*z*v + t^2 + 2*t*u - 10*t*v - t*s + 2*u^2 - 5*u*v - 7*u*s + 5*v^2 + 3*v*s + 6*s^2,
    x*u - z*w + z*v + 3*w*s + t^2 + 3*t*u - 5*t*v - 3*t*s - u^2 - 4*u*v - 6*u*s + 3*v^2 + 5*v*s + s^2,
    x*v - z*v - w^2 + 2*w*u + 3*w*s + t^2 + t*u - 5*t*v - t*s - 2*u*v - 7*u*s + 4*v^2 + 2*v*s + s^2,
    x*s - w*t + 2*w*s + t^2 + t*u - t*v - 2*t*s - u^2 + u*v - u*s - 4*s^2,
    y*w - z^2 + 11*z*v - 2*w*u - 4*w*s - 9*t^2 + 4*t*u + 16*t*v + 13*t*s + u^2 - 12*u*v + u*s - 19*v^2 - 22*v*s + 3*s^2,
    y*t - z*w + 4*z*v + 2*w*u - w*s - 6*t^2 + 4*t*u + 8*t*v + 4*t*s - u^2 - 9*u*v - 6*u*s - 6*v^2 - 7*v*s + 7*s^2,
    y*u + 3*z*v - w^2 + 2*w*u + 2*w*s - 5*t^2 + 2*t*u + 10*t*v + 5*t*s - 3*u^2 - 5*u*v - 4*u*s - 8*v^2 - 9*v*s - s^2,
    y*v + z*v - w*t + w*u - 2*t^2 + 2*t*u + 4*t*v + 3*t*s - u^2 - 4*u*v - 2*u*s - 3*v^2 - 5*v*s + s^2,
    y*s + 2*z*v - w*s - 3*t^2 + t*u + 6*t*v + 4*t*s - 3*u*v - u*s - 5*v^2 - 7*v*s - s^2,
    z*t - 2*z*v - w^2 + 2*w*u + 3*w*s - 2*t*v - 2*t*s - u^2 + u*v - 4*u*s + 4*v^2 + 3*v*s - s^2,
    z*u - z*v - w*t + 2*w*s + t^2 - 2*t*s - 2*u^2 + 2*u*v + u*s + 3*v*s - 4*s^2,
    z*s - t*u + t*v + u*v + u*s - v^2 - 2*v*s - 2*s^2,
    w*v - w*s - t*u + 2*t*s + u^2 - u*v - 3*v*s + s^2
]) >;


// ---- N = 381,  [ <3, 1>, <127, 1> ],  special points = 10 ----
models[381] := rec< ModelRec | N := 381, genus := 8, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + z*s + 2*w*u + 2*w*v + 6*w*s + 3*t^2 - 4*t*u - 19*t*v + 17*t*s - 6*u^2 + 2*u*v - u*s + 15*v^2 - 25*v*s - 3*s^2,
    x*w - y*z + z*s + w*u - w*v - 3*w*s + t^2 + t*u - 7*t*v + 2*t*s - 2*u*v - u*s + 10*v^2 - 4*v*s + 3*s^2,
    x*t - z^2 + 4*w*u + 2*w*v - 9*w*s - 2*t^2 + 2*t*u - 3*t*v + 2*t*s + 2*u^2 - 8*u*v - 5*u*s + 9*v^2 - 2*v*s + 12*s^2,
    x*u - z*w + 5*w*u + 3*w*v - 7*w*s - 3*t^2 + 5*t*v + 9*t*s - 2*u^2 - 7*u*v - 7*u*s - v^2 - 10*v*s + 11*s^2,
    x*v + z*s - w^2 - 2*w*u + 2*w*v + 8*w*s + 3*t^2 - t*u - 9*t*v - 6*t*s + u^2 + u*v + 2*u*s + 3*v^2 - v*s - 10*s^2,
    x*s - w*t - 2*w*u + 2*w*v + 3*w*s + 2*t^2 - 3*t*v - 5*t*s + u^2 + u*v + 2*u*s - 6*s^2,
    y*w - z^2 - w*v - 8*w*s + 3*t*u - 6*t*s + 4*u^2 - 4*u*v - u*s + 5*v^2 + 10*v*s + 7*s^2,
    y*t - z*w + 4*w*u + w*v - 7*w*s - 4*t^2 + t*u + 9*t*v + 2*t*s - 4*u*v - 5*u*s - 6*v^2 + 10*s^2,
    y*u + z*s - w^2 - w*u + 2*w*v + 6*w*s + t^2 - t*u - 3*t*v - 3*t*s - u*v - u*s + 2*v^2 - 2*v*s - 7*s^2,
    y*v - w*t - w*u + w*v + w*s + t^2 - 3*t*s + u^2 + u*s - 3*v^2 + 2*v*s - 2*s^2,
    y*s - 2*w*u + 2*w*s + t^2 - t*v - 5*t*s + u^2 + 2*u*v + 2*u*s - v^2 + 3*v*s - 5*s^2,
    z*t - w^2 - w*u + 2*w*v + 6*w*s + t^2 - 2*t*u - 4*t*v - 2*t*s + 2*u*v + 2*u*s - 3*v*s - 6*s^2,
    z*u - w*t - w*u + w*v + 3*w*s + t^2 - t*u - t*s - u^2 + u*v + u*s - 2*v^2 - 4*s^2,
    z*v - 3*w*u + 4*w*s + 2*t^2 - 4*t*v - 6*t*s + u^2 + 2*u*v + 4*u*s - v^2 + 5*v*s - 6*s^2,
    2*z*s - 3*w*u - w*v + 6*w*s + 3*t^2 - t*u - 7*t*v - 7*t*s + u^2 + 4*u*v + 2*u*s + 4*v^2 + 5*v*s - 10*s^2
]) >;


// ---- N = 383,  [ <383, 1> ],  special points = 3 ----
models[383] := rec< ModelRec | N := 383, genus := 8, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 - 13*z*s + 2*w*t - 4*w*v - 3*t^2 + 3*t*u + 9*t*v - 8*u^2 + 6*u*v + 4*u*s - 3*v^2 + 18*v*s + 7*s^2,
    x*w - y*z - 2*z*s + 2*w*t - 4*w*v - 2*w*s - t^2 + 3*t*v - t*s - 3*u^2 + 5*u*v - 2*u*s - v^2 + 9*v*s - s^2,
    x*t - z^2 + 4*z*s + w*t + w*s + 2*t^2 - 3*t*u - 7*t*v + 2*u^2 + 4*u*v - 6*u*s + 2*v^2 - 4*v*s - 2*s^2,
    x*u - z*w + z*s + w*t + w*v + w*s + t^2 - 2*t*u - 2*t*v - 3*u*s - v*s - s^2,
    x*v - 2*z*s - w^2 - w*v + 3*w*s + t^2 + 2*t*u - 2*t*v + 3*t*s - 2*u^2 + 2*u*v - 2*u*s - 2*v*s + 2*s^2,
    x*s - z*s - w*v + t*u - u^2 + u*v - u*s + v^2 - v*s,
    y*w - z^2 + 7*z*s - w*s + 2*t^2 - 3*t*u - 5*t*v - t*s + 4*u^2 - 4*u*s + 2*v^2 - 7*v*s - 4*s^2,
    y*t - z*w + 3*z*s + 2*w*v + w*s + t^2 - 2*t*u - 4*t*v + 2*u^2 - 2*u*s - 4*v*s - 2*s^2,
    y*u - z*s - w^2 + w*v + w*s + t^2 - t*v + t*s - 2*u^2 + u*v - 2*u*s + s^2,
    y*v + 2*z*s - w*t + w*s + t*u - t*v + t*s + u^2 - 3*u*v - 5*v*s - s^2,
    y*s + z*s - t*v + u^2 - u*v - u*s + v^2 - 3*v*s - s^2,
    z*t - 3*z*s - w^2 + 2*w*s + t*u + t*s - 2*u^2 + 2*u*v + 2*v*s + 2*s^2,
    z*u + z*s - w*t + w*v - 2*u*v - 2*v*s,
    z*v - 2*z*s - w*v - t^2 + t*u + 2*t*v - u^2 - u*v + 2*u*s - v^2 + 2*v*s + s^2,
    w*u - w*s - t^2 + 2*t*v - t*s - u^2 - u*v - v^2 + 2*v*s - s^2
]) >;


// ---- N = 403,  [ <13, 1>, <31, 1> ],  special points = 7 ----
models[403] := rec< ModelRec | N := 403, genus := 8, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 19*z*s + 2*w*t - 9*w*u + w*v + 2*w*s + 6*t^2 - 4*t*u - 9*t*v - 5*t*s + 9*u^2 - 15*u*v - 9*u*s + 18*v^2 - 55*v*s + 27*s^2,
    x*w - y*z + 20*z*s + 3*w*t - 8*w*u - w*v + 7*t^2 - 5*t*u - 11*t*v + t*s + 6*u^2 - 3*u*v - 14*u*s + 15*v^2 - 63*v*s + 33*s^2,
    x*t - z^2 + 12*z*s + w*t - 2*w*u - 2*w*v + 5*w*s + 4*t^2 - 2*t*u - 8*t*v - 5*t*s + 2*u^2 - 3*u*v - 7*u*s + 11*v^2 - 43*v*s + 27*s^2,
    x*u - z*w + 11*z*u + 11*z*s - 10*w*t - 2*w*u + w*v + 10*w*s + 3*t^2 + 7*t*u + 2*t*v - 34*t*s - 6*u^2 - 51*u*v + 13*u*s + 26*v^2 - 8*v*s,
    x*v + 3*z*s - w^2 + 2*w*u - 3*w*v + 5*w*s - t^2 + 3*t*u - 8*t*s - 2*u^2 - 4*u*v - u*s + 2*v^2 - 3*v*s + 4*s^2,
    x*s + 7*z*s - 2*w*u - w*v + 3*w*s + 2*t^2 - 3*t*v - 6*t*s + 2*u^2 - 5*u*v - 5*u*s + 7*v^2 - 21*v*s + 11*s^2,
    y*w - z^2 + z*u + 15*z*s - w*t - 3*w*u - 2*w*v + 6*w*s + 6*t^2 - 8*t*v - 10*t*s + 2*u^2 - 10*u*v - 6*u*s + 16*v^2 - 49*v*s + 31*s^2,
    y*t - z*w + z*u + 8*z*s - w*t - 2*w*v + 7*w*s + t^2 + 2*t*u - 3*t*v - 12*t*s - 10*u*v - 3*u*s + 9*v^2 - 19*v*s + 14*s^2,
    y*u + z*u + 11*z*s - w^2 - w*t - 3*w*v + 9*w*s + t^2 + 5*t*u - 3*t*v - 16*t*s - 3*u^2 - 14*u*v - 4*u*s + 12*v^2 - 21*v*s + 16*s^2,
    y*v + 6*z*s - w*t - w*u - 2*w*v + 5*w*s + t^2 + 3*t*u - 2*t*v - 8*t*s - 7*u*v - 3*u*s + 6*v^2 - 14*v*s + 9*s^2,
    y*s + 16*z*s - 4*w*u - 2*w*v + 7*w*s + 4*t^2 + 2*t*u - 7*t*v - 12*t*s + 2*u^2 - 11*u*v - 10*u*s + 15*v^2 - 42*v*s + 24*s^2,
    z*t + 11*z*u + 11*z*s - w^2 - 11*w*t - w*u + w*v + 11*w*s + t^2 + 11*t*u + 3*t*v - 39*t*s - 8*u^2 - 53*u*v + 16*u*s + 25*v^2 + 3*v*s - 5*s^2,
    2*z*u + 18*z*s - 2*w*t - 5*w*u - w*v + 8*w*s + 5*t^2 + 3*t*u - 7*t*v - 17*t*s + 2*u^2 - 21*u*v - 6*u*s + 20*v^2 - 44*v*s + 25*s^2,
    z*v + 21*z*s - 6*w*u - 3*w*v + 10*w*s + 5*t^2 + 3*t*u - 9*t*v - 16*t*s + 4*u^2 - 17*u*v - 12*u*s + 20*v^2 - 55*v*s + 33*s^2,
    22*z*s - 6*w*u - 2*w*v + 9*w*s + 6*t^2 + 2*t*u - 10*t*v - 15*t*s + 4*u^2 - 16*u*v - 12*u*s + 21*v^2 - 59*v*s + 35*s^2
]) >;


// ---- N = 415,  [ <5, 1>, <83, 1> ],  special points = 6 ----
models[415] := rec< ModelRec | N := 415, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 2*w*t - 11*w*u + w*v + 46*w*s + 10*t^2 - 5*t*u - 30*t*v + t*s + 22*u^2 - 3*u*v - 15*u*s + 16*v^2 + 30*v*s - 127*s^2,
    x*w - y*z + z*v + 2*w*t - 4*w*u - 2*w*v + 10*w*s + 2*t^2 - 3*t*u - 9*t*v + 3*t*s + 5*u^2 + 7*u*v - 10*u*s + v^2 + 20*v*s - 41*s^2,
    x*t - z^2 + 3*z*u + z*v - 3*w*t + 5*w*u - 2*w*v - 13*w*s - 4*t^2 + 2*t*u + 13*t*v - 4*t*s - 10*u^2 - 2*u*v + 6*u*s - 4*v^2 - 22*v*s + 56*s^2,
    x*u - z*w + 2*z*u + z*v - w*t - w*v + 2*w*s + t*u + 2*t*v - 2*t*s - 2*u^2 - 5*u*v + 2*u*s + 2*v^2 - 14*v*s + 14*s^2,
    x*v + z*u + z*v - w^2 - w*t - 2*w*u - w*v + 12*w*s + 2*t^2 + 2*t*u - 6*t*v + t*s + 2*u^2 - 4*u*v - u*s + 5*v^2 - 12*v*s - 11*s^2,
    x*s + 3*z*u + z*v - 3*w*t - 2*w*u - w*v + 6*w*s + t^2 + 4*t*u + t*v - 4*t*s - 10*u*v + 7*u*s + 6*v^2 - 24*v*s + 11*s^2,
    y*w - z^2 + z*v + 4*w*u - 3*w*v - 14*w*s - 3*t^2 + 8*t*v + t*s - 7*u^2 + 4*u*v + u*s - 5*v^2 - 3*v*s + 34*s^2,
    y*t - z*w + z*u + 2*z*v - w*t - 3*w*u - w*v + 7*w*s + t^2 + 2*t*u - 5*t*v + 3*u^2 - 7*u*v + 8*u*s + 7*v^2 - 18*v*s + 3*s^2,
    y*u + 3*z*u + z*v - w^2 - 3*w*t + 2*w*s + 4*t*u + 4*t*v - 3*t*s - 4*u^2 - 10*u*v + 7*u*s + 4*v^2 - 28*v*s + 27*s^2,
    y*v + z*u + 2*z*v - 2*w*t - 4*w*u - 2*w*v + 10*w*s + 2*t^2 + 4*t*u - 5*t*v + 4*u^2 - 10*u*v + 8*u*s + 8*v^2 - 21*v*s - 2*s^2,
    y*s + z*u + z*v - w*t - 2*w*u - w*v + 5*w*s + t^2 + 2*t*u - 2*t*v - t*s + 2*u^2 - 6*u*v + 4*u*s + 5*v^2 - 13*v*s,
    z*t + 3*z*u + z*v - w^2 - 3*w*t - 3*w*u + 12*w*s + 2*t^2 + 3*t*u - 3*t*v - 2*t*s + 2*u^2 - 11*u*v + 6*u*s + 9*v^2 - 26*v*s + 2*s^2,
    4*z*u + z*v - 4*w*t - w*u - w*v + 2*w*s + 5*t*u + 6*t*v - 6*t*s - 2*u^2 - 13*u*v + 12*u*s + 5*v^2 - 31*v*s + 30*s^2,
    2*z*v - 6*w*u - w*v + 18*w*s + 4*t^2 + t*u - 13*t*v + 2*t*s + 9*u^2 - 6*u*v + u*s + 10*v^2 - 3*v*s - 38*s^2,
    z*s - w*u + 4*w*s + t^2 - 3*t*v + 2*u^2 - u*v - u*s + 2*v^2 + v*s - 11*s^2
]) >;


// ---- N = 427,  [ <7, 1>, <61, 1> ],  special points = 6 ----
models[427] := rec< ModelRec | N := 427, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 6*z*s + 4*w*u - 8*w*v - w*s - t^2 - 4*t*u - 4*t*v + 12*t*s + 7*u^2 - 7*u*v - 11*u*s + 16*v^2 + 7*v*s - 4*s^2,
    x*w - y*z + z*v + 2*w*u - w*v - w*s + 2*t*u - t*v - 5*t*s - 4*u^2 + 4*u*v - 4*u*s - 4*v^2 + 5*v*s + s^2,
    x*t - z^2 + z*v + w*u + w*v + t*u - 2*t*v - 5*t*s - 2*u^2 + u*v - u*s - v^2 - v*s + 2*s^2,
    x*u - z*w + 3*z*s + w*u - t*u + t*s - 2*u*v - 4*u*s + 2*v^2 - 2*v*s - s^2,
    x*v + 2*z*v + 4*z*s - w^2 + w*v + w*s - t^2 - 4*t*u + 7*t*s + 6*u^2 - 5*u*v - 3*u*s + v^2 - 10*v*s - 4*s^2,
    x*s + 6*z*s - w*t + 2*w*u - w*v - 5*w*s - t^2 - 4*t*u + 4*t*v + 10*t*s + 8*u^2 - 10*u*v - 6*u*s + 7*v^2 - 11*v*s + 2*s^2,
    y*w - z^2 + 2*z*v + 2*z*s - 2*w*u + 4*w*v - 7*w*s - 3*t*u + 3*t*v + 3*t*s + 6*u^2 - 5*u*v + 4*u*s - 2*v^2 - 15*v*s + 8*s^2,
    y*t - z*w + z*v + 4*z*s + w*v - 2*w*s - t^2 - 3*t*u + 2*t*v + 2*t*s + 4*u^2 - 4*u*v + v^2 - 7*v*s + s^2,
    y*u + 2*z*s - w^2 + 3*w*s - t*u + 2*t*s + u^2 - 3*u*v - 3*u*s + 3*v^2 - 3*v*s - 4*s^2,
    y*v + z*v + 5*z*s - w*t - 4*w*s - t^2 - 4*t*u + 3*t*v + 10*t*s + 8*u^2 - 9*u*v - 2*u*s + 4*v^2 - 12*v*s + 2*s^2,
    y*s + z*v + 4*z*s - w*u + 2*w*v - 5*w*s - t^2 - 5*t*u + 3*t*v + 8*t*s + 8*u^2 - 6*u*v + 2*v^2 - 13*v*s + 2*s^2,
    z*t - w^2 + 2*w*v + 4*w*s - 2*t*u - 2*t*v + 2*u*v - u*s - v^2 - 2*v*s - 5*s^2,
    z*u + 2*z*v + 2*z*s - w*t - w*u + w*v - w*s - t^2 - 3*t*u + 2*t*v + 7*t*s + 4*u^2 - 4*u*v - v^2 - 6*v*s - 2*s^2,
    3*z*v + 2*z*s - 2*w*u + 2*w*v - 2*w*s - t^2 - 4*t*u + t*v + 6*t*s + 6*u^2 - 3*u*v + 2*u*s - 2*v^2 - 8*v*s - s^2,
    7*z*s + w*u - 2*w*v - 6*w*s - t^2 - 5*t*u + 3*t*v + 11*t*s + 10*u^2 - 11*u*v - 4*u*s + 10*v^2 - 10*v*s + 4*s^2
]) >;


// ---- N = 431,  [ <431, 1> ],  special points = 5 ----
models[431] := rec< ModelRec | N := 431, genus := 8, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + z*v + w^2 - 2*w*t + 7*w*s + 4*t^2 - 4*t*u + 4*t*v - 7*t*s + 3*u^2 - 11*u*v + 4*u*s + 11*v^2 - 15*v*s + s^2,
    x*w - y*z + 4*z*v + w^2 - w*t - 6*w*v + 9*w*s - 2*t*u + 7*t*v - 6*t*s + 2*u^2 - 10*u*v + 2*u*s + 11*v^2 - 18*v*s + 6*s^2,
    x*t - z^2 + 4*z*v + w^2 - 6*w*v + 6*w*s - t^2 - 2*t*u + 4*t*v - 5*t*s + 2*u^2 - 5*u*v + 2*u*s + 4*v^2 - 8*v*s + 2*s^2,
    x*u - z*w + w*s + 2*t*v - 2*t*s - u^2 + u*v - 2*v^2,
    x*v - z*v - w*t + t*u + t*v - t*s - u^2 + 2*u*v - 2*v^2 - v*s + s^2,
    x*s - w*v + w*s + t*v - 2*t*s - u*s + v^2 - 2*v*s,
    y*w - z^2 + 3*z*v + w*t - 6*w*v + 3*w*s - 2*t^2 + 4*t*v - 3*t*s - u*v + u*s + 2*v^2 - 6*v*s + 5*s^2,
    y*t - z*w + z*v + w*t - w*v + w*s - t^2 - t*v - 2*t*s + u*v - v^2 + s^2,
    y*u - 2*z*v - w^2 + 3*w*v - 6*w*s + t*u - 2*t*v + 3*t*s - 2*u^2 + 6*u*v - 8*v^2 + 11*v*s - 4*s^2,
    y*v - z*v - w*s - t^2 + t*u + t*s - u^2 + 2*u*v - u*s - 2*v^2 + v*s + s^2,
    y*s - w*s - t*v + t*s + u*v - u*s - v^2 + v*s - 2*s^2,
    z*t - z*v - w^2 + 4*w*v - 6*w*s + t^2 - t*u - 4*t*v + 3*t*s + 4*u*v + 2*u*s - 7*v^2 + 9*v*s - 6*s^2,
    z*u - 2*z*v - w*t + 2*w*v - 2*w*s + t*u + t*s - 2*u^2 + 3*u*v - u*s - 2*v^2 + 3*v*s,
    z*s + w*s - t*s - u*v - u*s + 2*v^2 - 3*v*s + s^2,
    w*u - w*v + 2*w*s - t^2 + 2*t*v - t*s - u^2 - u*v - u*s + 3*v^2 - 5*v*s + 4*s^2
]) >;


// ---- N = 479,  [ <479, 1> ],  special points = 4 ----
models[479] := rec< ModelRec | N := 479, genus := 8, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + 2*w*t - 10*w*u - w*v - 4*w*s + 4*t^2 + 5*t*u - 11*t*v - 9*t*s + u^2 + 8*u*v + u*s + v^2 + 16*v*s + 4*s^2,
    x*w - y*z + 2*w*t - 4*w*u - 4*w*v - 3*w*s + 2*t^2 + 2*t*u - 3*t*v - 4*t*s + 6*u*v - 2*u*s + 10*v*s + 3*s^2,
    x*t - z^2 + w*t + w*u - 2*w*v + 2*w*s - t^2 - t*u + 2*t*v - t*s + u*v - 3*u*s + v*s,
    x*u - z*w + w*t + w*s - t*u - u*v - 2*u*s + v*s - s^2,
    x*v - w^2 + w*t - w*u - w*v + t^2 + t*u - 4*t*v - t*s + u*v - u*s + 4*v*s - s^2,
    x*s - w*u - t*s + u*v - v*s - s^2,
    y*w - z^2 + 3*w*u - 2*w*v + 2*w*s - t^2 - 2*t*u + 5*t*v + 2*t*s - 2*u*v - 2*u*s - 3*v*s - s^2,
    y*t - z*w + 2*w*u + 2*w*s - t^2 - 2*t*u + t*v + 2*t*s - u*v - u*s - 2*v*s - 3*s^2,
    y*u - w^2 + 2*w*u + w*v + w*s - t^2 - t*u + t*v + 2*t*s - u^2 - 2*u*v - 3*v*s - 2*s^2,
    y*v - w*t + 2*w*u + w*v + w*s - t^2 - t*u + 2*t*v + 2*t*s - 3*u*v + u*s - v^2 - 5*v*s - s^2,
    y*s - t*u - v*s - s^2,
    z*t - w^2 + w*v - 3*t*v + 2*v*s - 2*s^2,
    z*u - w*t + w*u + 2*w*v + w*s - t^2 - t*u + 2*t*v + t*s - 3*u*v + u*s - 5*v*s,
    z*v - w*u + t*u - t*v - t*s + u*s + s^2,
    z*s - w*u - w*s + t^2 - 2*t*v - t*s + u*v + 2*v*s - s^2
]) >;


// ---- N = 505,  [ <5, 1>, <101, 1> ],  special points = 6 ----
models[505] := rec< ModelRec | N := 505, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 3*w*t + 4*w*u - 11*w*v - w*s - 8*t^2 + 11*t*u + 18*t*v + 10*t*s - 18*u^2 - 3*u*v + 2*u*s + 7*v^2 + 2*v*s - 15*s^2,
    x*w - y*z + 2*w*t - 4*w*u + w*v - 3*w*s + 2*t^2 - 6*t*u - 5*t*v - 10*t*s + 8*u^2 + 2*u*v + 4*u*s - 4*v^2 + 4*v*s + 11*s^2,
    x*t - z^2 + 2*w*t - 4*w*u + 6*w*v - w*s + 5*t^2 - 12*t*u - 14*t*v - 18*t*s + 16*u^2 + 4*u*v + u*s - 7*v^2 + 4*v*s + 18*s^2,
    x*u - z*w + w*t + w*u - w*s - 2*t*u - t*s - u^2 - 2*u*s - v^2 + v*s + 3*s^2,
    x*v - w^2 + w*t + 3*w*u - 3*w*v + 2*w*s - 2*t^2 + 3*t*u + 4*t*v + 3*t*s - 6*u^2 - u*v - 2*u*s + 2*v^2 - v*s - 6*s^2,
    x*s - w*u + 2*w*v + t^2 - 2*t*u - 3*t*v - 3*t*s + 3*u^2 - v^2 - v*s + s^2,
    y*w - z^2 - 9*w*u + 13*w*v + 11*t^2 - 18*t*u - 26*t*v - 24*t*s + 29*u^2 + 6*u*v + 2*u*s - 11*v^2 + 2*v*s + 26*s^2,
    y*t - z*w + 2*w*u - 2*w*s - t*u - t*v + t*s - u^2 + u*v - 2*u*s - v^2 + 3*s^2,
    y*u - w^2 + 3*w*v + 4*w*s + t^2 - 2*t*u - 3*t*v - 2*t*s + 2*u^2 - u*s - 2*v*s - 2*s^2,
    y*v - w*t + w*u + t*u + 2*t*s - u^2 - u*v - 2*u*s - v*s - s^2,
    y*s - w*u + w*v + t^2 - t*u - 2*t*v - 2*t*s + 2*u^2 - v^2 - v*s + s^2,
    z*t - w^2 + 3*w*u - 2*w*v + 3*w*s - 3*t^2 + 4*t*u + 5*t*v + 6*t*s - 7*u^2 - u*v - u*s + 4*v^2 - 2*v*s - 10*s^2,
    z*u - w*t - w*u + 2*w*v + 2*w*s + t^2 - t*u - 2*t*v - t*s + 2*u^2 - u*v - v*s - s^2,
    z*v + 2*w*u - 4*w*v - w*s - 3*t^2 + 5*t*u + 7*t*v + 7*t*s - 8*u^2 - 2*u*v + 2*v^2 - v*s - 6*s^2,
    z*s - 2*w*u + 3*w*v + w*s + 2*t^2 - 3*t*u - 5*t*v - 5*t*s + 6*u^2 + u*v - 2*v^2 - v*s + 3*s^2
]) >;


// ---- N = 511,  [ <7, 1>, <73, 1> ],  special points = 7 ----
models[511] := rec< ModelRec | N := 511, genus := 8, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + y*v + z*s - w*t - 10*w*u - 6*w*v - 5*w*s + 9*t^2 + 8*t*u - 5*t*v - t*s + 5*u^2 + 16*u*v - 20*u*s - v^2 + 9*v*s - 5*s^2,
    x*w - y*z + 8*w*u + 10*w*v - 2*w*s - 8*t^2 - 6*t*u + 5*t*v - t*s - 4*u^2 - 17*u*v + 21*u*s - 12*v*s + 9*s^2,
    x*t - z^2 + z*t + 3*z*v + 6*z*s - w^2 - 25*w*u - 22*w*v - 5*w*s + 22*t^2 + 19*t*u - 13*t*v - 4*t*s + 13*u^2 + 44*u*v - 54*u*s - 2*v^2 + 26*v*s - 20*s^2,
    x*u + y*u + y*v - z*w + z*v + 5*z*s - w^2 - w*t - 21*w*u - 20*w*v - w*s + 20*t^2 + 15*t*u - 11*t*v - t*s + 10*u^2 + 38*u*v - 49*u*s - v^2 + 24*v*s - 20*s^2,
    x*v + y*u + y*v + z*v + 3*z*s - 2*w^2 - w*t - 16*w*u - 15*w*v + 2*w*s + 14*t^2 + 13*t*u - 8*t*v - t*s + 8*u^2 + 26*u*v - 35*u*s - 2*v^2 + 16*v*s - 16*s^2,
    x*s + 3*z*v + 3*z*s - w*t - 24*w*u - 19*w*v - 6*w*s + 20*t^2 + 18*t*u - 10*t*v - 2*t*s + 12*u^2 + 39*u*v - 47*u*s - 3*v^2 + 23*v*s - 17*s^2,
    y*w + y*v - z^2 + z*s - w*t + 4*w*u + 7*w*s - 4*t^2 - 2*t*u + t*v + 2*t*s - 2*u^2 - 9*u*v + 9*u*s + v^2 - 5*v*s - 3*s^2,
    y*t + y*u + y*v - z*w + z*v + 3*z*s - w^2 - w*t - 14*w*u - 15*w*v + 3*w*s + 13*t^2 + 11*t*u - 8*t*v - t*s + 7*u^2 + 25*u*v - 33*u*s - v^2 + 17*v*s - 16*s^2,
    y*u + y*v + z*t + 4*z*v + 10*z*s - 2*w^2 - w*t - 56*w*u - 52*w*v - 11*w*s + 52*t^2 + 41*t*u - 28*t*v - 5*t*s + 28*u^2 + 103*u*v - 125*u*s - 4*v^2 + 64*v*s - 45*s^2,
    y*v + 2*z*v + 4*z*s - w*t - 24*w*u - 23*w*v - 4*w*s + 22*t^2 + 18*t*u - 12*t*v - t*s + 12*u^2 + 43*u*v - 52*u*s - 2*v^2 + 27*v*s - 20*s^2,
    y*s + 3*z*v + 6*z*s - 36*w*u - 33*w*v - 9*w*s + 32*t^2 + 26*t*u - 16*t*v - 3*t*s + 18*u^2 + 65*u*v - 77*u*s - 3*v^2 + 39*v*s - 27*s^2,
    2*z*t + 3*z*v + 5*z*s - 2*w^2 - 35*w*u - 31*w*v - 8*w*s + 32*t^2 + 26*t*u - 18*t*v - 4*t*s + 18*u^2 + 65*u*v - 79*u*s - 3*v^2 + 40*v*s - 26*s^2,
    z*u + 3*z*v + 3*z*s - w*t - 23*w*u - 19*w*v - 7*w*s + 20*t^2 + 16*t*u - 10*t*v - t*s + 11*u^2 + 40*u*v - 48*u*s - 3*v^2 + 24*v*s - 15*s^2,
    4*z*v + 3*z*s - 28*w*u - 23*w*v - 9*w*s + 24*t^2 + 20*t*u - 12*t*v - 2*t*s + 14*u^2 + 48*u*v - 56*u*s - 4*v^2 + 29*v*s - 17*s^2,
    4*z*s - 14*w*u - 14*w*v - 4*w*s + 14*t^2 + 10*t*u - 7*t*v - 2*t*s + 7*u^2 + 28*u*v - 33*u*s + 17*v*s - 12*s^2
]) >;


// ---- N = 534,  [ <2, 1>, <3, 1>, <89, 1> ],  special points = 11 ----
models[534] := rec< ModelRec | N := 534, genus := 8, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + 2*z*s + w*u + w*v + t^2 - 4*t*u - 4*t*v + 3*t*s + u^2 - u*v + 2*u*s - v*s - s^2,
    x*w - y*z + 5*z*s - 3*w*u - 2*w*v + 4*t^2 - 2*t*u - 3*t*v + 2*u^2 - 2*u*v + 3*u*s - v^2 - 4*s^2,
    x*t - z^2 + 6*z*s - 5*w*u - 2*w*v + 6*t^2 - 3*t*u - 6*t*v + 4*u^2 - u*v + 3*u*s - v^2 - 5*s^2,
    x*u - z*w + 6*z*s - 6*w*u - 2*w*v + w*s + 7*t^2 - 3*t*u - 5*t*v + 2*t*s + 4*u^2 - 5*u*v + 5*u*s - 3*v^2 + v*s - 6*s^2,
    x*v + 5*z*s - w^2 - 5*w*u - 3*w*v + 2*w*s + 5*t^2 - 2*t*u - 4*t*v + 2*t*s + 4*u^2 - 4*u*v + 5*u*s - 3*v^2 - v*s - 5*s^2,
    x*s + 7*z*s - w*t - 8*w*u - 3*w*v + 8*t^2 - 3*t*u - 6*t*v + 3*t*s + 6*u^2 - 5*u*v + 8*u*s - 3*v^2 - v*s - 7*s^2,
    y*w - z^2 + 4*z*s - 5*w*u - 2*w*v - w*s + 5*t^2 - t*u - 3*t*v + 3*u^2 - u*v + 3*u*s - v^2 - 3*s^2,
    y*t - z*w + 6*z*s - 6*w*u - 2*w*v + w*s + 6*t^2 - 3*t*u - 5*t*v + t*s + 4*u^2 - 4*u*v + 6*u*s - 3*v^2 + v*s - 6*s^2,
    y*u + 3*z*s - w^2 - 4*w*u - 2*w*v + 2*w*s + 4*t^2 - 3*t*v + 2*t*s + 2*u^2 - 4*u*v + 3*u*s - v^2 - v*s - 3*s^2,
    y*v + 3*z*s - w*t - 4*w*u - 2*w*v + 4*t^2 - t*u - 3*t*v + 2*t*s + 3*u^2 - 2*u*v + 3*u*s - 2*v^2 - 3*s^2,
    y*s + z*s - 2*w*u - w*v + t^2 + u^2 - u*v + u*s - v^2 - 2*s^2,
    z*t + 5*z*s - w^2 - 5*w*u - 3*w*v + 2*w*s + 5*t^2 - 2*t*u - 5*t*v + 3*t*s + 4*u^2 - 4*u*v + 5*u*s - 2*v^2 - 5*s^2,
    z*u + 3*z*s - w*t - 4*w*u - 2*w*v + 4*t^2 - t*u - 2*t*v + 2*t*s + 3*u^2 - 3*u*v + 4*u*s - 2*v^2 + v*s - 3*s^2,
    z*v + 2*z*s - 3*w*u - w*v + 2*t^2 - t*u - 2*t*v + 2*t*s + 2*u^2 - 3*u*v + 4*u*s - 2*v^2 - 2*s^2,
    8*z*s - 9*w*u - 4*w*v + 9*t^2 - 4*t*u - 7*t*v + 4*t*s + 7*u^2 - 5*u*v + 9*u*s - 4*v^2 + 2*v*s - 8*s^2
]) >;


// ---- N = 545,  [ <5, 1>, <109, 1> ],  special points = 6 ----
models[545] := rec< ModelRec | N := 545, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + z*s - 3*w*v + 2*w*s + 2*t^2 - 3*t*u + t*v - 3*t*s + 2*u^2 - 3*u*v + 4*u*s + 2*v^2 - v*s + s^2,
    x*w - y*z + 6*z*s - w*v - 4*w*s + 2*t^2 - 6*t*u + 5*t*v - 8*t*s + 2*u^2 + 4*u*v - 5*u*s - 6*v^2 + 6*v*s + 6*s^2,
    x*t - z^2 + 3*z*s + 2*w*v - 2*w*s + t^2 - 4*t*u + 2*t*v - 6*t*s + u^2 + 3*u*v - 4*u*s - 4*v^2 + 4*v*s + 4*s^2,
    x*u - z*w - 2*z*s + 3*w*v + 2*t^2 - t*u - 3*t*v + t*s - 2*u*v - 2*u*s + 4*v*s,
    x*v - z*s - w^2 + 2*w*v + t^2 - t*u - t*v - t*s + u^2 - 2*u*v - u*s - v^2 + 2*v*s + s^2,
    x*s - 2*z*s - w*t + w*v + w*s + t^2 + t*u - 3*t*v + 3*t*s - 2*u*v + 2*v^2 - v*s - 2*s^2,
    y*w - z^2 + 4*z*s + w*v - 4*w*s - 3*t*u + 5*t*v - 7*t*s + 6*u*v - 5*u*s - 6*v^2 + 4*v*s + 5*s^2,
    y*t - z*w - 3*z*s + 3*w*v + w*s + t*u - 4*t*v + 3*t*s - u^2 + v^2 + v*s - 2*s^2,
    y*u - 5*z*s - w^2 + 3*w*v + 2*w*s + 4*t*u - 5*t*v + 5*t*s - 2*u^2 - 3*u*v + u*s + 4*v^2 - 2*v*s - 3*s^2,
    y*v - 3*z*s - w*t + w*v + 2*w*s + 3*t*u - 4*t*v + 5*t*s - u^2 - 2*u*v + u*s + 2*v^2 - 2*v*s - 3*s^2,
    y*s + z*s - w*s - t^2 + 2*t*v - 2*t*s + u*v - u*s - v^2 - v*s,
    z*t - 3*z*s - w^2 + 2*w*v + w*s + t*u - 3*t*v + 2*t*s - 2*u*v + u*s + 2*v^2 - s^2,
    z*u - 6*z*s - w*t + w*v + 4*w*s + 5*t*u - 6*t*v + 8*t*s - 2*u^2 - 4*u*v + 4*u*s + 6*v^2 - 4*v*s - 6*s^2,
    z*v - 2*z*s - w*v + 2*w*s - t^2 + 3*t*u - 2*t*v + 3*t*s - u^2 - 2*u*v + 3*u*s + 3*v^2 - 4*v*s - 3*s^2,
    w*u - w*s - t^2 + 2*t*v - t*s - u^2 + 2*u*v - v^2 - v*s + s^2
]) >;


// ---- N = 559,  [ <13, 1>, <43, 1> ],  special points = 6 ----
models[559] := rec< ModelRec | N := 559, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 - 14*w*u + 45*w*v - 5*w*s + 15*t^2 - 43*t*u - 16*t*v - 5*t*s + 13*u^2 + 7*u*v + 51*u*s + v^2 - 59*v*s + 6*s^2,
    x*w - y*z + z*v - 48*w*u + 136*w*v - 14*w*s + 48*t^2 - 135*t*u - 32*t*v - 36*t*s + 43*u^2 + 32*u*v + 151*u*s - 31*v^2 - 140*v*s + 13*s^2,
    x*t - z^2 - 111*w*u + 317*w*v - 28*w*s + 111*t^2 - 314*t*u - 73*t*v - 85*t*s + 100*u^2 + 76*u*v + 347*u*s - 73*v^2 - 323*v*s + 28*s^2,
    x*u - z*w - 74*w*u + 211*w*v - 17*w*s + 74*t^2 - 208*t*u - 49*t*v - 55*t*s + 65*u^2 + 52*u*v + 228*u*s - 50*v^2 - 213*v*s + 17*s^2,
    x*v + z*v - w^2 + 9*w*u - 26*w*v + 5*w*s - 10*t^2 + 28*t*u + 5*t*v + 8*t*s - 9*u^2 - 9*u*v - 28*u*s + 6*v^2 + 24*v*s - 4*s^2,
    x*s - w*t + 2*w*u - 5*w*v + w*s - 2*t^2 + 6*t*u + 2*t*v + t*s - 2*u^2 - 2*u*v - 6*u*s + 6*v*s - 2*s^2,
    y*w - z^2 + z*v - 16*w*u + 43*w*v - 6*w*s + 15*t^2 - 42*t*u - 8*t*v - 13*t*s + 14*u^2 + 10*u*v + 47*u*s - 12*v^2 - 42*v*s + 5*s^2,
    y*t - z*w + z*v + 17*w*u - 50*w*v + 6*w*s - 18*t^2 + 50*t*u + 12*t*v + 11*t*s - 16*u^2 - 11*u*v - 56*u*s + 8*v^2 + 56*v*s - 6*s^2,
    y*u - w^2 - 16*w*u + 45*w*v - w*s + 16*t^2 - 45*t*u - 10*t*v - 12*t*s + 14*u^2 + 10*u*v + 48*u*s - 11*v^2 - 45*v*s + 2*s^2,
    y*v + z*v - w*t + 37*w*u - 107*w*v + 11*w*s - 38*t^2 + 107*t*u + 25*t*v + 29*t*s - 34*u^2 - 26*u*v - 118*u*s + 22*v^2 + 110*v*s - 11*s^2,
    y*s + 36*w*u - 104*w*v + 9*w*s - 37*t^2 + 104*t*u + 25*t*v + 26*t*s - 33*u^2 - 25*u*v - 114*u*s + 22*v^2 + 108*v*s - 10*s^2,
    z*t - w^2 + 29*w*u - 81*w*v + 9*w*s - 29*t^2 + 81*t*u + 17*t*v + 22*t*s - 26*u^2 - 21*u*v - 88*u*s + 20*v^2 + 81*v*s - 8*s^2,
    z*u + z*v - w*t + 63*w*u - 180*w*v + 17*w*s - 64*t^2 + 180*t*u + 41*t*v + 49*t*s - 58*u^2 - 44*u*v - 198*u*s + 41*v^2 + 184*v*s - 17*s^2,
    2*z*v + 79*w*u - 227*w*v + 20*w*s - 81*t^2 + 227*t*u + 52*t*v + 61*t*s - 72*u^2 - 57*u*v - 248*u*s + 53*v^2 + 230*v*s - 20*s^2,
    z*s + 35*w*u - 99*w*v + 8*w*s - 35*t^2 + 98*t*u + 23*t*v + 26*t*s - 31*u^2 - 25*u*v - 108*u*s + 24*v^2 + 99*v*s - 8*s^2
]) >;


// ---- N = 573,  [ <3, 1>, <191, 1> ],  special points = 4 ----
models[573] := rec< ModelRec | N := 573, genus := 8, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + w*t + 2*w*u - 2*w*v - 2*w*s - 4*t^2 + 4*t*u + 3*t*v + 10*t*s - 3*u^2 + u*v - 4*u*s - v*s - 4*s^2,
    x*w - y*z + z*t - w^2 + w*t - w*u - t*u - t*v - 3*t*s - u^2 + 2*u*v + u*s - 2*v^2 + 5*v*s + s^2,
    x*t - z^2 + z*t - w^2 + w*t + w*u - w*v - t^2 + t*u - 2*t*v - 2*u^2 + u*v - 4*u*s + 3*v*s - 2*s^2,
    x*u - z*w + w*t - w*u + w*v + t^2 - t*u - t*v - 4*t*s - u*v + u*s - v^2 + 2*v*s + 3*s^2,
    x*v - w^2 + 2*w*s + t*u - t*v - u^2 + u*v - 3*u*s - 2*v^2 + 2*v*s - s^2,
    x*s + z*t - w^2 + 2*w*u - w*v + w*s - 2*t^2 + 2*t*u + t*v + 4*t*s - 2*u^2 - 5*u*s - v*s - 4*s^2,
    y*w - z^2 + z*t - w^2 + w*u - w*v - t*s - u^2 - 2*u*s + v*s,
    y*t - z*w + z*t - w^2 + 2*w*u - t^2 - 2*u*v - u*s + v^2 - 2*v*s,
    y*u - w^2 + w*u + w*v + w*s - t*u + t*v - 2*t*s - u^2 - u*v - v^2 + 2*s^2,
    y*v + z*t - w^2 - w*t + 2*w*u - w*v + 2*w*s - 2*t^2 + 2*t*u + t*v + 6*t*s - u^2 - u*v - 6*u*s - 2*v*s - 5*s^2,
    y*s + z*t - w^2 + 2*w*u - w*v - 2*t^2 + 2*t*u + t*v + 5*t*s - u^2 - u*v - 5*u*s + v^2 - 2*v*s - 5*s^2,
    2*z*t - 2*w^2 + 4*w*u - w*v + w*s - 4*t^2 + 3*t*u + 3*t*v + 8*t*s - 3*u^2 - u*v - 7*u*s - 2*v*s - 5*s^2,
    z*u - w*t + 3*w*s + t*u + t*s - u^2 + u*v - 3*u*s - v^2 + v*s - s^2,
    z*v + w*u - 2*w*v - 2*w*s - 2*t^2 + 2*t*u + t*v + 8*t*s - u*v - 4*u*s + 2*v^2 - 3*v*s - 6*s^2,
    z*s + w*u - w*v - w*s - t^2 + t*u + t*v + 3*t*s - u*v - 2*u*s + v^2 - 2*v*s - 2*s^2
]) >;


// ---- N = 581,  [ <7, 1>, <83, 1> ],  special points = 4 ----
models[581] := rec< ModelRec | N := 581, genus := 8, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + z*s + w*t + 2*w*u - 2*w*v - 4*w*s - 6*t^2 + 7*t*u + 5*t*v + 3*t*s - 5*u^2 - 2*u*v - 7*u*s - v*s - 2*s^2,
    x*w - y*z + z*s + w*t - w*v - 3*w*s - t^2 + 3*t*s + u^2 - 3*u*s + v^2 - v*s + s^2,
    x*t - z^2 + z*s + w*t - 2*w*s - t*u - t*v + t*s + 2*u^2 - 2*u*v + 2*u*s + v^2 - v*s + 3*s^2,
    x*u - z*w + w*t + w*u - t^2 + t*v + t*s - 2*u*v - 2*u*s + s^2,
    x*v + 3*z*s - w^2 + 3*w*u - w*v - 2*w*s - 3*t^2 + 2*t*u + 2*t*v + 3*t*s - 3*u^2 - 5*u*s - 5*v*s - 3*s^2,
    x*s + 2*z*s + w*u - w*v - w*s - 2*t^2 + 2*t*u + 2*t*v - 2*u^2 - 3*u*s - 2*v*s - 3*s^2,
    y*w - z^2 + 2*z*s - w*u + 2*t^2 - 2*t*u - 2*t*v + 2*u^2 + 3*u*s + v^2 - 2*v*s + s^2,
    y*t - z*w + w*u + 2*w*s - t*u - t*s + u^2 - u*v + u*s,
    y*u + 3*z*s - w^2 + 4*w*u - w*v - 2*w*s - 3*t^2 + t*u + 2*t*v + 4*t*s - 2*u^2 - 7*u*s + v^2 - 4*v*s - 3*s^2,
    y*v - w*t - w*u + 2*w*s + t^2 - 3*t*s - u^2 + 4*u*s - v^2 - s^2,
    y*s + 2*z*s + w*u - w*v - t^2 + t*v - u^2 + u*v - 3*u*s - 2*v*s - 2*s^2,
    z*t - w^2 + 2*w*u - w*s - 2*t^2 + t*u + t*v + t*s - u^2 - 3*u*s - s^2,
    z*u + z*s - w*t + w*u - t^2 + t*u + t*v - 2*u^2 - 2*u*s - v*s - 2*s^2,
    z*v - 2*w*u + 2*w*s + t^2 - t*v - 2*t*s - u^2 + u*v + u*s - v^2 - s^2,
    4*z*s + 3*w*u - 2*w*v - w*s - 3*t^2 + 2*t*u + 2*t*v + 2*t*s - 3*u^2 + u*v - 6*u*s + v^2 - 4*v*s - 4*s^2
]) >;


// ---- N = 606,  [ <2, 1>, <3, 1>, <101, 1> ],  special points = 10 ----
models[606] := rec< ModelRec | N := 606, genus := 8, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x*z - y^2 + w*t + 4*w*u + 6*w*v - 8*w*s - 6*t^2 - 5*t*u + 6*t*v + 13*t*s - u*v + u*s - 5*v^2 - 8*v*s - 3*s^2,
    x*w - y*z + w*t - 12*w*u + 3*w*s + 11*t^2 - 11*t*v - 9*t*s + 2*u^2 - 9*u*v + 8*u*s - v^2 + 14*v*s - 2*s^2,
    x*t - z^2 - 19*w*u - 6*w*v + 17*w*s + 19*t^2 + 5*t*u - 20*t*v - 28*t*s + 4*u^2 - 11*u*v + 6*u*s + 6*v^2 + 23*v*s + 2*s^2,
    x*u - z*w + w*t - 3*w*u + 3*w*s + 3*t^2 - t*u - 3*t*v - 3*t*s + u^2 - 3*u*v + 3*v*s,
    x*v - w^2 - 3*w*u + 3*w*s + 3*t^2 - 4*t*v - 2*t*s + u^2 - 3*u*v + u*s + 2*v*s - s^2,
    x*s - w*u + w*s + u^2 - u*v - u*s - v*s - s^2,
    y*w - z^2 - 15*w*u - 7*w*v + 14*w*s + 16*t^2 + 5*t*u - 16*t*v - 24*t*s + 3*u^2 - 7*u*v + 4*u*s + 6*v^2 + 19*v*s + 3*s^2,
    y*t - z*w - 2*w*u - w*v + 4*w*s + 2*t^2 - 3*t*v - 3*t*s + u^2 - u*v + v^2 + 2*v*s,
    y*u - w^2 + 4*w*u - w*v - 3*t^2 + t*u + 3*t*v - u^2 + 3*u*v - 4*u*s + 2*v^2 - 4*v*s + 2*s^2,
    y*v - w*t - w*v + 2*w*s + t*u - t*s - u*s,
    y*s + 3*w*u - w*v - w*s - 3*t^2 + 3*t*v + 2*t*s + 3*u*v - 3*u*s + v^2 - 5*v*s + s^2,
    z*t - w^2 + 5*w*u + w*v - 2*w*s - 5*t^2 - t*u + 4*t*v + 4*t*s - u^2 + 3*u*v - 2*u*s - 5*v*s,
    z*u - w*t + 3*w*u + 2*w*v - 3*w*s - 3*t^2 - t*u + 4*t*v + 5*t*s - u^2 + u*v - 2*u*s - 2*v^2 - 4*v*s,
    z*v + w*u + w*v - w*s - 2*t^2 - t*u + t*v + 4*t*s - v^2 - 3*v*s - s^2,
    z*s + 5*w*u + w*v - 4*w*s - 5*t^2 - t*u + 5*t*v + 6*t*s - u^2 + 3*u*v - 2*u*s - v^2 - 6*v*s - s^2
]) >;


// ---- N = 651,  [ <3, 1>, <7, 1>, <31, 1> ],  special points = 9 ----
models[651] := rec< ModelRec | N := 651, genus := 8, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + 7*z*s - 2*w*t + 59*w*u + 53*w*v - 69*w*s - 56*t^2 - 74*t*u + 71*t*v + 32*t*s - 20*u^2 + 9*u*v - 16*u*s - 25*v^2 - 53*v*s + 50*s^2,
    x*w - y*z + y*s + 11*z*s - 2*w*t + 80*w*u + 71*w*v - 95*w*s - 80*t^2 - 103*t*u + 98*t*v + 43*t*s - 20*u^2 + 17*u*v - 31*u*s - 29*v^2 - 81*v*s + 73*s^2,
    x*t - z^2 + 8*z*s - w*t + 44*w*u + 40*w*v - 53*w*s - 43*t^2 - 58*t*u + 53*t*v + 25*t*s - 14*u^2 + 8*u*v - 13*u*s - 18*v^2 - 41*v*s + 37*s^2,
    x*u - z*w + 9*z*s - w*t + 57*w*u + 52*w*v - 67*w*s - 56*t^2 - 76*t*u + 69*t*v + 32*t*s - 16*u^2 + 11*u*v - 19*u*s - 22*v^2 - 56*v*s + 49*s^2,
    x*v + 8*z*s - w^2 - 2*w*t + 55*w*u + 50*w*v - 63*w*s - 54*t^2 - 72*t*u + 66*t*v + 32*t*s - 16*u^2 + 11*u*v - 18*u*s - 22*v^2 - 53*v*s + 46*s^2,
    x*s + 4*z*s - 3*w*t + 33*w*u + 29*w*v - 38*w*s - 32*t^2 - 39*t*u + 41*t*v + 17*t*s - 9*u^2 + 6*u*v - 13*u*s - 13*v^2 - 32*v*s + 30*s^2,
    y*w - z^2 + 5*z*s + 26*w*u + 22*w*v - 32*w*s - 28*t^2 - 32*t*u + 35*t*v + 13*t*s - 7*u^2 + 5*u*v - 11*u*s - 10*v^2 - 27*v*s + 26*s^2,
    y*t - z*w + 3*z*s + 11*w*u + 10*w*v - 12*w*s - 12*t^2 - 16*t*u + 13*t*v + 7*t*s - 2*u^2 + 3*u*v - 5*u*s - 3*v^2 - 13*v*s + 9*s^2,
    y*u + 5*z*s - w^2 + 35*w*u + 32*w*v - 41*w*s - 36*t^2 - 46*t*u + 44*t*v + 20*t*s - 10*u^2 + 6*u*v - 11*u*s - 14*v^2 - 35*v*s + 31*s^2,
    y*v + 9*z*s - w*t + 60*w*u + 55*w*v - 72*w*s - 62*t^2 - 81*t*u + 74*t*v + 36*t*s - 16*u^2 + 13*u*v - 21*u*s - 23*v^2 - 61*v*s + 53*s^2,
    y*s + 3*z*s + 23*w*u + 20*w*v - 28*w*s - 26*t^2 - 28*t*u + 31*t*v + 12*t*s - 5*u^2 + 5*u*v - 11*u*s - 8*v^2 - 26*v*s + 24*s^2,
    z*t - w^2 + 2*w*u + 3*w*v - w*s - 2*t^2 - 4*t*u + 2*t*v + 2*t*s - 2*u^2 + 2*u*s - 2*v^2 - v*s,
    z*u + z*s - w*t + 12*w*u + 11*w*v - 14*w*s - 12*t^2 - 15*t*u + 14*t*v + 7*t*s - 3*u^2 + 3*u*v - 6*u*s - 4*v^2 - 12*v*s + 11*s^2,
    z*v + 7*z*s + 51*w*u + 49*w*v - 62*w*s - 52*t^2 - 72*t*u + 62*t*v + 32*t*s - 17*u^2 + 10*u*v - 12*u*s - 21*v^2 - 51*v*s + 43*s^2,
    8*z*s + 54*w*u + 50*w*v - 65*w*s - 54*t^2 - 74*t*u + 65*t*v + 32*t*s - 16*u^2 + 11*u*v - 16*u*s - 21*v^2 - 53*v*s + 46*s^2
]) >;


// ---- N = 654,  [ <2, 1>, <3, 1>, <109, 1> ],  special points = 11 ----
models[654] := rec< ModelRec | N := 654, genus := 8, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x*z - y^2 + z*s + 3*w*u - w*v - w*s - 2*t^2 + 2*t*u + 2*t*v + 4*t*s + u^2 - 6*u*v - 7*u*s + v^2 + v*s + 2*s^2,
    x*w - y*z + 5*w*u - w*v + 2*w*s - 6*t^2 - t*v + 8*t*s + u^2 - 8*u*v - 13*u*s + 3*v^2 + 5*v*s - 2*s^2,
    x*t - z^2 + 4*z*s - 6*w*u - 3*w*v - 5*w*s + 6*t^2 - t*u + 2*t*v - 9*t*s - u^2 + 11*u*v + 15*u*s - v^2 - 4*v*s + 5*s^2,
    x*u - z*w + 2*z*s - w*u - w*v + t^2 - t*u + t*v - 2*t*s - u^2 + u*v + 3*u*s,
    x*v + z*s - w^2 - 5*w*u + w*v + 5*t^2 - t*u - 6*t*s + 7*u*v + 11*u*s - 2*v^2 - 5*v*s + s^2,
    x*s - w*t + 2*w*u - w*v + w*s - 3*t^2 + 4*t*s - 3*u*v - 5*u*s + 2*v^2 + 2*v*s - s^2,
    y*w - z^2 + 2*z*s - 4*w*u - 2*w*v - 4*w*s + 4*t^2 - t*u + t*v - 6*t*s - u^2 + 8*u*v + 10*u*s - v^2 - 2*v*s + 3*s^2,
    y*t - z*w + 2*z*s - w*u - w*v + t^2 - t*u - 4*t*s - u^2 + 3*u*v + 4*u*s,
    y*u + 2*z*s - w^2 - 8*w*u - w*s + 8*t^2 - 2*t*u - 10*t*s - u^2 + 12*u*v + 17*u*s - 2*v^2 - 6*v*s + 2*s^2,
    y*v + 2*z*s - w*t - 3*w*u - 2*w*v - 2*w*s + 3*t^2 + 2*t*v - 4*t*s - u^2 + 5*u*v + 8*u*s - v^2 - 3*v*s + 2*s^2,
    y*s + 2*z*s - 8*w*u - w*v - 3*w*s + 7*t^2 - 2*t*u + t*v - 10*t*s - u^2 + 12*u*v + 18*u*s - 2*v^2 - 5*v*s + 2*s^2,
    z*t + 2*z*s - w^2 - 8*w*u - w*s + 8*t^2 - 2*t*u - 11*t*s - u^2 + 12*u*v + 19*u*s - 2*v^2 - 6*v*s + 2*s^2,
    z*u + z*s - w*t - 2*w*u - w*v - w*s + 2*t^2 + t*v - 2*t*s - u^2 + 2*u*v + 5*u*s - v*s + s^2,
    z*v + z*s - 4*w*u - w*s + 3*t^2 - t*u - 4*t*s + 5*u*v + 8*u*s - v^2 - 3*v*s + s^2,
    5*z*s - 13*w*u - 3*w*v - 7*w*s + 13*t^2 - 2*t*u + 4*t*v - 18*t*s - 2*u^2 + 20*u*v + 31*u*s - 4*v^2 - 9*v*s + 7*s^2
]) >;


// ---- N = 665,  [ <5, 1>, <7, 1>, <19, 1> ],  special points = 7 ----
models[665] := rec< ModelRec | N := 665, genus := 8, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x*z - y^2 + 2*z*v + z*s + w*t + 9*w*v - 4*w*s - t^2 + 3*t*u - 9*t*v - 3*t*s - 8*u^2 - 3*u*v - 6*u*s + v^2 + 13*v*s + 41*s^2,
    x*w - y*z + 2*z*v + 3*z*s + w*t + 3*w*v - 6*w*s - t^2 + t*u - 2*t*v + 2*t*s - 3*u^2 + u*v - 2*u*s - 2*v^2 - v*s + 13*s^2,
    x*t - z^2 + 5*z*v + 3*z*s + w*u + 4*w*v - w*s - t^2 - 2*t*v - 2*t*s - 3*u^2 - 2*u*v - 3*u*s - 5*v^2 - v*s + 13*s^2,
    x*u - z*w + w*t + w*v - 2*w*s - t*v - t*s - u^2 - u*v - 2*u*s + v^2 + 4*v*s + 3*s^2,
    x*v + 4*z*v + 2*z*s + 5*w*v + w*s - t^2 + t*u - 5*t*v - 4*t*s - 4*u^2 - 7*u*v - 5*u*s - 2*v^2 + 5*v*s + 24*s^2,
    x*s + 5*z*v + z*s + 6*w*v - 6*t*v - 10*t*s - 6*u^2 - 5*u*v - 5*u*s - 3*v^2 + 11*v*s + 31*s^2,
    y*w - z^2 + 4*z*v + 2*z*s + w*u - 2*w*v - w*s - 2*t*u + t*v - 3*t*s - u^2 + u*v - u*s - 4*v^2 + 3*s^2,
    y*t - z*w + z*v + 2*z*s + w*u + w*s - t^2 - t*u + 2*t*v + t*s + u^2 + u*s - 3*v^2 - 8*v*s - 6*s^2,
    y*u + 4*z*v + 2*z*s - w^2 + w*u + 4*w*v + 3*w*s - 5*t*v - 7*t*s - 4*u^2 - 7*u*v - 5*u*s - v^2 + 6*v*s + 19*s^2,
    y*v + 5*z*v + z*s + 4*w*v + 2*w*s - t*u - 5*t*v - 10*t*s - 4*u^2 - 7*u*v - 4*u*s - 3*v^2 + 10*v*s + 26*s^2,
    y*s + 2*z*s + w*u - w*v + w*s - t^2 + 2*t*v + 4*t*s + u^2 - u*s - v^2 - 9*v*s - 7*s^2,
    z*t + 3*z*v - w^2 + 6*w*v + w*s - 6*t*v - 9*t*s - 5*u^2 - 3*u*v - 3*u*s - 2*v^2 + 10*v*s + 25*s^2,
    z*u + z*s - w*t + w*v + 3*w*s + t*u - t*v + t*s - 3*u*v - u*s + v^2 - 3*v*s - s^2,
    6*z*v + z*s + 6*w*v + w*s - 7*t*v - 11*t*s - 6*u^2 - 7*u*v - 5*u*s - 3*v^2 + 13*v*s + 35*s^2,
    3*z*s + w*u + w*s - t^2 + t*v + 4*t*s + u^2 - u*v - u*s - 8*v*s - 5*s^2
]) >;


// ---- N = 682,  [ <2, 1>, <11, 1>, <31, 1> ],  special points = 4 ----
models[682] := rec< ModelRec | N := 682, genus := 8, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x*z - y^2 + 4*z*s - 7*w*u + w*v - 6*w*s + 5*t^2 - 2*t*u - 4*t*v - 4*t*s + 6*u^2 - u*v - 26*u*s + v*s + 27*s^2,
    x*w - y*z + 2*w*t + 16*w*u - 7*w*v + 17*w*s - 15*t^2 + 3*t*u + 13*t*v + 3*t*s - 13*u^2 + u*v + 64*u*s - 3*v^2 + v*s - 69*s^2,
    x*t - z^2 + z*s + 3*w*u + 3*w*s - 2*t^2 - t*v + 2*t*s - 3*u^2 + u*v + 12*u*s + 3*v^2 - 13*s^2,
    x*u - z*w + 3*z*s - 6*w*u + 2*w*v - 7*w*s + 6*t^2 - 4*t*u - 7*t*v + 6*u^2 - 27*u*s + 2*v^2 - v*s + 27*s^2,
    x*v + 3*z*s - w^2 - 6*w*u + 2*w*v - 5*w*s + 7*t^2 - 2*t*u - 7*t*v - 2*t*s + 3*u^2 - 3*u*v - 19*u*s + 2*v^2 + 8*v*s + 22*s^2,
    x*s + 2*z*s - 4*w*u + w*v - 5*w*s + 4*t^2 - 2*t*u - 4*t*v - t*s + 4*u^2 - 18*u*s + v^2 - v*s + 18*s^2,
    y*w - z^2 + 4*z*s - 3*w*u + 3*w*v - 6*w*s + 5*t^2 - 2*t*u - 6*t*v + 4*u^2 - 19*u*s + 4*v^2 + 18*s^2,
    y*t - z*w - 2*w*u - 2*w*s + 2*t^2 - t*u - 3*t*v + 2*u^2 - 9*u*s + v^2 - v*s + 9*s^2,
    y*u + 3*z*s - w^2 - 4*w*u + w*v - w*s + 4*t^2 - t*u - 4*t*v - 2*t*s - 4*u*v - 7*u*s + 2*v^2 + 8*v*s + 9*s^2,
    y*v + 4*z*s - w*t - 15*w*u + 5*w*v - 17*w*s + 15*t^2 - 4*t*u - 13*t*v - 3*t*s + 13*u^2 - 2*u*v - 63*u*s + 3*v^2 + 66*s^2,
    y*s + 2*z*s - 3*w*u + w*v - 3*w*s + 3*t^2 - t*u - 3*t*v - t*s + 2*u^2 - u*v - 11*u*s + v^2 + v*s + 11*s^2,
    z*t + z*s - w^2 - w*u + w*s + t^2 - t*v - 2*t*s - 2*u^2 - 3*u*v + 4*u*s + 9*v*s - s^2,
    z*u + 2*z*s - w*t - 11*w*u + 4*w*v - 13*w*s + 11*t^2 - 4*t*u - 10*t*v - t*s + 10*u^2 - u*v - 48*u*s + 2*v^2 + 50*s^2,
    z*v + 4*z*s - 8*w*u + 2*w*v - 8*w*s + 7*t^2 - 2*t*u - 6*t*v - 4*t*s + 7*u^2 - 2*u*v - 32*u*s + v*s + 33*s^2,
    5*z*s - 9*w*u + 3*w*v - 10*w*s + 9*t^2 - 3*t*u - 8*t*v - 3*t*s + 8*u^2 - 2*u*v - 38*u*s + 2*v^2 + 2*v*s + 39*s^2
]) >;


// ---- N = 715,  [ <5, 1>, <11, 1>, <13, 1> ],  special points = 5 ----
models[715] := rec< ModelRec | N := 715, genus := 8, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 11*z*s - 18*w*u - 31*w*s + 20*t^2 - 11*t*u - 2*t*v + 16*t*s + 46*u^2 - 55*u*v + 38*u*s + 15*v^2 - 22*v*s - 6*s^2,
    x*w - y*z + z*v + z*s - 3*w*u - 2*w*v - 4*w*s + 3*t^2 - t*u + 2*t*s + 7*u^2 - 6*u*v + 7*u*s - v^2 - 4*v*s - 3*s^2,
    x*t - z^2 + z*v + 12*z*s - 15*w*u - w*v - 33*w*s + 15*t^2 - 11*t*u + 3*t*v + 19*t*s + 40*u^2 - 52*u*v + 34*u*s + 15*v^2 - 22*v*s - s^2,
    x*u - z*w + 23*z*s - 30*w*u - 63*w*s + 30*t^2 - 23*t*u + 9*t*v + 40*t*s + 78*u^2 - 103*u*v + 68*u*s + 30*v^2 - 46*v*s - 5*s^2,
    x*v + 24*z*s - w^2 - 31*w*u - 64*w*s + 31*t^2 - 24*t*u + 10*t*v + 40*t*s + 80*u^2 - 105*u*v + 72*u*s + 30*v^2 - 49*v*s - 5*s^2,
    x*s + z*v + 25*z*s - w*t - 32*w*u - w*v - 66*w*s + 32*t^2 - 24*t*u + 10*t*v + 40*t*s + 81*u^2 - 107*u*v + 73*u*s + 32*v^2 - 49*v*s - 5*s^2,
    y*w - z^2 + 20*z*s - 24*w*u - w*v - 55*w*s + 24*t^2 - 18*t*u + 6*t*v + 35*t*s + 65*u^2 - 88*u*v + 53*u*s + 28*v^2 - 35*v*s - 2*s^2,
    y*t - z*w + 27*z*s - 35*w*u + w*v - 74*w*s + 35*t^2 - 27*t*u + 8*t*v + 47*t*s + 92*u^2 - 121*u*v + 79*u*s + 36*v^2 - 53*v*s - 6*s^2,
    y*u + z*v + 11*z*s - w^2 - 13*w*u - 27*w*s + 12*t^2 - 11*t*u + 7*t*v + 17*t*s + 31*u^2 - 44*u*v + 31*u*s + 14*v^2 - 22*v*s,
    y*v + z*v + 20*z*s - w*t - 25*w*u - w*v - 51*w*s + 24*t^2 - 19*t*u + 10*t*v + 31*t*s + 61*u^2 - 81*u*v + 58*u*s + 23*v^2 - 39*v*s - 3*s^2,
    y*s + z*v + 6*z*s - 9*w*u - 14*w*s + 7*t^2 - 5*t*u + 3*t*v + 7*t*s + 17*u^2 - 21*u*v + 18*u*s + 5*v^2 - 13*v*s - s^2,
    z*t + z*v + 10*z*s - w^2 - 12*w*u - 23*w*s + 11*t^2 - 10*t*u + 6*t*v + 12*t*s + 28*u^2 - 37*u*v + 29*u*s + 11*v^2 - 20*v*s,
    z*u + z*v + 17*z*s - w*t - 22*w*u - w*v - 42*w*s + 21*t^2 - 16*t*u + 8*t*v + 24*t*s + 51*u^2 - 67*u*v + 49*u*s + 20*v^2 - 32*v*s - 2*s^2,
    2*z*v + 13*z*s - 18*w*u - w*v - 32*w*s + 16*t^2 - 12*t*u + 6*t*v + 17*t*s + 39*u^2 - 49*u*v + 40*u*s + 13*v^2 - 26*v*s - 2*s^2,
    29*z*s - 37*w*u - w*v - 77*w*s + 37*t^2 - 28*t*u + 11*t*v + 47*t*s + 95*u^2 - 124*u*v + 85*u*s + 36*v^2 - 56*v*s - 7*s^2
]) >;


// ---- N = 759,  [ <3, 1>, <11, 1>, <23, 1> ],  special points = 5 ----
models[759] := rec< ModelRec | N := 759, genus := 8, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 89*z*s - w*t - 6*w*u - 12*w*v + 71*w*s + 8*t^2 + 9*t*u + 13*t*v - 66*t*s + 8*u^2 - 143*u*v + 80*u*s + 81*v^2 + 15*v*s - 252*s^2,
    x*w - y*z + 17*z*s - 2*w*u + w*v + 9*w*s + 4*t^2 - 3*t*u - 2*t*v - 11*t*s + u^2 - 18*u*v + 15*u*s + 12*v^2 - 34*s^2,
    x*t - z^2 + 128*z*s - w*t - 6*w*u - 22*w*v + 93*w*s + 7*t^2 + 24*t*u + 13*t*v - 87*t*s + 12*u^2 - 207*u*v + 104*u*s + 120*v^2 + 34*v*s - 376*s^2,
    x*u - z*w + 22*z*s - w*t - 2*w*u + 19*w*s + 3*t^2 + 2*t*v - 14*t*s + u^2 - 32*u*v + 19*u*s + 18*v^2 + v*s - 60*s^2,
    x*v + 66*z*s - w^2 - w*t - 2*w*u - 14*w*v + 52*w*s + 3*t^2 + 14*t*u + 10*t*v - 45*t*s + 7*u^2 - 114*u*v + 56*u*s + 64*v^2 + 19*v*s - 208*s^2,
    x*s + 123*z*s - 5*w*u - 26*w*v + 94*w*s + 5*t^2 + 25*t*u + 19*t*v - 87*t*s + 12*u^2 - 207*u*v + 103*u*s + 118*v^2 + 33*v*s - 373*s^2,
    y*w - z^2 + 67*z*s - 3*w*u - 12*w*v + 44*w*s + 3*t^2 + 15*t*u + 5*t*v - 44*t*s + 6*u^2 - 107*u*v + 51*u*s + 63*v^2 + 20*v*s - 194*s^2,
    y*t - z*w + 113*z*s - 4*w*u - 24*w*v + 86*w*s + 3*t^2 + 25*t*u + 17*t*v - 78*t*s + 11*u^2 - 191*u*v + 93*u*s + 109*v^2 + 32*v*s - 346*s^2,
    y*u + 9*z*s - w^2 + w*u - 6*w*v + 8*w*s - 2*t^2 + 7*t*u + 3*t*v - 4*t*s + 2*u^2 - 22*u*v + 3*u*s + 12*v^2 + 8*v*s - 42*s^2,
    y*v + 38*z*s - w*t - w*u - 10*w*v + 31*w*s + 11*t*u + 8*t*v - 27*t*s + 4*u^2 - 69*u*v + 32*u*s + 38*v^2 + 12*v*s - 124*s^2,
    y*s + 39*z*s - w*u - 10*w*v + 30*w*s + t^2 + 10*t*u + 6*t*v - 28*t*s + 4*u^2 - 68*u*v + 32*u*s + 39*v^2 + 13*v*s - 124*s^2,
    z*t + 113*z*s - w^2 - 3*w*u - 27*w*v + 88*w*s + 3*t^2 + 26*t*u + 19*t*v - 81*t*s + 12*u^2 - 197*u*v + 95*u*s + 112*v^2 + 35*v*s - 354*s^2,
    z*u + 2*z*s - w*t - w*v + 5*w*s + 3*t*v - 2*t*s - 7*u*v + 4*u*s + 3*v^2 - v*s - 12*s^2,
    z*v + 17*z*s - 7*w*v + 16*w*s - t^2 + 6*t*u + 6*t*v - 15*t*s + 2*u^2 - 34*u*v + 15*u*s + 18*v^2 + 7*v*s - 58*s^2,
    132*z*s - 5*w*u - 28*w*v + 100*w*s + 5*t^2 + 28*t*u + 20*t*v - 93*t*s + 13*u^2 - 223*u*v + 110*u*s + 127*v^2 + 37*v*s - 400*s^2
]) >;


// ---- N = 782,  [ <2, 1>, <17, 1>, <23, 1> ],  special points = 3 ----
models[782] := rec< ModelRec | N := 782, genus := 8, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + z*v - 4*w*u - 2*w*v + 3*w*s + 4*t^2 + 2*t*u - 4*t*v - t*s - u*v - u*s - 2*v^2 - v*s + 5*s^2,
    x*w - y*z + 4*w*u + 2*w*v - 3*w*s - 4*t^2 - 2*t*u + 6*t*v - 2*u^2 - u*v + 4*u*s - v^2 - 4*s^2,
    x*t - z^2 + 9*w*u + 6*w*v - 9*w*s - 9*t^2 - 6*t*u + 10*t*v + 2*t*s - 2*u^2 - u*v + 9*u*s - 8*s^2,
    x*u - z*w + 3*w*u + 3*w*v - w*s - 3*t^2 - 2*t*u + 3*t*v - u^2 - u*v + 2*u*s - 3*s^2,
    x*v - w^2 - 3*w*u - 3*w*v + 3*w*s + 3*t^2 + 3*t*u - 4*t*v + 2*u^2 - 3*u*s - v*s + 3*s^2,
    x*s + z*v - w*t - 10*w*u - 7*w*v + 8*w*s + 9*t^2 + 7*t*u - 11*t*v - t*s + 4*u^2 + 2*u*v - 10*u*s + v^2 - 3*v*s + 9*s^2,
    y*w - z^2 + z*v + 4*w*u + 4*w*v - 5*w*s - 5*t^2 - 4*t*u + 6*t*v + 2*t*s - 2*u^2 - u*v + 6*u*s - v^2 - 5*s^2,
    y*t - z*w + z*v + 3*w*u + 4*w*v - 2*w*s - 4*t^2 - 4*t*u + 4*t*v - 2*u^2 - u*v + 6*u*s - 2*v^2 + 2*v*s - 4*s^2,
    y*u + z*v - w^2 - 8*w*u - 5*w*v + 8*w*s + 7*t^2 + 5*t*u - 9*t*v + 2*u^2 + u*v - 8*u*s - 2*v*s + 7*s^2,
    y*v + z*v - w*t - 6*w*u - 3*w*v + 5*w*s + 5*t^2 + 3*t*u - 7*t*v + 2*u^2 + u*v - 5*u*s - v*s + 5*s^2,
    y*s + z*v - 8*w*u - 4*w*v + 6*w*s + 6*t^2 + 4*t*u - 8*t*v + 2*u^2 + u*v - 6*u*s - 2*v*s + 6*s^2,
    z*t - w^2 - 5*w*u - 4*w*v + 5*w*s + 5*t^2 + 4*t*u - 7*t*v - t*s + 2*u^2 + u*v - 6*u*s + v^2 - v*s + 6*s^2,
    z*u + z*v - w*t - 11*w*u - 7*w*v + 8*w*s + 10*t^2 + 7*t*u - 12*t*v + 4*u^2 + u*v - 10*u*s + v^2 - 3*v*s + 10*s^2,
    2*z*v - 6*w*u - 2*w*v + 5*w*s + 4*t^2 + 2*t*u - 5*t*v - 2*u*s - 2*v^2 - v*s + 4*s^2,
    z*s - 6*w*u - 5*w*v + 5*w*s + 6*t^2 + 4*t*u - 7*t*v - t*s + 2*u^2 + u*v - 6*u*s + v^2 - v*s + 5*s^2
]) >;


// ---- N = 805,  [ <5, 1>, <7, 1>, <23, 1> ],  special points = 6 ----
models[805] := rec< ModelRec | N := 805, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 13*z*v - 18*z*s + 25*w*v + 22*w*s - 25*t^2 - 33*t*u + 27*t*v + 36*t*s + 15*u*v - 18*u*s - 8*v^2 - 56*v*s + 20*s^2,
    x*w - y*z,
    x*t + x*v - z^2 + 15*z*v - 17*z*s - 3*w^2 + 24*w*v + 20*w*s - 26*t^2 - 30*t*u + 27*t*v + 35*t*s + 4*u^2 + 13*u*v - 27*u*s - 9*v^2 - 61*v*s + 22*s^2,
    x*u - z*w + 11*z*v - 14*z*s + 22*w*v + 22*w*s - 23*t^2 - 29*t*u + 24*t*v + 32*t*s + 13*u*v - 17*u*s - 7*v^2 - 48*v*s + 16*s^2,
    x*v + 8*z*v - 10*z*s - 2*w^2 + 13*w*v + 11*w*s - 14*t^2 - 16*t*u + 15*t*v + 19*t*s + 2*u^2 + 7*u*v - 15*u*s - 5*v^2 - 33*v*s + 12*s^2,
    x*s + 8*z*v - 10*z*s - w*t + 16*w*v + 15*w*s - 16*t^2 - 20*t*u + 17*t*v + 22*t*s + 9*u*v - 12*u*s - 5*v^2 - 34*v*s + 10*s^2,
    y*w - z^2 + 10*z*v - 11*z*s + 18*w*v + 18*w*s - 20*t^2 - 25*t*u + 20*t*v + 29*t*s + u^2 + 11*u*v - 14*u*s - 6*v^2 - 43*v*s + 14*s^2,
    y*t + y*v - z*w + 11*z*v - 13*z*s - 3*w*t + 23*w*v + 25*w*s - 22*t^2 - 26*t*u + 21*t*v + 27*t*s + 11*u*v - 18*u*s - 6*v^2 - 42*v*s + 12*s^2,
    y*u + 17*z*v - 22*z*s - w^2 + 32*w*v + 30*w*s - 34*t^2 - 43*t*u + 36*t*v + 49*t*s + u^2 + 19*u*v - 25*u*s - 11*v^2 - 74*v*s + 26*s^2,
    y*v + 5*z*v - 6*z*s - 2*w*t + 11*w*v + 10*w*s - 10*t^2 - 12*t*u + 10*t*v + 13*t*s + 5*u*v - 8*u*s - 3*v^2 - 20*v*s + 6*s^2,
    y*s + 4*z*v - 5*z*s + 8*w*v + 7*w*s - 9*t^2 - 11*t*u + 10*t*v + 13*t*s + 5*u*v - 6*u*s - 3*v^2 - 19*v*s + 6*s^2,
    z*t + 7*z*v - 10*z*s - w^2 + 14*w*v + 13*w*s - 15*t^2 - 18*t*u + 16*t*v + 21*t*s + u^2 + 8*u*v - 13*u*s - 5*v^2 - 33*v*s + 12*s^2,
    z*u + z*v - z*s - w*t + 2*w*v - w*s - 2*t^2 - 2*t*u + 3*t*v + 2*t*s + u*v - 2*u*s - v^2 - 4*v*s + 2*s^2,
    18*z*v - 23*z*s + 34*w*v + 33*w*s - 36*t^2 - 45*t*u + 37*t*v + 50*t*s + u^2 + 20*u*v - 27*u*s - 11*v^2 - 76*v*s + 26*s^2,
    w*u + w*v + w*s - t^2 - 2*t*u + t*v + t*s - u^2 + u*v + u*s - v*s
]) >;


// ---- N = 814,  [ <2, 1>, <11, 1>, <37, 1> ],  special points = 5 ----
models[814] := rec< ModelRec | N := 814, genus := 8, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x*z - y^2 + 3*z*s - 2*w*u + 3*w*v + 4*w*s + 3*t^2 - 6*t*u - 5*t*v - 4*t*s + 3*u^2 + 2*u*v - u*s + 4*v^2 - 5*v*s - 4*s^2,
    x*w - y*z + 3*z*s + w*v + 3*w*s + t^2 - 5*t*u - 2*t*v - 3*t*s + 4*u*v - 4*u*s + 2*v^2 - 2*v*s - 5*s^2,
    x*t - z^2 + 2*w*u - w*v + w*s - t^2 + t*u + 2*t*s - 2*u^2 - u*v - 2*u*s + v^2,
    x*u - z*w + z*s - 2*w*u + 6*w*v + 2*w*s + 2*t^2 - 7*t*u - 4*t*v - 4*t*s + 2*u^2 + 5*u*v - 3*u*s - v*s - 8*s^2,
    x*v - w^2 - 3*w*u + 8*w*v + 2*w*s + 3*t^2 - 9*t*u - 5*t*v - 6*t*s + 4*u^2 + 5*u*v - 4*v*s - 8*s^2,
    x*s - w*t - 2*w*u + 4*w*v + 2*t^2 - 4*t*u - 2*t*v - 3*t*s + 2*u^2 + 2*u*v + u*s - 2*v*s - 4*s^2,
    y*w - z^2 + z*s - w*u + w*v + t^2 - t*u - 2*t*v + u*v - u*s + v^2 - v*s - 2*s^2,
    y*t - z*w + z*s - 2*w*u + 5*w*v + w*s + 2*t^2 - 5*t*u - 4*t*v - 4*t*s + 2*u^2 + 4*u*v - u*s - v*s - 6*s^2,
    y*u + 4*z*s - w^2 - 11*w*u + 22*w*v + 6*w*s + 11*t^2 - 26*t*u - 17*t*v - 17*t*s + 11*u^2 + 16*u*v - 2*u*s + 4*v^2 - 11*v*s - 25*s^2,
    y*v + 4*z*s - w*t - 12*w*u + 24*w*v + 5*w*s + 12*t^2 - 28*t*u - 18*t*v - 19*t*s + 12*u^2 + 19*u*v - 2*u*s + 2*v^2 - 9*v*s - 29*s^2,
    y*s + z*s - 4*w*u + 7*w*v + w*s + 3*t^2 - 8*t*u - 5*t*v - 6*t*s + 4*u^2 + 6*u*v - u*s - 2*v*s - 9*s^2,
    z*t - w^2 - w*u + 2*w*v + t^2 - 2*t*u - t*v - 2*t*s + 2*u^2 + 2*u*s - 2*v*s,
    z*u + z*s - w*t - 4*w*u + 8*w*v + w*s + 4*t^2 - 9*t*u - 5*t*v - 7*t*s + 4*u^2 + 6*u*v - 2*v*s - 9*s^2,
    z*v + z*s - 6*w*u + 10*w*v + 2*w*s + 5*t^2 - 11*t*u - 8*t*v - 8*t*s + 6*u^2 + 7*u*v + v^2 - 4*v*s - 11*s^2,
    5*z*s - 10*w*u + 19*w*v + 6*w*s + 10*t^2 - 24*t*u - 16*t*v - 16*t*s + 10*u^2 + 16*u*v - 3*u*s + 4*v^2 - 9*v*s - 24*s^2
]) >;


// ---- N = 930,  [ <2, 1>, <3, 1>, <5, 1>, <31, 1> ],  special points = 9 ----
models[930] := rec< ModelRec | N := 930, genus := 8, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x*z - y^2 + z*t + 144*z*s - w^2 - w*t + 223*w*u - 228*w*s - 221*t^2 - 291*t*u + 510*t*v + 264*t*s - 131*u^2 + 345*u*v + 112*u*s - 290*v^2 - 369*v*s - 25*s^2,
    x*w - y*z + y*s + 59*z*s - w*t + 89*w*u - w*v - 92*w*s - 89*t^2 - 117*t*u + 206*t*v + 107*t*s - 54*u^2 + 137*u*v + 47*u*s - 117*v^2 - 147*v*s - 12*s^2,
    x*t - z^2 + 2*z*t + 133*z*s - 2*w^2 - w*t + 201*w*u - 2*w*v - 205*w*s - 200*t^2 - 263*t*u + 464*t*v + 237*t*s - 120*u^2 + 309*u*v + 104*u*s - 265*v^2 - 331*v*s - 25*s^2,
    x*u - z*w + z*t + 44*z*s - w^2 - w*t + 69*w*u + 3*w*v - 68*w*s - 68*t^2 - 90*t*u + 154*t*v + 82*t*s - 40*u^2 + 106*u*v + 33*u*s - 87*v^2 - 115*v*s - 8*s^2,
    x*v + 2*z*t + 128*z*s - 3*w^2 + 197*w*u - w*v - 200*w*s - 196*t^2 - 257*t*u + 454*t*v + 232*t*s - 116*u^2 + 303*u*v + 100*u*s - 260*v^2 - 325*v*s - 23*s^2,
    x*s + 114*z*s - 2*w*t + 174*w*u + w*v - 179*w*s - 173*t^2 - 228*t*u + 401*t*v + 208*t*s - 104*u^2 + 268*u*v + 90*u*s - 229*v^2 - 288*v*s - 22*s^2,
    y*w + y*s - z^2 + 135*z*s + 199*w*u - 5*w*v - 209*w*s - 202*t^2 - 261*t*u + 474*t*v + 238*t*s - 122*u^2 + 304*u*v + 108*u*s - 272*v^2 - 327*v*s - 27*s^2,
    y*t - z*w + 101*z*s + 153*w*u - 159*w*s - 154*t^2 - 200*t*u + 357*t*v + 182*t*s - 90*u^2 + 235*u*v + 78*u*s - 206*v^2 - 251*v*s - 18*s^2,
    y*u + 63*z*s - w^2 + 94*w*u - w*v - 97*w*s - 95*t^2 - 124*t*u + 223*t*v + 112*t*s - 57*u^2 + 146*u*v + 50*u*s - 128*v^2 - 157*v*s - 12*s^2,
    y*v + 2*z*t + 53*z*s - 2*w^2 - w*t + 84*w*u + 2*w*v - 84*w*s - 84*t^2 - 109*t*u + 192*t*v + 99*t*s - 48*u^2 + 129*u*v + 41*u*s - 110*v^2 - 139*v*s - 9*s^2,
    y*s + z*t + 57*z*s - w^2 + 87*w*u - 90*w*s - 89*t^2 - 114*t*u + 206*t*v + 104*t*s - 52*u^2 + 133*u*v + 46*u*s - 118*v^2 - 144*v*s - 11*s^2,
    3*z*t + 102*z*s - 3*w^2 + 159*w*u + w*v - 161*w*s - 159*t^2 - 208*t*u + 366*t*v + 187*t*s - 92*u^2 + 247*u*v + 79*u*s - 209*v^2 - 264*v*s - 17*s^2,
    z*u + 17*z*s - w*t + 27*w*u + w*v - 27*w*s - 27*t^2 - 36*t*u + 62*t*v + 33*t*s - 16*u^2 + 43*u*v + 13*u*s - 35*v^2 - 46*v*s - 3*s^2,
    z*v + 54*z*s + 82*w*u - 86*w*s - 83*t^2 - 108*t*u + 193*t*v + 98*t*s - 48*u^2 + 128*u*v + 42*u*s - 112*v^2 - 137*v*s - 9*s^2,
    149*z*s + 226*w*u - 2*w*v - 235*w*s - 226*t^2 - 296*t*u + 527*t*v + 268*t*s - 134*u^2 + 350*u*v + 116*u*s - 303*v^2 - 373*v*s - 26*s^2
]) >;


// ---- N = 966,  [ <2, 1>, <3, 1>, <7, 1>, <23, 1> ],  special points = 6 ----
models[966] := rec< ModelRec | N := 966, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + z*s - 6*w*u - 19*w*v + 12*w*s + 3*t^2 + 20*t*u + 3*t*v - 34*t*s - u^2 - 6*u*v - 4*u*s + 5*v^2 + 17*v*s + 11*s^2,
    x*w - y*z + z*s + 2*w*t - 4*w*u - 22*w*v + 12*w*s + 4*t^2 + 19*t*u + 2*t*v - 38*t*s - u^2 + u*v - 2*u*s + 6*v^2 + 9*v*s + 7*s^2,
    x*t - z^2 + 3*w*u + 11*w*v - 8*w*s - 2*t^2 - 11*t*u - 3*t*v + 19*t*s + 2*u^2 + 5*u*v - u*s - 2*v^2 - 9*v*s - 3*s^2,
    x*u - z*w + z*s + 2*w*v - 2*w*s + t^2 - 4*t*u - t*v + 5*t*s + 2*u^2 - 3*u*s + v^2 - v*s,
    x*v + z*s - w^2 + w*v + 2*w*s - t*u + t*s - 3*u^2 - u*v + 6*u*s - v^2 - 4*s^2,
    x*s + z*s - w*u - w*v + t^2 - t*s + u^2 - u*v - 3*u*s + v^2 + v*s + 2*s^2,
    y*w - z^2 + z*s + 5*w*u + 20*w*v - 13*w*s - 3*t^2 - 20*t*u - 3*t*v + 36*t*s + 3*u^2 + 4*u*v - u*s - 4*v^2 - 14*v*s - 8*s^2,
    y*t - z*w + z*s - 2*w*u - 5*w*v + 4*w*s + 2*t^2 + 4*t*u - 9*t*s - u*v - 2*u*s + 2*v^2 + 3*v*s + 2*s^2,
    y*u - w^2 + 3*w*u + 18*w*v - 8*w*s - 3*t^2 - 17*t*u - 3*t*v + 29*t*s - u^2 + 4*u*v + 6*u*s - 5*v^2 - 13*v*s - 9*s^2,
    y*v + z*s - w*t + 2*w*v - 2*t*u + t*v + 5*t*s - u^2 - 3*u*v + 2*u*s - v^2 - 3*s^2,
    y*s + z*s + w*u + 8*w*v - 4*w*s - t^2 - 8*t*u - t*v + 14*t*s + u*v + u*s - 2*v^2 - 6*v*s - 4*s^2,
    z*t - w^2 + w*u + 3*w*v + w*s - t^2 - 3*t*u + 3*t*s - 3*u^2 + u*v + 7*u*s - 2*v^2 - 3*v*s - 4*s^2,
    z*u - w*t - w*u - w*v + w*s + t^2 + t*u + t*v - 4*u*v - 2*u*s + v^2 + 4*v*s + s^2,
    z*v + z*s - w*u - 3*w*v + 3*w*s + 3*t*u + t*v - 5*t*s - u^2 - 2*u*v + u*s + 2*v*s,
    2*z*s - w*u - w*v + 2*w*s + t^2 + t*u + t*v - t*s - u^2 - 3*u*v + u*s + v^2 + 2*v*s - 2*s^2
]) >;


// ---- N = 1001,  [ <7, 1>, <11, 1>, <13, 1> ],  special points = 3 ----
models[1001] := rec< ModelRec | N := 1001, genus := 8, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + 117*z*s + 203*w*u - 208*w*v + 46*w*s - 202*t^2 + 89*t*u + 132*t*v - 161*t*s - 57*u^2 - 30*u*v - 100*u*s + 150*v^2 + 67*v*s - 91*s^2,
    x*w - y*z + 156*z*s + 269*w*u - 276*w*v + 61*w*s - 267*t^2 + 118*t*u + 169*t*v - 212*t*s - 76*u^2 - 42*u*v - 134*u*s + 200*v^2 + 86*v*s - 121*s^2,
    x*t - z^2 + 102*z*s + 174*w*u - 176*w*v + 40*w*s - 174*t^2 + 76*t*u + 109*t*v - 138*t*s - 48*u^2 - 29*u*v - 87*u*s + 128*v^2 + 54*v*s - 79*s^2,
    x*u - z*w + 153*z*s + 264*w*u - 269*w*v + 61*w*s - 263*t^2 + 117*t*u + 165*t*v - 208*t*s - 75*u^2 - 43*u*v - 132*u*s + 196*v^2 + 83*v*s - 119*s^2,
    x*v + 72*z*s - w^2 + 126*w*u - 128*w*v + 30*w*s - 125*t^2 + 56*t*u + 77*t*v - 98*t*s - 35*u^2 - 22*u*v - 62*u*s + 94*v^2 + 38*v*s - 56*s^2,
    x*s + 9*z*s - w*t + 17*w*u - 19*w*v + 3*w*s - 16*t^2 + 8*t*u + 10*t*v - 12*t*s - 5*u^2 - 2*u*v - 8*u*s + 14*v^2 + 6*v*s - 7*s^2,
    y*w - z^2 + 129*z*s + 221*w*u - 224*w*v + 50*w*s - 221*t^2 + 97*t*u + 137*t*v - 174*t*s - 61*u^2 - 37*u*v - 111*u*s + 163*v^2 + 68*v*s - 100*s^2,
    y*t - z*w + 104*z*s + 179*w*u - 183*w*v + 41*w*s - 179*t^2 + 79*t*u + 114*t*v - 143*t*s - 51*u^2 - 27*u*v - 89*u*s + 133*v^2 + 58*v*s - 81*s^2,
    y*u + 104*z*s - w^2 + 180*w*u - 182*w*v + 42*w*s - 180*t^2 + 79*t*u + 113*t*v - 142*t*s - 50*u^2 - 30*u*v - 90*u*s + 133*v^2 + 56*v*s - 81*s^2,
    y*v + 72*z*s - w*t + 125*w*u - 127*w*v + 28*w*s - 125*t^2 + 56*t*u + 79*t*v - 98*t*s - 35*u^2 - 20*u*v - 62*u*s + 92*v^2 + 39*v*s - 56*s^2,
    y*s + 10*z*s + 17*w*u - 18*w*v + 4*w*s - 18*t^2 + 9*t*u + 8*t*v - 13*t*s - 4*u^2 - 5*u*v - 8*u*s + 14*v^2 + 4*v*s - 8*s^2,
    z*t + 157*z*s - w^2 + 272*w*u - 278*w*v + 63*w*s - 272*t^2 + 121*t*u + 170*t*v - 215*t*s - 76*u^2 - 44*u*v - 134*u*s + 203*v^2 + 86*v*s - 122*s^2,
    z*u + 121*z*s - w*t + 209*w*u - 213*w*v + 47*w*s - 209*t^2 + 92*t*u + 133*t*v - 165*t*s - 58*u^2 - 33*u*v - 104*u*s + 154*v^2 + 67*v*s - 94*s^2,
    z*v + 36*z*s + 62*w*u - 64*w*v + 14*w*s - 63*t^2 + 28*t*u + 40*t*v - 50*t*s - 17*u^2 - 10*u*v - 30*u*s + 46*v^2 + 20*v*s - 28*s^2,
    180*z*s + 311*w*u - 318*w*v + 71*w*s - 311*t^2 + 138*t*u + 196*t*v - 246*t*s - 87*u^2 - 50*u*v - 154*u*s + 231*v^2 + 99*v*s - 140*s^2
]) >;


// ---- N = 1155,  [ <3, 1>, <5, 1>, <7, 1>, <11, 1> ],  special points = 6 ----
models[1155] := rec< ModelRec | N := 1155, genus := 8, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x*z - y^2 + 22*z*v + 13*z*s - w*t - 104*w*u + 352*w*v - 178*w*s + 82*t^2 - 401*t*u - 465*t*v + 415*t*s + 537*u^2 - 301*u*v - 163*u*s + 6*v^2 + 616*v*s - 429*s^2,
    x*w - y*z + y*s + z*v + 17*z*s - 42*w*u + 178*w*v - 96*w*s + 40*t^2 - 214*t*u - 243*t*v + 223*t*s + 280*u^2 - 151*u*v - 92*u*s + 11*v^2 + 317*v*s - 225*s^2,
    x*t - z^2 + 8*z*v + 6*z*s - w*t - 38*w*u + 126*w*v - 63*w*s + 30*t^2 - 144*t*u - 166*t*v + 147*t*s + 191*u^2 - 107*u*v - 56*u*s + 3*v^2 + 218*v*s - 154*s^2,
    x*u - z*w + 14*z*v + 10*z*s - w*t - 70*w*u + 238*w*v - 119*w*s + 56*t^2 - 272*t*u - 313*t*v + 279*t*s + 361*u^2 - 203*u*v - 108*u*s + 5*v^2 + 414*v*s - 290*s^2,
    x*v + 26*z*v + 4*z*s - w^2 - w*t - 95*w*u + 282*w*v - 136*w*s + 68*t^2 - 316*t*u - 373*t*v + 327*t*s + 429*u^2 - 246*u*v - 123*u*s - 2*v^2 + 499*v*s - 346*s^2,
    x*s + 29*z*v - 2*w*t - 98*w*u + 280*w*v - 133*w*s + 68*t^2 - 309*t*u - 364*t*v + 317*t*s + 421*u^2 - 243*u*v - 118*u*s - 4*v^2 + 489*v*s - 338*s^2,
    y*w - z^2 + 5*z*v + 11*z*s - 37*w*u + 139*w*v - 73*w*s + 32*t^2 - 164*t*u - 190*t*v + 172*t*s + 218*u^2 - 120*u*v - 69*u*s + 6*v^2 + 249*v*s - 176*s^2,
    y*t - z*w + 5*z*v + 21*z*s - 62*w*u + 246*w*v - 129*w*s + 56*t^2 - 293*t*u - 339*t*v + 308*t*s + 388*u^2 - 213*u*v - 125*u*s + 12*v^2 + 445*v*s - 314*s^2,
    y*u + 2*z*v + 4*z*s - w^2 - 16*w*u + 53*w*v - 26*w*s + 13*t^2 - 63*t*u - 77*t*v + 68*t*s + 86*u^2 - 49*u*v - 26*u*s + 2*v^2 + 102*v*s - 72*s^2,
    y*v + 14*y*s + 174*z*v - 58*z*s - w*t - 429*w*u + 904*w*v - 385*w*s + 226*t^2 - 977*t*u - 1247*t*v + 1062*t*s + 1427*u^2 - 871*u*v - 361*u*s - 84*v^2 + 1752*v*s - 1182*s^2,
    y*s + 8*z*v + 25*z*s - 81*w*u + 313*w*v - 164*w*s + 71*t^2 - 372*t*u - 431*t*v + 392*t*s + 494*u^2 - 272*u*v - 159*u*s + 14*v^2 + 567*v*s - 399*s^2,
    z*t + 7*z*v + 16*z*s - w^2 - 60*w*u + 231*w*v - 120*w*s + 53*t^2 - 271*t*u - 313*t*v + 282*t*s + 359*u^2 - 198*u*v - 114*u*s + 10*v^2 + 410*v*s - 288*s^2,
    z*u + 5*z*v + 20*z*s - w*t - 63*w*u + 254*w*v - 133*w*s + 58*t^2 - 300*t*u - 345*t*v + 313*t*s + 396*u^2 - 218*u*v - 128*u*s + 13*v^2 + 452*v*s - 318*s^2,
    13*z*v - 2*z*s - 36*w*u + 97*w*v - 46*w*s + 23*t^2 - 106*t*u - 127*t*v + 111*t*s + 147*u^2 - 86*u*v - 41*u*s - 4*v^2 + 173*v*s - 118*s^2,
    29*z*s - 64*w*u + 287*w*v - 155*w*s + 64*t^2 - 345*t*u - 393*t*v + 361*t*s + 451*u^2 - 244*u*v - 150*u*s + 19*v^2 + 511*v*s - 362*s^2
]) >;


// ---- N = 1190,  [ <2, 1>, <5, 1>, <7, 1>, <17, 1> ],  special points = 3 ----
models[1190] := rec< ModelRec | N := 1190, genus := 8, squarefree := true, hyperelliptic := false, special_points := 3, curve := Curve(P, [
    x*z - y^2 + 21*z*u - 21*w*t - 20*w*u - 79*w*v + 117*w*s + 21*t^2 + 79*t*u - 58*t*v - 23*t*s - 59*u^2 + 118*u*v - u*s + 18*v^2 - 35*v*s - 50*s^2,
    x*w - y*z + 7*z*u + 14*z*v - 7*w*t - 6*w*u + 5*w*v - 12*w*s - 8*t^2 - 6*t*u + 11*t*v - 3*t*s + 2*u^2 - 16*u*v + 12*u*s - 2*v^2 + 6*s^2,
    x*t - z^2 + 5*z*s - 4*w*u - 17*w*v + 22*w*s + 5*t^2 + 13*t*u - 10*t*v - t*s - 8*u^2 + 23*u*v + 4*u*s + 3*v^2 - 10*v*s - 14*s^2,
    x*u - z*w + 2*z*v + 11*z*s - 11*w*u - 31*w*v + 39*w*s + 9*t^2 + 20*t*u - 14*t*v - t*s - 13*u^2 + 40*u*v + 14*u*s + 6*v^2 - 21*v*s - 25*s^2,
    x*v + z*v + 4*z*s - w^2 - 3*w*u - 8*w*v + 10*w*s + 2*t^2 + 4*t*u - 2*t*v + t*s - 2*u^2 + 9*u*v + 6*u*s + v^2 - 7*v*s - 8*s^2,
    x*s + 10*z*s - w*t - 11*w*u - 38*w*v + 51*w*s + 12*t^2 + 28*t*u - 21*t*v - 3*t*s - 20*u^2 + 53*u*v + 11*u*s + 8*v^2 - 24*v*s - 29*s^2,
    y*w - z^2 + z*v + 9*z*s - 10*w*u - 30*w*v + 37*w*s + 9*t^2 + 21*t*u - 16*t*v - 3*t*s - 14*u^2 + 41*u*v + 11*u*s + 6*v^2 - 18*v*s - 23*s^2,
    y*t - z*w + z*v + 12*z*s - 11*w*u - 34*w*v + 45*w*s + 10*t^2 + 23*t*u - 16*t*v - 16*u^2 + 45*u*v + 14*u*s + 7*v^2 - 24*v*s - 28*s^2,
    y*u + z*v + 3*z*s - w^2 - 2*w*u - 4*w*v + 4*w*s + t^2 + t*u + t*s - u^2 + 4*u*v + 5*u*s + v^2 - 4*v*s - 4*s^2,
    y*v + 2*z*v + 2*z*s - w*t - 2*w*u - 2*w*v + w*s + t*v + t*s + u*v + 4*u*s - 3*v*s - 3*s^2,
    y*s + 7*z*v + w*u + 22*w*v - 33*w*s - 9*t^2 - 21*t*u + 19*t*v + 3*t*s + 14*u^2 - 36*u*v + 4*u*s - 5*v^2 + 9*v*s + 15*s^2,
    z*t + 2*z*v + 9*z*s - w^2 - 8*w*u - 23*w*v + 27*w*s + 6*t^2 + 14*t*u - 9*t*v - 8*u^2 + 28*u*v + 14*u*s + 4*v^2 - 16*v*s - 20*s^2,
    2*z*u + 2*z*v + 2*z*s - 2*w*t - 4*w*u - 10*w*v + 13*w*s + 2*t^2 + 8*t*u - 5*t*v - 2*t*s - 6*u^2 + 13*u*v + 4*u*s + 2*v^2 - 6*v*s - 7*s^2,
    3*z*v + 4*z*s - 4*w*u - 7*w*v + 7*w*s + t^2 + 3*t*u - t*v - 2*u^2 + 7*u*v + 7*u*s + v^2 - 6*v*s - 6*s^2,
    14*z*s - 15*w*u - 49*w*v + 64*w*s + 15*t^2 + 35*t*u - 26*t*v - 3*t*s - 24*u^2 + 67*u*v + 17*u*s + 10*v^2 - 31*v*s - 38*s^2
]) >;


// ==== special-points table (genus 8) ====
//   N : special points
//   293 : 5
//   346 : 10
//   362 : 9
//   381 : 10
//   383 : 3
//   403 : 7
//   415 : 6
//   427 : 6
//   431 : 5
//   479 : 4
//   505 : 6
//   511 : 7
//   534 : 11
//   545 : 6
//   559 : 6
//   573 : 4
//   581 : 4
//   606 : 10
//   651 : 9
//   654 : 11
//   665 : 7
//   682 : 4
//   715 : 5
//   759 : 5
//   782 : 3
//   805 : 6
//   814 : 5
//   930 : 9
//   966 : 6
//   1001 : 3
//   1155 : 6
//   1190 : 3

