// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = 3.
// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical
// saturated-HNF star basis. Cusp forms not stored.
// All curves of this genus live in the single shared projective space P below.
//   models[N]`curve          : the curve X_0(N)^* in P
//   models[N]`special_points : number of special (CM + cusp) rational points

Q := Rationals();
P<x, y, z> := ProjectiveSpace(Q, 2);
ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, curve >;
models := AssociativeArray();


// ---- N = 97,  [ <97, 1> ],  special points = 10 ----
models[97] := rec< ModelRec | N := 97, genus := 3, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x^3*z - x^2*y^2 - 5*x^2*z^2 + x*y^3 + x*y^2*z + 3*x*y*z^2 + 6*x*z^3 - 3*y^2*z^2 - y*z^3 - 2*z^4
]) >;


// ---- N = 109,  [ <109, 1> ],  special points = 9 ----
models[109] := rec< ModelRec | N := 109, genus := 3, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x^3*z - 2*x^2*y*z - x^2*z^2 - x*y^3 + 6*x*y^2*z - 6*x*y*z^2 + 3*x*z^3 + y^4 - 6*y^3*z + 10*y^2*z^2 - 5*y*z^3
]) >;


// ---- N = 113,  [ <113, 1> ],  special points = 8 ----
models[113] := rec< ModelRec | N := 113, genus := 3, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x^3*z - x^2*y^2 - 4*x^2*z^2 + x*y^3 + 2*x*y^2*z + 6*x*z^3 - y^3*z - 3*y^2*z^2 + y*z^3 - 3*z^4
]) >;


// ---- N = 127,  [ <127, 1> ],  special points = 8 ----
models[127] := rec< ModelRec | N := 127, genus := 3, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x^3*z - x^2*y^2 - 3*x^2*z^2 + x*y^3 - x*y*z^2 + 4*x*z^3 + 2*y^3*z - 3*y^2*z^2 + 3*y*z^3 - 2*z^4
]) >;


// ---- N = 139,  [ <139, 1> ],  special points = 7 ----
models[139] := rec< ModelRec | N := 139, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x^3*z - x^2*y^2 - 2*x^2*z^2 + x*y^3 - 2*x*y^2*z + 2*x*y*z^2 + x*z^3 + y^4 - 2*y^3*z + 4*y^2*z^2 - 3*y*z^3
]) >;


// ---- N = 149,  [ <149, 1> ],  special points = 7 ----
models[149] := rec< ModelRec | N := 149, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x^3*z - x^2*y^2 - 3*x^2*z^2 + x*y^3 + 3*x*y^2*z - 2*x*y*z^2 + 2*x*z^3 - y^4 - y^2*z^2 + y*z^3
]) >;


// ---- N = 151,  [ <151, 1> ],  special points = 8 ----
models[151] := rec< ModelRec | N := 151, genus := 3, squarefree := true, hyperelliptic := false, special_points := 8, curve := Curve(P, [
    x^3*z - 2*x^2*y*z - 2*x^2*z^2 - x*y^3 + 2*x*y^2*z + 4*x*y*z^2 + x*z^3 + y^2*z^2 - 3*y*z^3 - 2*z^4
]) >;


// ---- N = 178,  [ <2, 1>, <89, 1> ],  special points = 10 ----
models[178] := rec< ModelRec | N := 178, genus := 3, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x^3*z - x^2*y^2 - 4*x^2*z^2 + 2*x*y^2*z + 3*x*y*z^2 + 3*x*z^3 - y^3*z - 2*y^2*z^2 - y*z^3
]) >;


// ---- N = 179,  [ <179, 1> ],  special points = 6 ----
models[179] := rec< ModelRec | N := 179, genus := 3, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x^3*z - 2*x^2*y*z - 2*x^2*z^2 - x*y^3 + 2*x*y^2*z + x*y*z^2 + 2*x*z^3 + y^2*z^2 - y*z^3 - z^4
]) >;


// ---- N = 183,  [ <3, 1>, <61, 1> ],  special points = 10 ----
models[183] := rec< ModelRec | N := 183, genus := 3, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    2*x^3*z - 2*x^2*y^2 - 5*x^2*z^2 + 2*x*y^3 - 2*x*y^2*z + 4*x*y*z^2 + 2*x*z^3 + y^4 + 2*y^3*z - y^2*z^2 - 2*y*z^3
]) >;


// ---- N = 185,  [ <5, 1>, <37, 1> ],  special points = 7 ----
models[185] := rec< ModelRec | N := 185, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    2*x^3*z - 2*x^2*y^2 - 7*x^2*z^2 + 8*x*y^2*z - 8*x*y*z^2 + 10*x*z^3 - 3*y^4 + 8*y^3*z - 12*y^2*z^2 + 12*y*z^3 - 5*z^4
]) >;


// ---- N = 187,  [ <11, 1>, <17, 1> ],  special points = 6 ----
models[187] := rec< ModelRec | N := 187, genus := 3, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + x*y^3 - x*y^2*z - x*y*z^2 + 2*x*z^3 + y^3*z - y^2*z^2 + 3*y*z^3
]) >;


// ---- N = 194,  [ <2, 1>, <97, 1> ],  special points = 10 ----
models[194] := rec< ModelRec | N := 194, genus := 3, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x^3*z - x^2*y^2 - 3*x^2*z^2 + x*y^3 + 3*x*y^2*z + x*y*z^2 + 2*x*z^3 - 2*y^3*z - y^2*z^2 - y*z^3
]) >;


// ---- N = 203,  [ <7, 1>, <29, 1> ],  special points = 6 ----
models[203] := rec< ModelRec | N := 203, genus := 3, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x^3*z - x^2*y^2 - 3*x^2*z^2 + x*y^3 + 3*x*y^2*z - 4*x*y*z^2 + 4*x*z^3 - y^4 + 3*y^3*z - 6*y^2*z^2 + 3*y*z^3 - 2*z^4
]) >;


// ---- N = 217,  [ <7, 1>, <31, 1> ],  special points = 6 ----
models[217] := rec< ModelRec | N := 217, genus := 3, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    3*x^3*z - 3*x^2*y^2 - 11*x^2*z^2 - 3*x*y^3 + 13*x*y^2*z - 2*x*y*z^2 + 11*x*z^3 - 2*y^4 - y^3*z - 4*y^2*z^2 + y*z^3 - 2*z^4
]) >;


// ---- N = 239,  [ <239, 1> ],  special points = 5 ----
models[239] := rec< ModelRec | N := 239, genus := 3, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + x*y^3 - x*y^2*z + x*z^3 + y^4 - y^3*z + y*z^3 - z^4
]) >;


// ---- N = 246,  [ <2, 1>, <3, 1>, <41, 1> ],  special points = 11 ----
models[246] := rec< ModelRec | N := 246, genus := 3, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 - x*y^2*z - x*y*z^2 + x*z^3 + 2*y^3*z + y^2*z^2 - y*z^3
]) >;


// ---- N = 249,  [ <3, 1>, <83, 1> ],  special points = 6 ----
models[249] := rec< ModelRec | N := 249, genus := 3, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + 2*x*y^2*z + x*y*z^2 - x*z^3 - y^3*z + y^2*z^2 - y*z^3
]) >;


// ---- N = 258,  [ <2, 1>, <3, 1>, <43, 1> ],  special points = 11 ----
models[258] := rec< ModelRec | N := 258, genus := 3, squarefree := true, hyperelliptic := false, special_points := 11, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + x*y^3 - x*y^2*z + x*z^3 + 2*y^4 - y^3*z - y^2*z^2
]) >;


// ---- N = 282,  [ <2, 1>, <3, 1>, <47, 1> ],  special points = 9 ----
models[282] := rec< ModelRec | N := 282, genus := 3, squarefree := true, hyperelliptic := false, special_points := 9, curve := Curve(P, [
    x^3*z - 2*x^2*z^2 + x*y^2*z - 3*x*y*z^2 - x*z^3 - y^4 + 2*y^2*z^2 + 3*y*z^3 + 2*z^4
]) >;


// ---- N = 290,  [ <2, 1>, <5, 1>, <29, 1> ],  special points = 10 ----
models[290] := rec< ModelRec | N := 290, genus := 3, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x^3*z - x^2*y^2 - 3*x^2*z^2 + 3*x*y*z^2 + 2*x*z^3 - y^3*z - 3*y^2*z^2 - 2*y*z^3
]) >;


// ---- N = 295,  [ <5, 1>, <59, 1> ],  special points = 5 ----
models[295] := rec< ModelRec | N := 295, genus := 3, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + x*y^3 - x*y^2*z + 2*x*y*z^2 - x*z^3 - y^3*z + 3*y^2*z^2 - y*z^3
]) >;


// ---- N = 303,  [ <3, 1>, <101, 1> ],  special points = 4 ----
models[303] := rec< ModelRec | N := 303, genus := 3, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + x*y^3 + 2*x*y^2*z + x*z^3 - y^4 - y^3*z - y^2*z^2
]) >;


// ---- N = 310,  [ <2, 1>, <5, 1>, <31, 1> ],  special points = 7 ----
models[310] := rec< ModelRec | N := 310, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 - x*y^2*z - x*y*z^2 - x*z^3 + 2*y^3*z + y^2*z^2 + 3*y*z^3
]) >;


// ---- N = 318,  [ <2, 1>, <3, 1>, <53, 1> ],  special points = 10 ----
models[318] := rec< ModelRec | N := 318, genus := 3, squarefree := true, hyperelliptic := false, special_points := 10, curve := Curve(P, [
    x^3*z - x^2*y^2 - 3*x^2*z^2 + 5*x*y*z^2 + 2*x*z^3 - y^3*z - 3*y^2*z^2 - 2*y*z^3
]) >;


// ---- N = 329,  [ <7, 1>, <47, 1> ],  special points = 4 ----
models[329] := rec< ModelRec | N := 329, genus := 3, squarefree := true, hyperelliptic := false, special_points := 4, curve := Curve(P, [
    x^3*z - x^2*y^2 + x*y^3 + x*y*z^2 + x*z^3 - y^3*z + 2*y*z^3 + z^4
]) >;


// ---- N = 429,  [ <3, 1>, <11, 1>, <13, 1> ],  special points = 5 ----
models[429] := rec< ModelRec | N := 429, genus := 3, squarefree := true, hyperelliptic := false, special_points := 5, curve := Curve(P, [
    x^3*z - x^2*y^2 - x^2*z^2 + x*y^3 + 2*x*y^2*z - 4*x*y*z^2 - x*z^3 - y^4 + 2*y^3*z - 2*y^2*z^2 - 2*y*z^3
]) >;


// ---- N = 430,  [ <2, 1>, <5, 1>, <43, 1> ],  special points = 7 ----
models[430] := rec< ModelRec | N := 430, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x^3*z - x^2*y^2 - x*y^3 - 3*x*y^2*z - 2*x*z^3 + 2*y^4 + 3*y^2*z^2 + z^4
]) >;


// ---- N = 455,  [ <5, 1>, <7, 1>, <13, 1> ],  special points = 7 ----
models[455] := rec< ModelRec | N := 455, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x^3*z - x^2*y^2 - x*y^3 - 3*x*y^2*z - 3*x*y*z^2 - 2*x*z^3 + 2*y^3*z + 3*y^2*z^2 + 2*y*z^3 + z^4
]) >;


// ---- N = 462,  [ <2, 1>, <3, 1>, <7, 1>, <11, 1> ],  special points = 6 ----
models[462] := rec< ModelRec | N := 462, genus := 3, squarefree := true, hyperelliptic := false, special_points := 6, curve := Curve(P, [
    x^3*z - x^2*y^2 + 2*x^2*z^2 - 7*x*y^2*z - x*y*z^2 - 6*x*z^3 + 4*y^4 + 2*y^3*z + 7*y^2*z^2 + 2*y*z^3 + 3*z^4
]) >;


// ---- N = 510,  [ <2, 1>, <3, 1>, <5, 1>, <17, 1> ],  special points = 7 ----
models[510] := rec< ModelRec | N := 510, genus := 3, squarefree := true, hyperelliptic := false, special_points := 7, curve := Curve(P, [
    x^3*z - 2*x^2*y^2 + 2*x^2*y*z - 4*x^2*z^2 + x*y^3 + 11*x*y^2*z - 16*x*y*z^2 + 5*x*z^3 - 12*y^4 + 32*y^3*z - 31*y^2*z^2 + 13*y*z^3 - 2*z^4
]) >;


// ==== special-points table (genus 3) ====
//   N : special points
//   97 : 10
//   109 : 9
//   113 : 8
//   127 : 8
//   139 : 7
//   149 : 7
//   151 : 8
//   178 : 10
//   179 : 6
//   183 : 10
//   185 : 7
//   187 : 6
//   194 : 10
//   203 : 6
//   217 : 6
//   239 : 5
//   246 : 11
//   249 : 6
//   258 : 11
//   282 : 9
//   290 : 10
//   295 : 5
//   303 : 4
//   310 : 7
//   318 : 10
//   329 : 4
//   429 : 5
//   430 : 7
//   455 : 7
//   462 : 6
//   510 : 7

