// scripts/gen_genus_models.m
//
// Run directly (from the repo root):
//   magma -b scripts/gen_genus_models.m               // default: genus 5 and 6
//   magma -b g:=7 scripts/gen_genus_models.m           // one genus only
//   magma -b g:=8 eval_prec:=1500 scripts/gen_genus_models.m  // override eval_prec (default 3000)
//
// Build the X_0(N)^* models for every squarefree level N whose star-quotient
// genus is exactly g, and emit one Magma-loadable file per genus:
//   data/genus5_models.m ... data/genus8_models.m
//
// Each model is re-expressed in the canonical saturated-HNF basis of the +1
// Atkin-Lehner eigenspace of S_2(Gamma_0(N)) (see src/hnf_canonical.m), so
// the equations are basis-independent.  All curves of a given genus live in a
// single shared, named projective space P.  Cusp forms are not stored; the
// number of special (CM + cusp) rational points is recorded.
//
// Pipeline note: the special-point machinery (RationalCMDiscs) assumes N is
// squarefree, so non-squarefree levels of the same genus are skipped.
//
// This script deliberately does not route model construction through the
// disk cache in data/starmodels/ (StarModelWithForms, src/star_model_cache.m).
// The search entry points read that cache by default, so the call below opts
// out explicitly with UseCache := false:
// reusing a cached starforms_<N>.m entry reproduces the identical curve but
// through a *different* choice of ideal generators than a fresh
// XZeroNstarWithForms computation would pick, HNF canonicalizes the
// coordinate system, not which specific polynomials generate the ideal in
// it. That would break the exact-diff acceptance test this pipeline
// requires (regenerate and diff against the committed files, resolve any
// mismatch before release), for a result that's correct but not identical.
// So every level is built fresh via XZeroNstarWithForms + HNFCanonicalCurve
// every run. A killed multi-hour genus-8 run therefore has no resume mode:
// re-running redoes already-completed levels from scratch.
//
// Progress (one timestamped line per level, flushed immediately so a killed
// run's log is readable) goes to outputs/gen_genus_models_g<g>.progress;
// outputs/ is private and does not ship.

load "src/AtkinLehner.m";
load "src/hnf_canonical.m";

if not assigned g then
    gs := [5, 6];      // original default: both genus 5 and 6 in one run
else
    gs := [StringToInteger(g)];
end if;

B := 1000;    // point-search bound (cheap; not stored)
if not assigned eval_prec then
    eval_prec := 3000;    // q-expansion precision for model construction
else
    eval_prec := StringToInteger(eval_prec);
end if;

for g in gs do
    outfile  := Sprintf("data/genus%o_models.m", g);
    progfile := Sprintf("outputs/gen_genus_models_g%o.progress", g);
    names    := AmbientVarNames(g);

    procedure note(s)
        Write(progfile, Sprintf("[%o] %o\n", Cputime(), s));
    end procedure;

    Write(outfile,
        Sprintf("// X_0(N)^* models for squarefree N with genus(X_0(N)^*) = %o.\n", g) cat
        "// Auto-generated by scripts/gen_genus_models.m. Curves are in the canonical\n" cat
        "// saturated-HNF star basis. Cusp forms not stored.\n" cat
        "// All curves of this genus live in the single shared projective space P below.\n" cat
        "//   models[N]`curve          : the curve X_0(N)^* in P\n" cat
        "//   models[N]`special_points : number of special (CM + cusp) rational points\n\n" cat
        "Q := Rationals();\n" cat
        Sprintf("P<%o> := ProjectiveSpace(Q, %o);\n", Join(names, ", "), g-1) cat
        "ModelRec := recformat< N, genus, squarefree, hyperelliptic, special_points, curve >;\n" cat
        "models := AssociativeArray();\n"
        : Overwrite := true);

    summary := [];
    failed  := [];

    for entry in StarQuotientsOfGenusExactly(g) do
        N := entry[1];
        if not IsSquarefree(N) then continue; end if;
        printf "\n===== genus %o : N = %o  %o =====\n", g, N, Factorization(N);
        note(Sprintf("START N=%o %o", N, Factorization(N)));

        ok := true;
        try
            // UseCache := false: see the header note above. This is the one
            // caller that needs every level built the same fresh way, since it
            // diffs its output against the committed data/genus<g>_models.m.
            exc, pts, X, fs, Sstar, cm_pts := exceptional_pts_X0Nstar(N, B :
                eval_prec := eval_prec, UseCache := false);
        catch e
            printf "FAILED N=%o: %o\n", N, e`Object;
            note(Sprintf("FAILED N=%o: %o", N, e`Object));
            Append(~failed, N);
            ok := false;
        end try;
        if not ok then continue; end if;

        if IsHyperellipticX0Nstar(N) then
            printf "SKIP N=%o: hyperelliptic (no canonical embedding in P^%o)\n", N, g-1;
            note(Sprintf("SKIP N=%o: hyperelliptic", N));
            Append(~failed, N);
            continue;
        end if;

        special := 1;
        for d in Keys(cm_pts) do special +:= cm_pts[d]; end for;
        special := Integers() ! special;

        C   := HNFCanonicalCurveFromSstar(N, X, Sstar, g);
        eqs := CurveEqnsString(C, names);
        block := Sprintf("\n// ---- N = %o,  %o,  special points = %o ----\n", N, Factorization(N), special)
            cat Sprintf("models[%o] := rec< ModelRec | N := %o, genus := %o, squarefree := true, hyperelliptic := false, special_points := %o, curve := Curve(P, %o) >;\n",
                        N, N, g, special, eqs);
        Write(outfile, block);

        Append(~summary, <N, special>);
        printf "stored N=%o  special=%o\n", N, special;
        note(Sprintf("DONE N=%o special=%o", N, special));
    end for;

    tbl := "\n// ==== special-points table (genus " cat IntegerToString(g) cat ") ====\n//   N : special points\n";
    for t in summary do
        tbl cat:= Sprintf("//   %o : %o\n", t[1], t[2]);
    end for;
    if #failed gt 0 then
        tbl cat:= "// FAILED/SKIPPED levels (no model stored): " cat Sprint(failed) cat "\n";
    end if;
    Write(outfile, tbl);

    printf "\n##### genus %o done: %o models stored, %o failed/skipped #####\n", g, #summary, #failed;
    note(Sprintf("genus %o done: %o stored, %o failed/skipped", g, #summary, #failed));
end for;

exit;
