// src/fields_of_definition.m
//
// Fields of definition of the CM points on X_0(N)*, computed from ring class
// field data: their degree, and hence which discriminants give a point that is
// rational or of degree 2.
//
// Entry points:  DegreeOfFieldOfDefinitionOfCMPoint(N, d)     just the degree
//                FieldsOfDefinitionOfCMPoint(N, d)            the fields
//                RationalCMDiscs(N)                           rational discs
//                Degree2Points(N) / CountDegree2Points(N)     degree-2 discs
//
// Depends on cm_orders.m and star_quotients.m.



// rc_cache: AssociativeArray keyed by discriminant (negative integer).
// Stores the disc-only expensive bundle, NormGroup(RingClassField(R)) is the
// dominant cost, so it is computed at most once per discriminant across all N
// values in a genus loop.  Everything downstream of alSub is N-dependent and is
// rebuilt per call.
//
// This is FieldsOfDefinitionOfCMPointFast from ShimuraCurveALQuotients/SchoferFormula.m,
// specialised to D = 1 and W = all Atkin-Lehner involutions of N.  
function FieldsOfDefinitionOfCMPoint(N, d : rc_cache := AssociativeArray())
    R   := QuadraticOrder(BinaryQuadraticForms(d));
    K   := NumberField(R);
    f   := Conductor(R);
    OK  := Integers(K);
    chi := KroneckerCharacter(d);

    // Sorted, not a SetEnum: the w0 search below breaks on the first hit and
    // Magma's set iteration order is unspecified.  Any two valid w0 differ by an
    // element already in alSub, so the field is the same either way; but the
    // choice should not vary run to run.  (Divisors(N) is already sorted.)
    W := [m : m in Divisors(N) | GCD(m, N div m) eq 1];

    N_R      := &*[Integers()| p : p in PrimeDivisors(N) | chi(p) eq 1 or (f mod p eq 0)];
    N_star_R := &*[Integers()| p : p in PrimeDivisors(N) | chi(p) eq 1 and (f mod p ne 0)];

    assert GCD(N_star_R, Discriminant(R)) eq 1;
    assert GCD(N_R, Discriminant(R)) eq GCD(N, f);

    // Proposition 5.6 of Gonzalez Rotger.  Cheap arithmetic check; must run before
    // RingClassField.
    if (Discriminant(R) mod (N div N_star_R)) ne 0 then
        return [* *], rc_cache;
    end if;

    // Disc-only expensive bundle: computed once per discriminant, cached across N.
    disc_key := Discriminant(R);
    if not IsDefined(rc_cache, disc_key) then
        // AbelianExtension needs a genuine ray-class-group map: NormGroup of the
        // ring class field.  not PicardGroup (wrong tag) and not RayClassGroup(f*OK)
        // (wrong, larger group).
        mG_new := NormGroup(RingClassField(R));
        PicR_new, mPicR_new := PicardGroup(R);
        A2_new, PicR_to_A2_new := PicR_new / (2*PicR_new);
        rc_cache[disc_key] := <mG_new, Domain(mG_new), PicR_new, mPicR_new,
                               A2_new, PicR_to_A2_new>;
    end if;
    cached     := rc_cache[disc_key];
    mG         := cached[1];
    G          := cached[2];
    PicR       := cached[3];
    mPicR      := cached[4];
    A2         := cached[5];
    PicR_to_A2 := cached[6];

    // Lemma 5.9: the Atkin-Lehner-Galois subgroup of G = Gal(H_R/K), generated by
    // the Artin classes of the "square root" ideals frakb_mm for those w_mm in W
    // that act as Galois automorphisms.
    al_gen := [];
    for mm in W do
        if mm eq 1 then continue; end if;
        if (N div N_R) mod mm ne 0 then continue; end if;   // al_is_gal
        frakb := &*[Parent(1*OK) | pa[1]^(pa[2] div 2) : pa in Factorization(mm*OK)];
        Append(~al_gen, frakb @@ mG);
    end for;
    alSub := sub<G | al_gen>;

    // Lemma (CC): complex conjugation is realised by w_m . sigma_a with
    // m = N_star_R.  It identifies P with bar P on the quotient iff some mm in W
    // is a reflection m * w0 with w0 al_is_gal; then the reflection restricts to
    // A_abs as c . sigma_a . sigma_{w0}.  Depends only on W and ramification, so it
    // is settled before any number field is built.
    m := N_star_R;
    cc_active := false;
    w0 := 1;
    for mm in W do
        w := AtkinLehnerMul(m, mm, N);
        if (N div N_R) mod w eq 0 then   // w is al_is_gal
            cc_active := true;
            w0 := w;
            break;
        end if;
    end for;

    // A_abs = H_R fixed by alSub, built as an abelian extension of K.  The quotient
    // maps must be composed (Inverse(pi_quo)*mG); a fresh map<...|x :-> ...> lambda
    // strips the ray-class tag and AbelianExtension then rejects it.
    _, pi_quo := quo<G | alSub>;
    Aext := AbelianExtension(Inverse(pi_quo)*mG);
    NFA  := NumberField(Aext);
    Aabs := AbsoluteField(NFA);
    _, NFA_to_abs := IsIsomorphic(NFA, Aabs);

    if not cc_active then
        return [* Aabs *], rc_cache;   // field of definition contains K
    end if;

    // Complex conjugation on A_abs.  H_R is CM iff conjugation is central iff it acts
    // trivially by inversion on Gal(H_R/K) = Pic(R), i.e. iff Exponent(G) <= 2.
    if Exponent(G) le 2 then
        has_cc, cc := HasComplexConjugate(Aabs);
        assert has_cc;
    else
        // A_abs is not CM, so HasComplexConjugate fails; but conjugation is still one
        // automorphism (A_abs/Q is Galois): the one sending A_abs.1 to the
        // complex-conjugate root of its defining polynomial.  Do not enumerate order-2
        // automorphisms via AutomorphismGroup: that returns every reflection c.sigma,
        // of which only this one is genuinely complex conjugation, and the resulting
        // over-generation (exactly h candidates) is the bug this port fixes.
        // Named fpoly, not f; f is the conductor and is still live.
        fpoly   := DefiningPolynomial(Aabs);
        prec    := 40 + 4*Degree(Aabs);
        target  := ComplexConjugate(Conjugates(Aabs.1 : Precision := prec)[1]);
        roots_A := [r[1] : r in Roots(fpoly, Aabs)];
        diffs   := [Abs(Conjugates(r : Precision := prec)[1] - target) : r in roots_A];
        _, idx  := Minimum(diffs);
        // Guard the numerical pick.  The winning root should match `target` to nearly
        // full precision while every other conjugate sits O(1) away; if two candidates
        // are comparably close, `Minimum` silently chooses one and we return a wrong
        // field with no error.  Turn that into a crash.  The margin is deliberately
        // loose (10^10) so it only fires on genuine ambiguity, not on precision noise.
        sorted_diffs := Sort(diffs);
        error if #sorted_diffs ge 2 and sorted_diffs[1]*10^10 gt sorted_diffs[2],
            Sprintf("complex-conjugation pinning is ambiguous for d=%o at N=%o: "
                    * "closest root is %o away, runner-up %o (need a factor 10^10). "
                    * "Raise prec (currently %o) or pin cc another way.",
                    d, N, sorted_diffs[1], sorted_diffs[2], prec);
        cc := hom<Aabs -> Aabs | roots_A[idx]>;
    end if;

    B  := QuaternionAlgebra(1);   // the split algebra M_2(Q)
    am := ArtinMap(Aext);         // the FldAb ArtinMap; avoids the
                                  // ArtinMap(RingClassField(R)) "not in the codomain" bug

    // The extra Atkin-Lehner twist sigma_{w0} on A_abs from the reflection m*w0 in W.
    // At w0 = 1 (the full star quotient) Factorization is empty and this is the identity.
    frakb_w0 := &*[Parent(1*OK) | pa[1]^(pa[2] div 2) : pa in Factorization(w0*OK)];
    tw := (NFA_to_abs^-1)*am(frakb_w0)*NFA_to_abs;

    // Classes [a] in Pic(R)/Pic(R)^2 with B ~ (-s, m*N(a))_Q, as automorphisms of A_abs.
    // GR Remark (uniqueness): [a] is unique only for f = 1, hence the guarded break.
    sigma_as := [* *];
    for a in A2 do
        alift := a@@PicR_to_A2;
        // Guard the identity class: mPicR has a bug on PicR!0.
        fraka := (alift eq PicR!0) select 1*R else mPicR(alift);
        if not IsIsomorphic(QuaternionAlgebra(Rationals(), d, m*Norm(fraka)), B) then
            continue;
        end if;
        Append(~sigma_as, (NFA_to_abs^-1)*am(OK !! fraka)*NFA_to_abs);
        if IsFundamentalDiscriminant(d) then break; end if;
    end for;
    error if #sigma_as eq 0,
        "Error in field of definition - could not find a fractional ideal for complex conjugation!";

    // Q(P) = fixed field of the reflection c . sigma_a . sigma_{w0}; collect distinct.
    // Field-level IsIsomorphic dedup is fine here: there is one candidate when d is
    // fundamental and a small handful otherwise.  (It was catastrophic in the old
    // H_R-based code only because that code generated h of them.)
    fields := [* *];
    for sa in sigma_as do
        sigma := hom<Aabs -> Aabs | tw(cc(sa(Aabs.1)))>;
        F := FixedField(Aabs, [sigma]);
        is_new := true;
        for FF in fields do
            if IsIsomorphic(F, FF) then is_new := false; break; end if;
        end for;
        if is_new then Append(~fields, F); end if;
    end for;

    return fields, rc_cache;

end function;



function make_AL_fixed(S, N)
    //S  =  al_gens
    W := AllALsFromGens(S, N);
    fixedptAL := {* *};
    for m in W do
      if m eq 1 then continue; end if;
      if (m mod 4) eq (1 mod 4) then
        Include(~fixedptAL, -m*4);
      elif (m mod 4) eq (3 mod 4) then
        Include(~fixedptAL, -m);
        Include(~fixedptAL, -m*4);
      elif (m mod 4) eq (2 mod 4) and m ne 2 then
        Include(~fixedptAL, -m*4);
      elif m eq 2 then
        Include(~fixedptAL, -4);
        Include(~fixedptAL, -8);
      end if;
    end for;
    return fixedptAL;
end function;

//Even faster variation of degree of field of definition of CM point
function DegreeOfFieldOfDefinitionOfCMPoint(N, d)
    assert IsSquarefree(N);
    R := QuadraticOrder(BinaryQuadraticForms(d));
    f := Conductor(R);
    D := Discriminant(R);
    chi := KroneckerCharacter(d);
    N_R      := &*[Integers()| p : p in PrimeDivisors(N) | chi(p) eq 1 or (f mod p eq 0)];
    N_star_R := &*[Integers()| p : p in PrimeDivisors(N) | chi(p) eq 1 and (f mod p ne 0)];
    if D mod (N div N_star_R) ne 0 then
        return 0;
    end if;
    PicR, _ := PicardGroup(R);
    h_R := #PicR;
    fixedptAL := make_AL_fixed(Set(PrimeFactors(N)), N);
    if d in fixedptAL then eps := 1; else eps := 0; end if;
    deg := h_R / 2^(omega(N div N_R) - eps);
    return deg;
end function;


function RationalCMDiscs(N)
    //using Shimura Reciprocity, find which CM points are rational on X0(N)*
    assert IsSquarefree(Integers()!N);
    CNs := CMClassLists();
    cm_pts := AssociativeArray();
    omegaN := #PrimeFactors(N);
    iterates := [2^i : i in [0..omegaN]];
    fixedptAL := make_AL_fixed(Set(PrimeFactors(N)), N);
    discs := CNs;
    for n in iterates do
        if not IsDefined(discs, n) then
            error Sprintf("CMClassLists() missing class number %o; add CNs[%o] (omegaN=%o, N=%o)", n, n, omegaN, N);
        end if;
        for d in discs[n] do

            i := Valuation(n, 2);
            disc := -d;
            R := QuadraticOrder(BinaryQuadraticForms(disc));
            f_cond := Conductor(R);
            N_R_primes := {p : p in PrimeDivisors(N) | KroneckerCharacter(disc)(p) eq 1 or f_cond mod p eq 0};

            //first optimization is to look at the prime ideals corresponding to w_p in the class group and check if they generate the class group
            opt_emb := NumberOfOptimalEmbeddings(R, N);
            if opt_emb eq 0 then continue; end if;

            // Assume $N$ is squarefree and $\CM(R) \ne \emptyset$. Let  $\varepsilon(R)$ be 1 if R is an order that is fixed by an atkin lehner and 0 otherwise.
            // The field of definition of the points in $\overline{\CM}(R)$ has degree 
            // \[\frac{h(R)}{ 2^{\omega (N/N(R)) - \varepsilon(R) }}. \]

            deg := DegreeOfFieldOfDefinitionOfCMPoint(N, disc);
            if deg eq 1 then
                print "found CM point at discriminant", disc;
                if disc in fixedptAL then
                    den := 2^(omegaN-1);
                else
                    den := 2^omegaN;
                end if;
                cm_pts[disc] := opt_emb / den;
            end if;
        end for;
    end for;
    return cm_pts;
end function;

function Degree2Points(N : max_class_num := 0, compute_fields := true, rc_cache := AssociativeArray());
    //using Shimura Reciprocity, find which CM points are degree 2 on X0(N)*
    // max_class_num: if > 0, only consider discriminants with class number <= max_class_num (speeds up computation)
    // compute_fields: if true, also build the ring class field (field of definition) for each
    //   degree-2 disc via FieldsOfDefinitionOfCMPoint. This is the expensive part and is only
    //   needed for the confirmatory AlgebraicDeg2Matches check. When false, each entry's field
    //   slots are left as a placeholder (false) and the disc keys / multiplicities are still returned.
    // rc_cache: FieldsOfDefinitionOfCMPoint's disc-keyed cache of the expensive per-discriminant
    //   ring-class-field bundle (see that function's header). Threaded through and returned
    //   (updated) so a caller looping over several N values (e.g. analyze_exceptional) can share
    //   one cache instead of rebuilding the same discriminant's fields at every level that happens
    //   to share it.
    // Each entry is <multiplicity, fields, discriminants> where fields is the list of candidate
    //   fields of definition (the field of definition is genuinely multi-valued, see
    //   FieldsOfDefinitionOfCMPoint) and discriminants the matching list.
    CNs := CMClassListsDeg2();
    cm_pts := AssociativeArray();
    omegaN := #PrimeFactors(N);
    iterates := [2^i : i in [0..omegaN+1]];

    if max_class_num gt 0 then
        iterates := [n : n in iterates | n le max_class_num];
    end if;
    fixedptAL := make_AL_fixed(Set(PrimeFactors(N)), N);
    discs := CNs;
    for n in iterates do
        if not IsDefined(discs, n) then
            error Sprintf("CMClassListsDeg2() missing class number %o; add CNs[%o] (omegaN=%o, N=%o)", n, n, omegaN, N);
        end if;
        for d in discs[n] do
            disc := -d;
            R := QuadraticOrder(BinaryQuadraticForms(disc));
            opt_emb := NumberOfOptimalEmbeddings(R, N);
            if opt_emb eq 0 then continue; end if;

            // Fast degree check; only build the full ring class field if degree is 2.
            deg := DegreeOfFieldOfDefinitionOfCMPoint(N, disc);
            if deg ne 2 then continue; end if;

            if disc in fixedptAL then
                den := 2^(omegaN-1);
            else
                den := 2^omegaN;
            end if;
            if not compute_fields then
                // Skip the expensive ring class field build; field-of-definition slots
                // are placeholders (only AlgebraicDeg2Matches consumes them).
                cm_pts[disc] := <opt_emb/den, false, false>;
                continue;
            end if;
            flds, rc_cache := FieldsOfDefinitionOfCMPoint(N, disc : rc_cache := rc_cache);
            assert #flds ge 1;
            cm_pts[disc] := <opt_emb/den, flds, [* Discriminant(F) : F in flds *]>;
        end for;
    end for;
    return cm_pts, rc_cache;
end function;

function CountDegree2Points(N)
    cm_pts := Degree2Points(N : compute_fields := false);
    ks := Keys(cm_pts);
    sum := 0;
    for k in ks do
        sum +:= cm_pts[k][1];
    end for;
    return sum;
end function;
